### ISSUE TITLE
The drop rate of Fine Moonstalker Pelt is too high

### ISSUE THREAD

**Issue by petage** [the-hyjal-project/bugtracker#100]
**Describe Your Issue**

The drop rate of the quest item Fine Moonstalker Pelt is currently set to 80% for both of the mobs it drops off of.

**Steps To Reproduce**

``SELECT * FROM `creature_loot_template` WHERE `item`='5386';``

https://classic.wowhead.com/item=5386/fine-moonstalker-pelt

**Expected Behavior**

The drop rate should be significantly lower as [Classic Wowhead](https://classic.wowhead.com/item=5386/fine-moonstalker-pelt#dropped-by) and [Thottbot](https://web.archive.org/web/20070417121709/http://www.thottbot.com/i5386) suggest.

**Comment by ratkosrb** [comment]
Fixed in https://github.com/vmangos/core/commit/c1db8e8f625ba5dbba3c03a11eafb4411e1557db
