### ISSUE TITLE
Food crate in SW Canals "invalid target"

### ISSUE THREAD

**Issue by PennieLen** [the-hyjal-project/bugtracker#101]
**Describe Your Issue**
by the south east bridge in SW canals food crate gives red text "invalid target"

**Steps To Reproduce**

1.
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected Behavior**

lootable food

**Comment by Gamemechanicwow** [comment]
Try emptying your cache folder. That usually does the trick with crates :>

**Comment by PennieLen** [comment]
Several Food crates and Barrels of milk around Stormwind give read text "invalid target"

**Comment by PennieLen** [comment]
i see thank you

**Comment by kodolol** [comment]
Happened to me too. Fixed after clearing cache.

**Comment by kodolol** [comment]
#110 seems like this isn't limited to only Stormwind crates. Wonder if it's all crates in the game?

**Comment by Nolin7777** [comment]
Checked all chests around the canals of stormwind, none of them prints this error.
As @Gamemechanicwow said, this must be a caching issue.
