### ISSUE TITLE
Bugged Escort Quest: Rin'ji Is Trapped

### ISSUE THREAD

**Issue by ripcurl91** [the-hyjal-project/bugtracker#102]
**Describe Your Issue**
Escort NPC Rin'ji in the Hinterlands not aggroing anything

**Steps To Reproduce**

1. Accept the escort quest in the Hinterlands at 30,46

Quest: https://classic.wowhead.com/quest=2742/rinji-is-trapped
NPC: https://classic.wowhead.com/npc=7780/rinji

**Expected Behavior**
Rin'ji should attack mobs around him.

**Comment by Nolin7777** [comment]
Note: Wrong faction

**Comment by ratkosrb** [comment]
Should be fixed in https://github.com/vmangos/core/commit/0a24e43fe353853d860b5349c3677a6d9d9867db
