### ISSUE TITLE
"Rin'ji is Trapped" quest in the Hinterlands not working properly; NPC is not aggroing any mobs

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#103]
**Describe Your Issue**
"Rin'ji is Trapped" quest in the Hinterlands not working properly; NPC is not aggroing any mobs

**Steps To Reproduce**

1.
2. 
3. 

Quest: https://classic.wowhead.com/quest=2742/rinji-is-trapped
NPC: https://classic.wowhead.com/npc=7780/rinji

**Expected Behavior**

Rin'ji should attack mobs around him

**Comment by kodolol** [comment]
Duplicate of #102
