### ISSUE TITLE
The quests Covert Ops - Alpha and Covert Ops - Beta aren't available at the same time

### ISSUE THREAD

**Issue by petage** [the-hyjal-project/bugtracker#105]
**Describe Your Issue**

Covert Ops - Beta is only offered after completing Covert Ops - Alpha.

**Steps To Reproduce**

1. Complete the prerequisites Ineptitude + Chemicals = Fun and Special Delivery for Gaxim.
2. Notice how Gaxim Rustfizzle only offers Covert Ops - Alpha.
3. Complete Covert Ops - Alpha and only then you'll be offered Covert Ops - Beta.

https://classic.wowhead.com/npc=4077/gaxim-rustfizzle
https://classic.wowhead.com/quest=1074/ineptitude-chemicals-fun
https://classic.wowhead.com/quest=1077/special-delivery-for-gaxim
https://classic.wowhead.com/quest=1079/covert-ops-alpha
https://classic.wowhead.com/quest=1080/covert-ops-beta

**Expected Behavior**

Covert Ops - Beta should be offered at the same time as Covert Ops - Alpha. After completing the prerequisites mentioned, both Alpha and Beta should become available. See the [comment](https://classic.wowhead.com/quest=1079/covert-ops-alpha#comments:id=68639) made by 22655 and his [reply](https://classic.wowhead.com/quest=1079/covert-ops-alpha#comments:id=68639:reply=6425) where he corrects himself. Also notice the quests under Unlocks on the right-hand side of the pages [Ineptitude + Chemicals = Fun](https://classic.wowhead.com/quest=1074/ineptitude-chemicals-fun) and [Special Delivery for Gaxim](https://classic.wowhead.com/quest=1077/special-delivery-for-gaxim).

**Comment by NickTyrer** [comment]
Fix here https://github.com/vmangos/core/pull/983

**Comment by NickTyrer** [comment]
Fixed

**Comment by Gamemechanicwow** [comment]
Thanks @NickTyrer !
