### ISSUE TITLE
Pigman Kuz's Patrol

### ISSUE THREAD

**Issue by Simp-N** [the-hyjal-project/bugtracker#108]
**Describe Your Issue**
Kuz, one of the pigmen for the quest Betryal From Within in Southern Barrens, does not patrol on Hyjal PTR. Instead he spawns at about 45.2, 80.3, near a rock, and just stands there (like on many other pservers).

**Steps To Reproduce**
1. Go to the coords 45.2, 80.3
2. Observe Kuz standing there.

Kuz: https://classic.wowhead.com/npc=3436/kuz#comments
Betrayal From Within: https://classic.wowhead.com/quest=879/betrayal-from-within#comments

**Expected Behavior**
First of all, his spawn location is different. Secondly, he is supposed to patrol. If you look at the comments in the links above, you can see several people mention that Kuz patrols, going as far back as 2004. [Here](https://www.youtube.com/watch?v=jX9wGm27CSc) is also a video from vanilla, of Joana encoutering Kuz walking at a different spot than where he spawns on Hyjal. edit: Forgot to add timestamp for the video, about 24:00 in.

I'm afraid I don't know how to get the exact points for his spawn or patrol, but I've tried following him around in Classic, and getting the coordinates of whenever he changed direction. I also recorded it and it can be viewed [here](https://streamable.com/ayxwd3). Take notice that his spawn point isn't part of his patrol points, meaning that if you let him go his full patrol he will not cross his spawn point again. Also notice that at around 4:55 he walks over an object which looks a bit weird. Below are the coordinates noted.

Points:
43.970292806625 79.580938816071 <- Spawn point
43.804353475571 79.457235336304 <- First point of patrol
43.65947842598 79.118829965591
43.495827913284 78.954964876175
43.070542812347 78.972655534744
42.647922039032 79.873806238174
42.814671993256 80.231934785843
43.212002515793 80.472183227539
43.482410907745 80.486905574799
43.78490447998 81.404221057892
44.14165019989 81.446754932404
44.823837280273 80.945241451263
45.473915338516 80.917406082153
45.53427696228 80.467236042023
45.12767791748 80.312716960907
44.307075207748 80.706173181534
44.047904014587 80.590885877609
43.916255235672 80.417895317078
44.079220294952 79.993617534637
44.403862953186 79.853814840317
44.847095012665 79.870909452438
45.054465532303 79.751378297806
45.121163129807 79.220753908157
44.897270202637 78.868174552917
44.431746006012 78.68560552597 <- Last point of patrol
43.805915117264 79.437756538391 <- Back to first point of patrol

I understand the server doesn't use coordinates like this but I'm afraid I don't know what the server's equivalent would be. If you know of a method to get more exact points from him, please let me know and I could try it on Classic.

**Comment by NickTyrer** [comment]
Fixed here https://github.com/vmangos/core/pull/972
