### ISSUE TITLE
Water Barrel on the ground in Kharanos is not lootable

### ISSUE THREAD

**Issue by theloras** [the-hyjal-project/bugtracker#110]
**Describe Your Issue**
Water Barrel on the ground in Kharanos is not lootable

**Steps To Reproduce**
Click the barrel on the ground

It's right beside Golorn Frostbeard - and when I try to pick it up I get the error text,

"Invalid Target"

**Expected Behavior**
I should be able to loot it and have it drop into my bag inventory.

**Comment by theloras** [comment]
This issue is likewise present with the Food Crate on the ground across the road in Kharanos as well - next to Tharek Blackstone.

Get the same error code, "Invalid Target"

**Comment by theloras** [comment]
well lol at me cuz it would appear that ALL water barrels and food crates throughout the game cannot be looted...

I'm in Stormwind now and it's the same story here as well :(

**Comment by kodolol** [comment]
Try clearing your cache first. That usually fixed it for me.

**Comment by theloras** [comment]
good call - thanks!
