### ISSUE TITLE
NPCs will cancel their spellcast to flee

### ISSUE THREAD

**Issue by Simp-N** [the-hyjal-project/bugtracker#117]
**Describe Your Issue**
NPCs that can cast spells and who can flee, will cancel a spell if you get them below their "flee threshold" while they are casting. What they should do is finish casting their spell and *then* flee (or continue fighting if the spell cast was a heal). I have not tested this for every fleeing spellcasting NPC in the game, but I want to remember that all of those that I've encountered while leveling my paladin (lvl 26 so far) have had this issue. So it appears to be a general issue with spellcasting NPCs, and not just a select few of them. I have recorded some demonstrations of this, and of how it should work, with Thistlefur Shamans who can heal themselves, and Bristleback Geomancers who can cast Fireball. With this issue the healing is kind of useless since they only use it when they're low anyway, and the player don't really have to use their interrupting abilities as much.

**Steps To Reproduce**
Get a mob below its fleeing threshold while it's casting a spell.

Demonstrations:
[Furbolg's heal on Hyjal PTR](https://streamable.com/kto7st)
[Bristleback's Fireball on Hyjal PTR](https://streamable.com/8q7awf)

**Expected Behavior**
The mobs should finish their spellcast, and then flee if they're still low on HP.

Here are two recordings from Classic:
[Furbolg's heal on Classic](https://streamable.com/6zjvvf)
[Bristleback's Fireball on Classic](https://streamable.com/uzm3yh)

You can also watch [this video](https://www.youtube.com/watch?v=NrSdjsrhX0s) of Joana's 1-60 guide from vanilla, where he fights the Bristlebacks. Timestamps for examples: 
2:43:31
3:30:54
3:31:26

And [this video](https://www.youtube.com/watch?v=rFcE2P8E44c) for the Furbolgs. Timestamps:
38:40
42:46

Wowhead links to the NPCs in my examples
Bristleback Geomancer: https://classic.wowhead.com/npc=3263/bristleback-geomancer
Thistlefur Shaman: https://classic.wowhead.com/npc=3924/thistlefur-shaman

**Comment by High-Speed-Dirt** [comment]
I believe a similar issue affects mobs such as Syndicate Wizard as well.   This not only during the flee mechanic, but even if you get in range of a Syndicate Wizard that is casting, he will drop his cast and run out of melee range, and start to recast again.  You can endlessly interrupt this mobs casting by keeping it in melee range and chasing it around.  

I tested this on classic and the mob stays in melee range the whole time.  It does not try to outrange and cast.  

https://classic.wowhead.com/npc=2319/syndicate-wizard

**Comment by Nolin7777** [comment]
Awesome ticket!

**Comment by High-Speed-Dirt** [comment]
You guys rock.

**Comment by Simp-N** [comment]
@Gamemechanicwow 
I'm afraid this bug still lingers.

https://streamable.com/pj169m
https://streamable.com/d85f6k

**Comment by Gamemechanicwow** [comment]
> I'm afraid this bug still lingers.

Its live on the PTR now.

**Comment by Simp-N** [comment]
> 
> 
> > I'm afraid this bug still lingers.
> 
> Its live on the PTR now.

Oh I'm sorry. For whatever reason I thought it had already been applied. Thanks a lot
