### ISSUE TITLE
Chasing A-Me 01 (Escort quest)

### ISSUE THREAD

**Issue by ripcurl91** [the-hyjal-project/bugtracker#118]
**Describe Your Issue**
"Chasing A-Me 01" quest in Un'Goro Crater not working properly; NPC is not aggroing any mobs

**Steps To Reproduce**

1. Accept the quest and watch how the NPC just walks by the mobs
2. 
3. 

Quest: https://classic.wowhead.com/quest=4245/chasing-a-me-01
NPC: https://classic.wowhead.com/npc=9623/a-me-01

**Expected Behavior**
A-Me 01 should aggro mobs around him.

**Comment by Gamemechanicwow** [comment]
fixed here https://github.com/vmangos/core/commit/0a24e43fe353853d860b5349c3677a6d9d9867db
