### ISSUE TITLE
The quest Webwood Venom (id 916) gives 355 xp when it should give either 525 or 360 xp depending on the patch

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#12]
**Describe Your Issue**
The quest Webwood Venom (id 916) gives 355 xp when it should give either 525 or 360 xp depending on the patch (source: https://web.archive.org/web/20060303061704/http://wow.allakhazam.com/db/quest.html?wquest=916). The value was most likely changed in patch 1.10, since in a 2006-05-22 archive the quest was updated on 2006-03-29 which is just a day after patch 1.10 release. Although said archive lists the xp reward as 35, there is a comment from 2006-06-01 saying "XP at level 5: 360". Classic Wowhead (https://classic.wowhead.com/quest=916/webwood-venom) and other databases also list the quest giving 360 xp, so the 35 xp was probably a bug on Allakhazam's end back then.

**Steps To Reproduce**

1.
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected Behavior**

**Comment by petage** [comment]
Copypasting an update I did regarding this issue in Discord after we found out Classic Wowhead doesn't display some quest experience rewards correctly. The original, correct value, can always be found in the source code of the quest page which is what I referred to with "according to Classic Wowhead".

_This quest should give 355 xp according to Classic Wowhead like it currently does. I don't have an explanation for the comment saying it gives 360 xp, but I believe 355 xp is the correct value here. Now the 525 xp pre patch 1.10 is something that could need further evidence which I tried to find without success. Note though, that the quest was changed at least a few times throughout vanilla removing some item rewards (check the archive I linked and change the capture date), so maybe a change to the xp reward was made too._
