### ISSUE TITLE
Razor Hill Inn doesn't sell refreshments

### ISSUE THREAD

**Issue by Azizxo** [the-hyjal-project/bugtracker#122]
**Describe Your Issue**
Inkeeper Grosk in Razor Hill doesn't have trade dialogue and can't sell me refreshments https://i.imgur.com/a1JC2py.png

**Steps To Reproduce**

1. Make orc
2. Go to razorhill
3. Talk to Innkeeper Grosk

NPC: https://classicdb.ch/?npc=6928

**Expected Behavior**
He should sell low level refreshments

**Comment by Nolin7777** [comment]
Can't find the issue atm

**Comment by Gamemechanicwow** [comment]
fix submitted
