### ISSUE TITLE
Copper vein not there despite being on minimap

### ISSUE THREAD

**Issue by ronaldofenomeno** [the-hyjal-project/bugtracker#123]
**Describe Your Issue**
in Dun Morogh just off the road to the south near a hill a copper vein appears on minimap as bright yellow so that means its outdoors but its not there i counldnt find it.

**Steps To Reproduce**
![image](https://user-images.githubusercontent.com/33092150/102230575-1b907780-3efe-11eb-92c9-feb8cdfee4c3.png)

Item: https://classic.wowhead.com/item=
Quest: https://classic.wowhead.com/quest=
Spell: https://classic.wowhead.com/spell=

**Expected Behavior**
the copper vein should be visible where its indicated on the minimap

**Comment by kodolol** [comment]
It's probably under the map?

**Comment by ronaldofenomeno** [comment]
i tried moving my cursor around the place but no tooltip shows

**Comment by Nolin7777** [comment]
This node is in a cave.
