### ISSUE TITLE
copper vein in loch modan is unreachable

### ISSUE THREAD

**Issue by ronaldofenomeno** [the-hyjal-project/bugtracker#125]
**Describe Your Issue**
there is no way to get to this copper vein i tried to climb the rocky hill from every direction but i couldnt get to it

**Steps To Reproduce**
![image](https://user-images.githubusercontent.com/33092150/102278338-b149f800-3f3a-11eb-8871-13808cd5273f.png)

Item: https://classic.wowhead.com/item=
Quest: https://classic.wowhead.com/quest=
Spell: https://classic.wowhead.com/spell=

**Expected Behavior**

**Comment by GM-Dave-THP** [comment]
This is accessible further round the hill to the right, requires simple walking and jumping.
