### ISSUE TITLE
Ol'Sooty is stationary and doesnt patrol

### ISSUE THREAD

**Issue by ronaldofenomeno** [the-hyjal-project/bugtracker#126]
**Describe Your Issue**
the lvl 20 elite bear ol'sooty is stationary near a tree and doesnt move at all.

**Steps To Reproduce**
![image](https://user-images.githubusercontent.com/33092150/102283039-a8f5bb00-3f42-11eb-8388-dda78773f110.png)

Item: https://classic.wowhead.com/item=
Quest: https://classic.wowhead.com/quest=
Spell: https://classic.wowhead.com/spell=

**Expected Behavior**
it should patrol along the coast

**Comment by GM-Dave-THP** [comment]
https://classic.wowhead.com/npc=1225/ol-sooty

**Comment by NickTyrer** [comment]
Fixed here https://github.com/vmangos/core/pull/972
