### ISSUE TITLE
Stuck NPC in Darkshore

### ISSUE THREAD

**Issue by Troffel123** [the-hyjal-project/bugtracker#128]
**Describe Your Issue**
Thistle Bear in Darkshore  44,28 is stuck in a tree. 

**Steps To Reproduce**

No steps needed just go there.

NPC: https://classic.wowhead.com/npc=2163/thistle-bea

**Expected Behavior**
Shouldn't be stuck in the tree.

**Comment by GM-Dave-THP** [comment]
![image](https://user-images.githubusercontent.com/19539976/102654704-eb98dc80-4168-11eb-9383-1b3a8c844539.png)
