### ISSUE TITLE
Invisible mobs in coldridge

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#13]
**Describe Your Issue**
uys
there's invisible mobs
that only appear when aggro'ed
in Coldridge valley
lemme record it real quick

**Steps To Reproduce**

https://cdn.discordapp.com/attachments/780923795782369360/782115286076620820/2020-11-27_21-25-58.mp4

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected Behavior**

**Comment by Gamemechanicwow** [comment]
I think we got this downed as a client/setup problem.

- Other players ran thru the tunnel and didn't encounter invisible mobs.
- This is reported from the same player that had terrain clips which where caused by amd gpu tesselation.

**Comment by Nolin7777** [comment]
> I think we got this downed as a client/setup problem.
> 
> * Other players ran thru the tunnel and didn't encounter invisible mobs.
> * This is reported from the same player that had terrain clips which where caused by amd gpu tesselation.

This
