### ISSUE TITLE
Three Odd Quests in Duskwood

### ISSUE THREAD

**Issue by Simp-N** [the-hyjal-project/bugtracker#130]
**Describe Your Issue**
I noticed three quests in Duskwood that I've never seen before. I tried looking them up on Wowhead and found almost nothing on any of them (though two kind of appears on ClassicDB).

**Steps To Reproduce**
The three quests are:
1. *Awaiting Word* (236), I'm sorry I forgot who gave me, but I believe it may have been Watcher Dodds (888). The quest has no objective and is simply turned in at Watcher Callahan (2142). There's a quest listed on ClassicDB with the same ID, and same objective, but the name's different: Watcher Callahan.

2. *Four-Legged Menaces* (171). This is a follow-up of Awaiting Word. The objective is to kill 12 Rabid Dire Wolf. The objective is similiar to the quest Wolves At Our Heels (226), which has you kill 8 Rabid Dire Wolf, and 12 Starving Dire Wolf. Also, this quest should not be confused with another quest called *Eight*-Legged Menaces. Splauks on the discord also noticed that ClassicDB has a quest called Four-Legged Menaces, as part of the Children's Week event. On Wowhead there's a quest with the same ID (171), called A Warden to the Alliance.

3. *Ambushed in the Forest* (172). This quest is picked up from Ambassador Berrybuck (271) in Darkshire's Town Hall. The objective is to get *Ambassador's Satchel* which is looted from a chest called *Ambassador's Locker* at 65,66. While the quest isn't listed on Wowhead, the item and the chest are, but there's no information about them.

[Watcher Dodds](https://classic.wowhead.com/npc=888/watcher-dodds)
[Watcher Callahan (NPC)](https://classic.wowhead.com/npc=2142/watcher-callahan)
[Watcher Callahan (quest)](https://classicdb.ch/?quest=236)

[Four-Legged Menaces](https://classicdb.ch/?quest=171)
[Wolves At Our Heels](https://classic.wowhead.com/quest=226/wolves-at-our-heels)
[Eight-Legged Menaces](https://classic.wowhead.com/quest=245/eight-legged-menaces)
[A Warden to the Alliance](https://classic.wowhead.com/quest=171/a-warden-of-the-alliance)

[Ambassador Berrybuck](https://classicdb.ch/?npc=271)
[Ambassador's Satchel](https://classicdb.ch/?item=1923)
[Ambassador's Locker](https://classicdb.ch/?object=41)

**Expected Behavior**
I can't remember seeing any of these on the pservers I've played on, nor on Classic. 

Gamemechanic wrote this on the discord: "Awaiting Word, Four Legged Menace and Ambushed In The Forest are all quests from wow beta between 0.6 and 0.8. They shouldn't be available.
The mix up with childrens week quests, is probably because the quest id was reused in 1.4."

**Comment by Gamemechanicwow** [comment]
The 3 quests where available during beta, but never made it to release. The quests also lacks either questcompletion text or have the wrong text .

https://github.com/vmangos/core/pull/911

**Comment by Nolin7777** [comment]
Credits vmangos
