### ISSUE TITLE
Quests "Nessa Shadowsong" and "Honor Students" are available for humans

### ISSUE THREAD

**Issue by ripcurl91** [the-hyjal-project/bugtracker#131]
**Describe Your Issue**
The race specific quests "Nessa Shadowsong" and "Honor Students" including their follow-ups are available for humans but they should be locked to night elves and dwarves / gnomes respectively.

**Steps To Reproduce**

1.
2. 
3. 

Quests: https://classic.wowhead.com/quest=6387/honor-students, https://classic.wowhead.com/quest=6344/nessa-shadowsong 

**Expected Behavior**
Nessa Shadowsong should be available for night elves only. Honor Students should be available for dwarves only.

**Comment by NickTyrer** [comment]
`UPDATE `quest_template` SET `Required_Races` = 8 WHERE `entry` = 6344;
UPDATE `quest_template` SET `Required_Races` = 68 WHERE `entry` = 6387;`

**Comment by Simp-N** [comment]
Good catch. The other races also have similiar quests, that I suppose are meant to teach the player about flight points, and it might be worth checking them too. I looked in the database and the human quest might also be available for other races, and it shouldn't.

Orc & Troll: [Meats to Orgrimmar](https://classic.wowhead.com/quest=6365/meats-to-orgrimmar)
Tauren: [A Bundle of Hides](https://classic.wowhead.com/quest=6361/a-bundle-of-hides)
Undead: [Supplying the Sepulcher](https://classic.wowhead.com/quest=6321/supplying-the-sepulcher)
Dwarves & Gnomes: [Honor Students](https://classic.wowhead.com/quest=6387/honor-students)
Humans: [A Swift Message](https://classic.wowhead.com/quest=6181/a-swift-message)
Night Elves: [Nessa Shadowsong](https://classic.wowhead.com/quest=6344/nessa-shadowsong)

**Comment by ripcurl91** [comment]
I've tested horde side as Undead and you couldn't accept any of the flight point quests that are meant for Orcs, Trolls and Taurens.

**Comment by Nolin7777** [comment]
credit vmangos
