### ISSUE TITLE
Tauren druid mana/health and mana/health growth incorrect

### ISSUE THREAD

**Issue by PinPulse** [the-hyjal-project/bugtracker#132]
**Describe Your Issue**
https://gyazo.com/e6d2805d93268f7cd03299946c433361
The mana at level 1 should be 67 then at level 2 be 75.
Atm the mana begins at 34 and then at level 2 u gain 41 mana points.
https://gyazo.com/98dabf17a70de25aac9ae4bc7f99bfc2

additional info: this is how it was on classic and other pservers

**Comment by Nolin7777** [comment]
I don't understand the issue if it's currently the same behavior as it is on classic?
