### ISSUE TITLE
Weapon with 0 durability shows as equipped when attacking

### ISSUE THREAD

**Issue by pmmcsweeney** [the-hyjal-project/bugtracker#133]
I have a dagger equipped with 0 durability that shows up on my character model when attacking. Attack sound is a dagger and not unarmed. 

Damage is the same as unarmed and my unarmed skill is leveling though so I don't think it is actually attacking with the dagger.

**Comment by GM-Dave-THP** [comment]
Please can you delete your WDB folder and check the item again, if this still exists can you please provide a screenshot.

**Comment by pmmcsweeney** [comment]
That seems to have resolved the issue
