### ISSUE TITLE
High Justice Grimstone chat bubbles

### ISSUE THREAD

**Issue by monkfish** [the-hyjal-project/bugtracker#135]
**Describe Your Issue**

The npc high justice grimstone sometimes doesnt have chat bubbles when he says his speech
We did arena event 2 times, first one we didnt see any chat bubbles, and second one we saw them

**Steps To Reproduce**

1. Go inside black rock depths arena and start the event
2. Wait for him to spawn and pay attention
3. You can see his speech on the chat box but you wont see his chat bubbles all the times

NPC : https://classic.wowhead.com/npc=10096/high-justice-grimstone

**Expected Behavior**

He should have chat bubbles at all times

**Comment by NickTyrer** [comment]
See https://github.com/vmangos/core/issues/754

**Comment by Neto-WoW** [comment]
I've implemented some small additions to the event however it needs a bigger rework to be accurate. I will work on the overall event over time, however the original bug report is fixed.
