### ISSUE TITLE
Lyceum double torch trick

### ISSUE THREAD

**Issue by monkfish** [the-hyjal-project/bugtracker#136]
**Describe Your Issue**

Inside Black rock depths instance, inside the lyceum room. you need to get torches in order to lit 2 braziers
after that the door to magmus opens.
This trick has been used for years in private servers, never seen it fixed ( not sure how easy or if its possible to fix )
But basically, you can use 2 torches at the same time on the same brazier, and the it will count as if you litted 2 braziers. so the door will open even tho you only litted 1

"clever use of game mechanics" but i think it should be fixed 

**Steps To Reproduce**

1. Go inside the lyceum room
2. Get 2 torches ( you will need 2 players for this tho 1 torch in each player )
3. Then at the same time lit one of the braziers.
4. The door to magmus should open

Item: https://classic.wowhead.com/item=11885/shadowforge-torch

**Expected Behavior**

Only one of the torches should lit the brazier, even if two players use 2 torches at the same time, only the first one to click it should work. and the second torch shouldnt be used at all even if he clicked. same way 2 players try to loot a quest item
only the first one to click will get it. the other one would get canceled

**Comment by Gamemechanicwow** [comment]
I can't recreate this bug. Even with nearly instant activations.
![image](https://user-images.githubusercontent.com/2223066/104105964-5ba30a00-52b2-11eb-83dc-fe4801fbaab3.png)

If this bugreport is only based on previous pserver experience i would say its invalid - but if you somehow was able to trigger it on the ptr i would like to know more.

**Comment by monkfish** [comment]
it was tested on hyjal ptr. u need 2 players to use torch at the same time on the same brazier
