### ISSUE TITLE
Blood of the mountain drop

### ISSUE THREAD

**Issue by monkfish** [the-hyjal-project/bugtracker#137]
**Describe Your Issue**

We were doing BRD instance yesterday and we killed one of the bloodhounds and he dropped blood of the mountain

You can see here:
minute 01:53:20
https://www.twitch.tv/videos/843298026

**Steps To Reproduce**

1.Go inside black rock depths instance and start killing bloodhounds to see if it drops again ( or check the loot tables somehow )

Item: https://classic.wowhead.com/item=11382/blood-of-the-mountain
NPC : https://classic.wowhead.com/npc=8921/bloodhound

**Expected Behavior**

Blood of the mountain should only be dropping from molten destroyers inside Molten core or either be mined from dark iron deposits

**Comment by GM-Dave-THP** [comment]
While wowhead does indeed show that it drops from only 1 NPC, classicdb.ch shows it can drop from multiple mobs seen here:

https://classicdb.ch/?item=11382

Requires further investigation.

**Comment by Gamemechanicwow** [comment]
> While wowhead does indeed show that it drops from only 1 NPC, classicdb.ch shows it can drop from multiple mobs seen here:
> 
> https://classicdb.ch/?item=11382
> 
> Requires further investigation.

Classicdb is db.vanillagaming.org. Its not a credible source for what is accurate imo

**Comment by Nolin7777** [comment]
Drop rate is 0.02
