### ISSUE TITLE
Esqort quest bugs

### ISSUE THREAD

**Issue by Homeotyan** [the-hyjal-project/bugtracker#139]
https://classic.wowhead.com/quest=898/free-from-the-hold quest is bugged. Npc https://classic.wowhead.com/npc=3465/gilthares-firebough goes though mobs not getting aggro and then bugs in when he's starting aggroing on https://classic.wowhead.com/npc=3382/southsea-cannoneer or https://classic.wowhead.com/npc=3381/southsea-brigand 
When i charged them it showed that they're evading whats kinda weird
Attaching some screenshots
https://cdn.discordapp.com/attachments/788342339306651679/791815222594633738/unknown.png
https://cdn.discordapp.com/attachments/788342339306651679/791816659006128158/unknown.png
And there's another bugged esqort quest  https://classic.wowhead.com/quest=4121/precarious-predicament
https://classic.wowhead.com/npc=9520/grark-lorkrub#drops grark not getting aggroed by orc and dragonkin elite mobs that  arent spawned by the event and staying still in fight (what is probably not a bug tho, dont remember exactly how he should respond on getting attacjed by orc npces)

**Comment by Gamemechanicwow** [comment]
Free from the hold is fixed here:https://github.com/vmangos/core/commit/4f05939da104a1301b1f5ab995a0094c79d0e370

Precarious predicament seems to be a different bug. He shouldn't aggro mobs. But still be attackable by alliance.
![image](https://user-images.githubusercontent.com/2223066/103162642-58f4df00-47f3-11eb-9557-2231361a37a5.png)
