### ISSUE TITLE
Boss tho'grun / tremors of the earth part 1

### ISSUE THREAD

**Issue by monkfish** [the-hyjal-project/bugtracker#140]
**Describe Your Issue**

1. Theres 3 of tho'grun's guards that walk way faster than him, so theyre rarely around him. ( eventually they will reach the boss, but since they walk faster, shortly after they will be already ahead of him etc... )
2. Boss tho'grun and his guards are rarely together making the quest really easy

**Steps To Reproduce**

1. Go to npc boss tho'grun's location and just follow him for a while, you will see that 3 guards dont go with him cuz they walk way faster.
2. Kill him, then kill the other npcs, ( dont instantly kill them, wait a few seconds before each kill so you will see their respawn behavior aka they dont wait for the boss to patrol or the boss doesnt wait for the guards )

NPS: https://classic.wowhead.com/npc=2944/boss-thogrun

**Expected Behavior**

I think, if the boss is killed he should wait for the guards, or the guards shouldnt be patrolling without the boss alive. or something like this

**Comment by Neto-WoW** [comment]
Seems to be blizzlike in both Classic and original Vanilla. You can see via comments that this is the case, even if it makes more sense for them to path together.

https://classic.wowhead.com/npc=2944/boss-thogrun#comments
