### ISSUE TITLE
Quest "Escape through Force" in Darkshore bugged

### ISSUE THREAD

**Issue by ripcurl91** [the-hyjal-project/bugtracker#141]
**Describe Your Issue**
The NPC "Volcor" in Darkshore bugs out during the quest "Escape through Force" and does not reset anymore until manually done by a GM or a server restart.

**Steps To Reproduce**

1.
2. 
3. 

Quest: https://classic.wowhead.com/quest=994/escape-through-force
NPC: https://classic.wowhead.com/npc=3692/volcor
**Expected Behavior**
NPC should not bug out.

**Comment by Gamemechanicwow** [comment]
fixed here: https://github.com/vmangos/core/commit/0a24e43fe353853d860b5349c3677a6d9d9867db
