### ISSUE TITLE
Magistrate barthilas early pull

### ISSUE THREAD

**Issue by monkfish** [the-hyjal-project/bugtracker#144]
**Describe Your Issue**

You can pull magistrate barthilas when hes in front of aurius chapel in elder's square

01:00:55 Here you can see how i pull him, pretty sure you can pull him with a hunter or any ranged attacks aswell
https://www.twitch.tv/videos/850934866

**Steps To Reproduce**

1. Go into stratholme through the backdoor entrance ( you should enter in elder's square )
2. Try to pull barthilas either with a ranged spell or attack or go to him and attack him ( for some reason he wont body pull )

NPC: https://classic.wowhead.com/npc=10435/magistrate-barthilas

**Expected Behavior**

You shouldnt be able to attack him while hes in front of the chapel. if you try to attack him or get too close he should just run away to his normal spot deep inside stratholme undead side.
He also should yell some dialogs when he starts running away. i think hes the one who warns baron rivendare about intruders then you get the baron's ultimatum. i don't fully remember

**Comment by Simp-N** [comment]
I'm a little confused here. In the **Steps to reproduce**-section you mention entering through the backdoor, but in the video you enter through the main entrance. Afaik, Magistrate only flees when you enter through the backdoor. Maybe you did enter through backdoor, and he didn't flee, at some other part in the video.

Examples of him not fleeing when getting to him through the main entrance:
[Video from TBC.](https://www.youtube.com/watch?v=vtTF1T02gjs) at about 2:00
[Video from Classic](https://www.youtube.com/watch?v=YsFmsuBGQak) at about 14:00
Couldn't find a video from actual vanilla, but [here's a guide](https://www.wow-pro.com/42-56-james-stratholme-guide/) from august 2006. Go to chapters 8 & 9 where he talks about Magistrate in Elder Square, and that he flees if you enter through backdoor.

**Comment by monkfish** [comment]
yeah thats my bad, i only mentioned backdoor since its the closest entrance, not as if he will only behave like that if you enter from backdoor.

**Comment by Nolin7777** [comment]
Working as intended
