### ISSUE TITLE
Bugged NPC'S

### ISSUE THREAD

**Issue by Troffel123** [the-hyjal-project/bugtracker#145]
**Describe Your Issue**
Guards in Arathi at Refuge Point kinde stuck. Also Commander Amaren seems to be stuck in combat.
**Steps To Reproduce**
no need to, they just stuck at patrolling start point it seems

https://classic.wowhead.com/npc=10696/refuge-pointe-defender
https://classic.wowhead.com/npc=2608/commander-amaren

**Expected Behavior**
patrol around base
commander should be in front of the tent next to fp

**Comment by NickTyrer** [comment]
@Troffel123 They look correct to me, could you elaborate more?

**Comment by Troffel123** [comment]
Yes i was there yesterday and indeed they behaved correctly. I thought u alreday fixed them.
The Ptr restart prolly fixed them. Anyway thanks for looking into it. When the ptr is back up i Swing by and Check if they still work correct.
