### ISSUE TITLE
Fishing Oily Blackmouth in Wetlands

### ISSUE THREAD

**Issue by petage** [the-hyjal-project/bugtracker#148]
**Describe Your Issue**

Oily Blackmouth can be fished in Wetlands (id 11) and the subzone Menethil Bay (id 299). Just for clarification, id 11 only includes areas in Wetlands that are not part of any subzone. For example, the coast southwest of Menethil Harbor at coordinates 2.3, 77.2.

**Steps To Reproduce**

``SELECT * FROM `fishing_loot_template` WHERE `item`='6358';``

1. Execute the SQL query.
2. Check all the entries and notice that only 11 and 299 are part of Wetlands.

https://classic.wowhead.com/item=6358/oily-blackmouth

**Expected Behavior**

In addition to zone ids 11 and 299, Oily Blackmouth should be fishable from Menethil Harbor (id 150) and Baradin Bay (id 298) according to multiple [comments](https://classic.wowhead.com/item=6358/oily-blackmouth#comments) on Classic Wowhead. Sort the comments by oldest first and check the ones posted before patch 1.9.0, since that's when fishing pools were introduced to the game.

**Comment by Gamemechanicwow** [comment]
I would prefer to have the data as accurate as possible before messing with it - and there is probably a decent amount of wrong numbers in the fishing loot template.

There is an addon for classic that tracks fishs caught pr subzone. I have made various posts across the interweb trying to get users of that addon to send me their datafile.

I will return to this issue soon - hopefully with alot of data.
