### ISSUE TITLE
Paladin's Charger mount bug

### ISSUE THREAD

**Issue by Hateboer33** [the-hyjal-project/bugtracker#149]
**Describe Your Issue**
When you use the spell Summon Charger for the 100% paladin class mount, nothing happens, the charger "buff" appears but there is no ridding horse summoned. Even you can use another mount while the charger "buff" is on.

**Steps To Reproduce**
1. Using the spell Summon Charger 

Item: https://classic.wowhead.com/item=14565
Spell: https://classic.wowhead.com/spell=23214

**Expected Behavior**
The spell Summon Charger should summon the ridding horse (Charger), the paladin epic mount.

**Comment by Gamemechanicwow** [comment]
Charger is not available untill 1.4

The ptr npc scammed you :>

It should have no impact on the real game.
