### ISSUE TITLE
Mobs not agroing in durnholde keep

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#15]
**Describe Your Issue**
some mobs just standing around and not aggroing
hillsbrad foothills in durnholde keep

**Steps To Reproduce**

https://cdn.discordapp.com/attachments/780923795782369360/782287469356777512/Untitled.jpg

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected Behavior**

**Comment by ratkosrb** [comment]
Bugged LoS inside this building.
