### ISSUE TITLE
The quests Enraged Spirits and Wounded Ancients aren't available at the same time

### ISSUE THREAD

**Issue by petage** [the-hyjal-project/bugtracker#152]
**Describe Your Issue**

Wounded Ancients is only offered after completing Enraged Spirits. This issue is similar to #105.

**Steps To Reproduce**

1. Complete the prerequisite Kaela's Update.
2. Notice how Kaela Shadowspear only offers Enraged Spirits.
3. Complete Enraged Spirits and only then you'll be offered Wounded Ancients.

https://classic.wowhead.com/npc=4080/kaela-shadowspear
https://classic.wowhead.com/quest=1091/kaelas-update
https://classic.wowhead.com/quest=1083/enraged-spirits
https://classic.wowhead.com/quest=1084/wounded-ancients

**Expected Behavior**

Wounded Ancients should be offered at the same time as Enraged Spirits. After completing the prerequisite mentioned, both Enraged Spirits and Wounded Ancients should become available. See the [comment](https://classic.wowhead.com/quest=1091/kaelas-update#comments:id=51451) made by HighFive. Also notice the quests under Unlocks on the right-hand side of the page [Kaela's Update](https://classic.wowhead.com/quest=1091/kaelas-update).

**Comment by NickTyrer** [comment]
Fixed here https://github.com/vmangos/core/pull/983

**Comment by NickTyrer** [comment]
Fixed
