### ISSUE TITLE
NPC chat/yell bug

### ISSUE THREAD

**Issue by Trenwow** [the-hyjal-project/bugtracker#158]
**Describe Your Issue**
NPCs are saying weird messages in chat when they yell. Both in and outside of instances.

https://i.gyazo.com/8681e4bb580591aad08db11efa26357f.png
https://i.gyazo.com/fde899804fb86e6682d66bff62b801df.png
https://i.gyazo.com/347af1e1f9f040a9312796a0bcaf8602.png

**Comment by GM-Dave-THP** [comment]
This looks related to a client side chat setting.

**Comment by Gamemechanicwow** [comment]
Looks very similar to an addon dumping an event in their eventlistener. Oldschool debugging :>

check your addons.

**Comment by Trenwow** [comment]
Was caused by an enemy cast bar addon. Thanks for the help.
