### ISSUE TITLE
Riverpaw Gnolls in Westfall drop Mulgore Spice Bread, which is a req 25 item

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#16]
**Describe Your Issue**
Riverpaw Gnolls in Westfall drop Mulgore Spice Bread, which is a req 25 item. That seems odd, and according to Wowhead they shouldn't drop it. Out of ten kills I got three breads.

**Steps To Reproduce**

1.
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected Behavior**

**Comment by ratkosrb** [comment]
Fixed in https://github.com/vmangos/core/commit/c1db8e8f625ba5dbba3c03a11eafb4411e1557db
