### ISSUE TITLE
Improved Blizzard rank 1 not working

### ISSUE THREAD

**Issue by Gammelman** [the-hyjal-project/bugtracker#164]
**Describe Your Issue**
The talent improved blizzard 1/3 does not apply it's slow debuff when casting Blizzard on enemies.

**Steps To Reproduce**
1. Lvl 20+ mage
2. 1 talent point into Improved Blizzard
3. Cast blizzard on mobs

Spell ID: 11185

**Expected Behavior**
Should give a slow debuff when the target takes damage from the spell Blizzard

**Comment by GM-Dave-THP** [comment]
Pushed to PTR team for testing.

**Comment by GM-Dave-THP** [comment]
![image](https://user-images.githubusercontent.com/19539976/103553505-70902f80-4ea5-11eb-8a2f-7387077268e9.png)

**Comment by GM-Dave-THP** [comment]
Unable to replicate, works on all three ranks.
