### ISSUE TITLE
Citizen Wilkes [Hillsbrad Farm] have fire resistance

### ISSUE THREAD

**Issue by Gammelman** [the-hyjal-project/bugtracker#165]
**Describe Your Issue**
Citizen Wilkes, NPC Quest mob for the quest "Dangerous!" Resists fire damage

**Steps To Reproduce**
Attack NPC with fire damage.

Quest: https://classic.wowhead.com/quest=567/dangerous
NPC ID: 2449

**Expected Behavior**
Pretty sure Wilkes does not have more fire resistance than other mobs in that area.

**Comment by GM-Dave-THP** [comment]
This mod currently has 0 fire resistance.
![image](https://user-images.githubusercontent.com/19539976/103552494-ea271e00-4ea3-11eb-87c9-bb90a6b8405f.png)
