### ISSUE TITLE
Magram Stormer uses the wrong Lightning Shield

### ISSUE THREAD

**Issue by Simp-N** [the-hyjal-project/bugtracker#168]
**Describe Your Issue**
[Magram Stormer](https://classic.wowhead.com/npc=4642/magram-stormer) in Desolace uses Lightning Shield. However, the one it uses on Hyjal PTR is a lot like the Shaman class' Lightning Shield. On Classic, and back in vanilla, it uses a different kind of Lightning Shield that works a little bit different. 

As it is on Hyjal PTR now, it has a 100% chance to trigger, and then it has a cooldown before it can trigger again.
What it should be is a 50% chance to trigger, with no cooldown.

**Steps To Reproduce**
Fight a Magram Stormer. You can use some quick attacks to try and trigger it often, and you'll notice it will have a few seconds before it can trigger again. Then, you can use one attack, wait a moment, and attack again, to see that it has a 100% chance to trigger when its off cooldown.

**Expected Behavior**
There should be a 50% when struck to trigger the Lightning Shield effect, and there should be no cooldown. On wowhead, there are abilities listed like [this](https://classic.wowhead.com/spell=8788/lightning-shield), if its any helpful.

Here's a screenshot from WoW Classic, showing the tooltip, which mentions 50% chance. I've also tried attacking these mobs quickly in Classic, and it can trigger often, appearing to have no cooldown. I also tried waiting a long time after triggering before attacking again, and it was not a 100% chance to trigger. 
![Fixed_WoWScrnShot_210104_161147](https://user-images.githubusercontent.com/75734743/103574980-33419700-4ed1-11eb-98fa-8fd06951e6f4.jpg)

I've also watched [Joana's videos from vanilla](https://youtu.be/OlnnPZbg3T0?t=5116), and at 1:25:16 you can see him fight a Magram Stormer. Notice that his pet does not trigger the effect immediately when attacking (shown by "yellow" 83 damage), indicating not a 100% chance to trigger, and that both the player and the pet appear to trigger the effect right after each other, indicating no cooldown.

**There's More**
I noticed this difference when I was actually looking into another problem, that these Magram Stormers will try and cast Lightning Cloud, but then abort it to re-apply Lightning Shield if its depleted while they're casting. I'll make a another ticket for that issue later, as it may be a more general issue affecting several types of mobs and I want to do some more research.

**Comment by Nolin7777** [comment]
Would be cool if you can find me the correct Spell ID for Lightning Shield.

**Comment by Simp-N** [comment]
> 
> 
> Would be cool if you can find me the correct Spell ID for Lightning Shield.

I downloaded an addon called TipTacClassic, that I was told could show spell IDs, and according to it the spell ID is 8788. Screenshot:
![Fixed_WoWScrnShot_210106_175539](https://user-images.githubusercontent.com/75734743/103797333-a3bef400-5048-11eb-978d-aa4f025ac9bb.jpg)

**Comment by Nolin7777** [comment]
Awesome thanks, good ticket
