### ISSUE TITLE
Stuns and Incapacitates appear to share diminishing returns.

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#17]
**Describe Your Issue**
Stuns and Incapacitates appear to share diminishing returns. I've tried this with Rough Copper Bombs and Hammer of Justice.

**Steps To Reproduce**

1.
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected Behavior**

**Comment by Gamemechanicwow** [comment]
Rough Copper Bomb is a stun even if the tooltip is very missleading.

They should share DR.
