### ISSUE TITLE
Paladin's Charger not working

### ISSUE THREAD

**Issue by HunLepto** [the-hyjal-project/bugtracker#170]
**Describe Your Issue**

If I try to use "Summon Charger" spell, it doesn't summon anything, still gives me the buff, but doesn't give anything basically. If I also click it off when I'm on a normal Warhorse, the Warhorse gets dismounted.
**Steps To Reproduce**

1. Just try to use "Summon Charger" for paladin.
2. 
3. 

Item: https://classic.wowhead.com/item=
Quest: https://classic.wowhead.com/quest=
Spell: https://classic.wowhead.com/spell=

**Expected Behavior**

Should summon my mount.

**Comment by Nolin7777** [comment]
This might be related to the PTR NPCs which gives you the spell without checking any conditions for it.
Will check again in live server.

**Comment by Gamemechanicwow** [comment]
Charger is 1.4
