### ISSUE TITLE
Preparation not working

### ISSUE THREAD

**Issue by harris987** [the-hyjal-project/bugtracker#178]
**Describe Your Issue**
Preparation rogue talent does not reset cooldowns of cold blood or blind. 

**Steps To Reproduce**

1. Use blind/cold blood, ensure ability is on cooldown
2. use preparation
3. blind and cold blood are still on cooldown

preparation: https://classic.wowhead.com/spell=14185/preparation
blind: https://classic.wowhead.com/spell=2094/blind
cold blood: https://classic.wowhead.com/spell=14177/cold-blood

**Expected Behavior**
Preparation should reset the cooldown on these abilities

**Comment by Nolin7777** [comment]
IDs? Links? Source?

**Comment by harris987** [comment]
added link to spell. 
expected behaviour now properly filled in
