### ISSUE TITLE
I can't give names to my characters that begin and end with X.

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#18]
**Describe Your Issue**
I can't give names to my characters that begin and end with X. I know this restriction exists in retail, but I was surprised to see it here. Is it hardcoded? Why is it there? Wanted to name me guy Xarfax.

**Steps To Reproduce**

1.
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected Behavior**

**Comment by Nolin7777** [comment]
Unchangeable client restriction.
