### ISSUE TITLE
No Spirit Healer in silithus

### ISSUE THREAD

**Issue by vphas** [the-hyjal-project/bugtracker#183]
**Describe Your Issue**
There is no spirit healer/ person to get res sickness in silithus at the camp. Theres one at the bottom by AQ but not one at the camp

**Comment by vphas** [comment]
cenarion hold

**Comment by Gamemechanicwow** [comment]
World of Warcraft Client Patch 1.8.0 (2005-10-11)
 - A neutral graveyard has been added to Silithus at Cenarion Hold. With 
   the addition of this graveyard, characters dying in Silithus will be 
   sent to whichever graveyard they are closer to when they die: Valor's 
   Rest or Cenarion Hold.
   
   But that being said. I think its a bug if the spirit healer at AQ is active in 1.2
