### ISSUE TITLE
No fishing schools / patches in Azshara

### ISSUE THREAD

**Issue by 123iqpl123** [the-hyjal-project/bugtracker#184]
**Describe Your Issue**
I've checked 3 times now and I've yet to see a fishing school, floating wreckage or a patch of elemental water spawn in Azshara. Not sure if a 1.2 related Issue.

https://classic.wowhead.com/object=180753/patch-of-elemental-water
https://classic.wowhead.com/object=180712/stonescale-eel-swarm
https://classic.wowhead.com/object=180685/floating-wreckage

**Expected Behavior**
Things I linked above should spawn in their spawn locations, but they don't.

**Comment by 123iqpl123** [comment]
This seems to be the case for Feralas & STV as well.

**Comment by Gamemechanicwow** [comment]
Patch 1.9.0 (2006-01-03): Schools of fish have appeared around the world that can be fished from a few times before being fished out.
