### ISSUE TITLE
Mining nodes stacking & spawning lots

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#19]
**Describe Your Issue**
I brought this u pbefore, but it bears repeating. Tons of mining nodes spawning next to each other.

**Steps To Reproduce**

https://cdn.discordapp.com/attachments/780923795782369360/782374685907746877/Jangolode_Mine_Hyjal_PTR_2020-11-28.png

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected Behavior**

**Comment by Nolin7777** [comment]
Need areas and coordinates

**Comment by GM-Dave-THP** [comment]
Jangolode mine

.go xyz -9989.13 1458.511 42.40

![image](https://user-images.githubusercontent.com/19539976/103831661-712af080-5074-11eb-93bf-521b713dd9d2.png)

**Comment by Nolin7777** [comment]
Dev-Note: Check Gobject-Pooling
