### ISSUE TITLE
Some/All Hunter Pets dont start with the correct ability.

### ISSUE THREAD

**Issue by PeachTeaDream** [the-hyjal-project/bugtracker#196]
**Describe Your Issue**

As a lvl 10 Hunter i tamed a lvl 10 Mountain Boar in Loch Modan and the boar did not come with the Charge 1 ability like it's supposed to. I tamed a lvl 11 mountain boar in Loch Modan later on just to be sure and again no ability comes with the pet after taming. I don't know if its with all pets yet, must test further.

Item: https://classic.wowhead.com/npc=1190/mountain-boar
Quest: https://classic.wowhead.com/quest=
Spell: https://classic.wowhead.com/spell=

**Expected Behavior**

After channeling and completing the tame ability on a pet, they should come with the expected ability on their action bar immediately. Ex: Boar with charge. Turtle with Shell Shield. Scorpion with poison.

**Comment by Nolin7777** [comment]
Source please

**Comment by shagu** [comment]
The boar you mentioned will have "Charge" from Patch 1.9 and later. 
Here's a list of all hunter pets, their abilities and the patch on which they will learn it: http://shagu.org/hunter/#4

**Comment by shagu** [comment]
Here's some additional notes on "Charge":
The [Patch 1.9 Changelog](https://wowwiki.fandom.com/wiki/Patch_1.9.0#Pet_Changes) says:
> Boars can now learn Charge, an ability that allows them to charge to an enemy, immobilize that enemy for 1 second, and add a large amount of Attack Power to the boar's next attack.
