### ISSUE TITLE
Kolkar wrangler, dont run away from you after using net.

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#2]
**Describe Your Issue**
Kolkar wrangler, dont run away from you after using net, normally they net you then run a bit further then keep shooting arrows at you

**Steps To Reproduce**

None

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected Behavior**
See above

**Comment by ratkosrb** [comment]
Fixed in https://github.com/vmangos/core/commit/c1db8e8f625ba5dbba3c03a11eafb4411e1557db
