### ISSUE TITLE
[Quest] "Crown of the Earth" the vial is destroyed if you try to use it while your inventory is full

### ISSUE THREAD

**Issue by joranis** [the-hyjal-project/bugtracker#200]
**Describe Your Issue**
When using the vial at the moonwell in the quest "Crown of the Earth", if your inventory is full while you use the vial then the vial is destroyed and you have to run back, abandon, and reaccept the quest to get a new vial. If your inventory is full the vial shouldn't be destroyed, but should give you a "full inventory" error so you can make room for the filled vial quest item. 

I am assuming this will happen with any interactable quest item that then creates a new quest item for quest completion if your inventory is full.

**Steps To Reproduce**
1. Accept the quest "Crown of the Earth".
2. Run to the moonwell, and make sure your inventory is full.
3. Use the vial while inside the moonwell, and observe the vial being destroyed after use.

Item: https://classic.wowhead.com/item=5185/crystal-phial https://classic.wowhead.com/item=5184/filled-crystal-phial
Quest: https://classic.wowhead.com/quest=921/crown-of-the-earth

**Expected Behavior**
The vial shouldn't be destroyed if your inventory is full, but rather a full inventory error is displayed so the player can make room for the new quest item. This goes for any quest where this interaction(Use quest item -> new quest item created) is present.

**Comment by hyjal-tester** [comment]
Just made this clip https://streamable.com/734mig this is a later part of the crown of earth chain but still functionally the same as the original poster. With a full inventory the vial is deleted and the vial of blessed water is not created in the inventory.
