### ISSUE TITLE
Flavour dialogue Demalier/Malagan not working

### ISSUE THREAD

**Issue by alassdaire** [the-hyjal-project/bugtracker#201]
**Describe Your Issue**
Characters eligible for the quest The First and the Last should occasionally trigger a dialogue between the NPCs Justine Demalier and Merlis Malagan. This does not presently occur. 

**Steps To Reproduce**

1. Create a character eligible for The First and the Last (Alliance, level 56+)
2. Stand in front of Justine Demalier and Merlis Malagan in Stormwind.
3. If you stand around for long enough, you will see that no dialogue is triggered.

Quest: https://classic.wowhead.com/quest=6182/the-first-and-the-last
NPC: https://classic.wowhead.com/npc=12481/justine-demalier
NPC: https://classic.wowhead.com/npc=12480/melris-malagan

**Expected Behavior**

The following dialogue should be occasionally triggered:

Justine Demalier: That one, Malagan. I know [him/her]. Dependable, brave, trustworthy. [Player name] is his name.

Melris Malagan: [Player name], eh? Oy! Citizen [Player name], come 'ere. Highlord Bolvar Fordragon has requested that all able bodied heroes o' the Alliance meet with him at Stormwind Keep. You just been recruited, mate! Get a move on!

**Comment by NickTyrer** [comment]
closed here https://github.com/vmangos/core/pull/1094
