### ISSUE TITLE
Small Ammo Pouch / Character models

### ISSUE THREAD

**Issue by Brodda** [the-hyjal-project/bugtracker#203]
**Describe Your Issue**
Tauren/Dwarf hunter character model and Small Ammo Pouch not showing.
https://user-images.githubusercontent.com/28935343/104084536-8b212a80-5250-11eb-826a-cdf82bc1385e.mp4

**Steps To Reproduce**
1. Create a new tauren/dwarf hunter and login

https://classic.wowhead.com/item=2102/small-ammo-pouch

**Expected Behavior**
Character models and Small Ammo Pouch should show up

**Comment by Gamemechanicwow** [comment]
It loads fine for me.

Can you try deleting or emptying your wdb folder?

**Comment by Nolin7777** [comment]
I told you already to not use modded clients
