### ISSUE TITLE
Galgar's Cactus Apple Surprise - Collecting Animation

### ISSUE THREAD

**Issue by TronusGames** [the-hyjal-project/bugtracker#204]
**Describe Your Issue**
When you collect the cactus apples from the plants the character does not do any animation.

**Steps To Reproduce**
Get the quest in the Valley of Trials in Durotar and go to find and collect any cactus apples near.

Quest: https://classic.wowhead.com/quest=4402/galgars-cactus-apple-surprise

**Expected Behavior**
On collecting apples the character should do an animation like when trying to cast a mount or something that seems he is collecting things.

**Comment by Gamemechanicwow** [comment]
https://www.youtube.com/watch?v=Xr5oyZPCWs8

Orcs are smart. They don't stick their hands into a cactus :>
aka its correct that no interaction animation is played.
