### ISSUE TITLE
Diamond Flask TBC mechanics

### ISSUE THREAD

**Issue by Pirupuku** [the-hyjal-project/bugtracker#206]
**Describe Your Issue**
Diamond Flask doesn't stack with +healing gear. You only get 9hp5 for 1min.

**Steps To Reproduce**

1. Equip Diamond Flask
2. Use it
3. Look at incoming heal

Item: https://classic.wowhead.com/item=201301

https://us.forums.blizzard.com/en/wow/t/diamond-flasks-hp5-snapshots/442337/197
https://wowwiki.fandom.com/wiki/Hotfixes/2007_Archive
-> March 2007
Wednesday, March 21st
See Official Forums (Blizzard Archive) | Unknown date & time by Unknown author.
Nightbane's melee damage has been reduced.
Hydross the Unstable no longer deals a crushing blow.
The Romulo and Julianne encounter has been retuned to be less difficult.
Gruul's health has been lowered, and the damage from his shatter ability has been reduced.
Gruul should now correctly use his hurtful strike ability.
The Magtheridon encounter has been rebalanced to be somewhat easier and should now better keep to proper raid progression.
Healing bonuses no longer apply to the Diamond Flask.

**Expected Behavior**

Diamond Flask did scale with +healing gear and snapshotted. So, when I equipped my +healing gear it scaled 1:1. E. g. Diamond Flask ticks with 9 hp5, I equip a 1h Mace with +11 healing -> Diamond Flask ticks with 20 hp5. Than, while the healing effect is still up, I unequip the 1h Mace for another weapon, that weapon doesn't has any +healing, but the effect persists. Obviously I can't unequip the Diamond Flask because than the effect disappears as well.

**Comment by Pirupuku** [comment]
Obviously couldn't check because it's not on the PTR yet, but it's the usual behavior of Diamond Flask on pservs.

**Comment by Gamemechanicwow** [comment]
> Obviously couldn't check because it's not on the PTR yet, but it's the usual behavior of Diamond Flask on pservs.

The healing already scales. And as far as i can tell its not a recent change in the DB - so it might have worked on some previous pservers without people knowing it :>
