### ISSUE TITLE
Rank display in Local Defense/World Defense channels & speech permissions in World Defense channel

### ISSUE THREAD

**Issue by alassdaire** [the-hyjal-project/bugtracker#208]
**Describe Your Issue**
When the honour system was introduced in patch 1.6, the following features were included:

- Players rank 11 or higher can now chat in the WorldDefense channel.
- The WorldDefense and LocalDefense channels will now display your rank as well as your name when chatting.

This has thus far never been implemented appropriately on private servers to my knowledge, and I would appreciate if someone could attempt to try and fix it.

See patch notes here:
https://web.archive.org/web/20060107003556/http://www.worldofwarcraft.com:80/patchnotes/patch-05-08-02.html

**Expected Behavior**

PVP rank should be displayed before character name when speaking in the Local Defense or World Defense channels.
Players rank 11 or higher should be able to speak in the World Defense channel.

**Comment by Nolin7777** [comment]
Interesting, never heard this before

**Comment by alassdaire** [comment]
> Interesting, never heard this before

Veteran Vanilla PvPers should remember it. I decided I'd look around for screenshots on the internet that demonstrate the intended behaviour, and I was lucky enough to find one. See the following picture, and note the presence of 'Grunt Zibber'.

![rd3](https://user-images.githubusercontent.com/77180009/104352386-9c7a6900-54d4-11eb-98cd-ba6f192a9d52.jpg)

**Comment by Gamemechanicwow** [comment]
![image](https://user-images.githubusercontent.com/2223066/107566876-ad0e2400-6be5-11eb-8dad-ca16c7074bc6.png)

Ranks are showing in defense channels.
Rank requirement for world defense channel is active.
