### ISSUE TITLE
The drop rate of Mossy Tumor (id 5170) seems to be way too high.

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#21]
**Describe Your Issue**
The drop rate of Mossy Tumor (id 5170) seems to be way too high. I killed 11 mobs and 10 of them dropped it. According to https://web.archive.org/web/20050331170852/http://wow.allakhazam.com/db/item.html?witem=5170 the drop rate is roughly 19-31% depending on the mob, whereas https://classic.wowhead.com/item=5170/mossy-tumor lists the drop rate as 44-54%.

**Steps To Reproduce**

1.
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected Behavior**

**Comment by petage** [comment]
Adding a Thottbot archive for some more reference, even though it's from early TBC: https://web.archive.org/web/20070312044715/http://www.thottbot.com/i5170.
