### ISSUE TITLE
Nova

### ISSUE THREAD

**Issue by Kattfot** [the-hyjal-project/bugtracker#212]
Using Polymorph on a mob that is in Frost Nova will leave the nova on the ground forever.
https://i.gyazo.com/37e972f01ac5c44c4cfda1ac7383b65f.jpg

**Comment by Gamemechanicwow** [comment]
I can't reproduce it.

Check if your graphics driver is uptodate. There was a widespread similar issue a few years back caused by a driver. I think it was ATI.
