### ISSUE TITLE
Vavles from Samophlange quest should spawn guards

### ISSUE THREAD

**Issue by Simp-N** [the-hyjal-project/bugtracker#214]
**Describe Your Issue**
When doing the quest [Samophlange](https://classic.wowhead.com/quest=900/samophlange) you have to open three valves. Two of these valves should spawn guards when opened, however on Hyjal PTR no guards appear to spawn.

**Steps To Reproduce**
1. Grab the first quest [Samophlange](https://classic.wowhead.com/quest=894/samophlange) from [Sputtervalve](https://classic.wowhead.com/npc=3442/sputtervalve) in Ratchet. Go to about 53,12 and turn it in to get the follow-up, which is the quest with the valves.
2. Turn the three valves, which are located around the machine you get the quest by.
3. Observe if any guards spawn (might wanna kill the mobs nearby first to make it more clear)

**Expected Behavior**
There three valves are named Fuel Control Valve, Regulator Valve and Main Control Valve. 
Turning the Regulator Valve should spawn 1 guard.
Turning the Main Control Valve should spawn 2 guards.

Referencing [Joana's vanilla guide](https://www.youtube.com/watch?v=NrSdjsrhX0s), at 1:06:40 you will see him turn the Regulator Valve, and 1 guard (Venture Co Peon). At 1:06:05 he turns the Main Control Valve, and the guards do spawn, but aren't aggroing him as he steps away from the valve, however you can see the two guards (Drudger, Peon) at the valve a few seconds later, 1:06:40, when he's turning the next one.

[Here's a recording](https://streamable.com/ufejph) from Classic. One Drudger from Regulator Valve, two Drudgers from from Main Control Valve. I'm guessing the type of mob spawned is random of the two.

[Venture Co Drudger](https://classic.wowhead.com/npc=3284/venture-co-drudger)
[Venture Co Peon](https://classic.wowhead.com/npc=3285/venture-co-peon)

**There's more**
I don't know if this matters, but after I completed the quest, I could still turn, or use, the valves.

**Comment by Neto-WoW** [comment]
Fixed.
