### ISSUE TITLE
Combat mechanics regarding GCD and swing reset

### ISSUE THREAD

**Issue by fitqt** [the-hyjal-project/bugtracker#218]
**Describe Your Issue**
Weapon swap triggers swing reset and GCD while being in combat.

**Steps To Reproduce**

Swing reset:
1. Swap weapons in combat while hitting a target:
1.1 Using a macro
1.2 Rightclicking it from bags
1.3 Drag n drop it from bags or switch MH/OH if DW and both are one handed weapons
2. Notice swing reset

GCD:
1. Do the above steps while having abilities on bars
2. Notice GCD timer of 1 or 1.5 sec depending on class

Item: All weapons
Spell: Any spell

**Expected Behavior**

Weapons swaps in combat prior to 1.7 should not trigger GCD or swing reset.

Patch 1.7.0 [https://wow.gamepedia.com/Patch_1.7.0](https://wow.gamepedia.com/Patch_1.7.0) states:

`Switching weapons in combat triggers a 1 second global cooldown for all abilities for rogues and a 1.5 second global cooldown for everyone else.`

`When you swap weapons in combat, you start your swing again, instead of continuing your last swing.`

While second note clearly shows how it worked before patch 1.7.0, same could not be said about first one because not triggering any GCD before that point does not necessarily follow from that note. I would like a comment from devs of whether this type of thing would even be considered for implementation before I try to find proof of first note.

**Comment by ratkosrb** [comment]
Mechanics like that are tied to client progression.
https://github.com/vmangos/core/blob/development/src/game/Objects/Player.cpp#L10539

**Comment by Nolin7777** [comment]
Thanks for the good ticket, but as @ratkosrb already said, those mechanics are tied to client progression and won't be changed.
Sorry.
