### ISSUE TITLE
Tome of Divinity questline bug

### ISSUE THREAD

**Issue by HunLepto** [the-hyjal-project/bugtracker#219]
**Describe Your Issue**

I could take the The Tome of Divinity quest after already having Tome of Divinity in my quest log.

**Steps To Reproduce**

1. Go take the first quest from Duthorian Rall and then try to pick up the quest from Brother Wilhelm after it was done.
2. 
3. 

Quest: https://classic.wowhead.com/quest=1641
Quest 2: https://classic.wowhead.com/quest=2998
NPC: https://classic.wowhead.com/npc=6171
NPC 2: https://classic.wowhead.com/npc=927

**Expected Behavior**

After taking the quest from Duthorian Rall, it should be impossible to take it from Brother Wilhelm after the first quest was completed.
![WoW 2021-01-10 17-11-28-900](https://user-images.githubusercontent.com/77020176/104128481-14775080-5368-11eb-96e8-d77109a49a45.jpg)
![WoW 2021-01-10 17-11-30-140](https://user-images.githubusercontent.com/77020176/104128489-1ccf8b80-5368-11eb-9676-9f985c4d9070.jpg)

**Comment by NickTyrer** [comment]
Fixed here https://github.com/vmangos/core/pull/991

**Comment by Gamemechanicwow** [comment]
Thanks @NickTyrer
