### ISSUE TITLE
The quest Crown of the Earth (id 934) currently gives 775 xp and 250 Darnassus rep.

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#22]
**Describe Your Issue**
The quest Crown of the Earth (id 934) currently gives 775 xp and 250 Darnassus rep. According to a comment from 2005-01-27 (https://web.archive.org/web/20050425164738/http://wow.allakhazam.com/db/quest.html?wquest=934) it should give 650 xp. The rep value should most likely be 75 since a comment from early TBC, on 2007-06-15 (https://web.archive.org/web/20070717202727/http://www.wowhead.com/?quest=934), says the quest gives 150 Darnassus rep and supposedly reputation gains were increased in patch 2.0.1. Classic Wowhead also suggests the quest giving 75 rep.

**Steps To Reproduce**

1.
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected Behavior**

**Comment by petage** [comment]
Adding a link to the [quest](https://classic.wowhead.com/quest=934/crown-of-the-earth) in question.

**Comment by ratkosrb** [comment]
Fixed in https://github.com/vmangos/core/commit/c1db8e8f625ba5dbba3c03a11eafb4411e1557db
