### ISSUE TITLE
Chain aggro

### ISSUE THREAD

**Issue by jamesaso** [the-hyjal-project/bugtracker#220]
**Describe Your Issue**
Humanoid mobs dont seem to aggro of eachother

**Steps To Reproduce**
1 .aggro mob
2. run away and make its path cross with a unaggroed mob

Seems to be an issue with multible mob types. Was the same in RFC

Example video: https://streamable.com/dqfcff

**Comment by Nolin7777** [comment]
That's weird. I tried it on the same mobs and same location, for me it worked..
