### ISSUE TITLE
Crown of the Earth - Jade Vial disappears after filling

### ISSUE THREAD

**Issue by Disorientx** [the-hyjal-project/bugtracker#221]
**Describe Your Issue**

While doing the second step of the Crown of the Earth Quest whereby you are required to fill the Jade Vial at the Moonwell in Starbreeze Village. After clicking the vial to fill it; it then disappeared from my inventory

**Steps To Reproduce**

1. Accepted the 4th step of "Crown of the Earth" from Corithras Moonrage in Dolonaar after taking level 6 skills from the Druid Trainer. 
2. Accepted and completed both "Timbering Seeds" and "Timberling Sprouts"
3. Moved up to Starbreeze Village Moonwell
4. Clicked the Vial - Whilst having a full inventory 
5. Vial disappeared and quest uncompleted

Item: https://classic.wowhead.com/item=5619 or 5639
Quest: https://classic.wowhead.com/quest=929
Spell: https://classic.wowhead.com/spell=9582

**Expected Behavior**

Once the "filling" spell has completed casting the vial should return to your inventory as a "Filled Jade Vial" and the Quest should be completed - I believe you gain some XP from the filling process

**Comment by joranis** [comment]
Related #200. Was your inventory full? Because a full inventory will destroy the vial or any related quest item with a Use quest item -> retrieve new quest item interaction.

**Comment by Disorientx** [comment]
Yeah, I had a full inventory. Is that an intended feature though? I assume
I'd be able to re-retrieve the Vial if I abandoned the quest?
