### ISSUE TITLE
Player/NPC model disappearing indoors

### ISSUE THREAD

**Issue by Brodda** [the-hyjal-project/bugtracker#223]
**Describe Your Issue**
Players/NPCs in indoors disappear when you have logged in far enough from them and Terrain Distance is set low.

**Steps To Reproduce**
1. Set 'Terrain Distance' in video options to either lowest or second lowest. (Third Lowest and higher don't seem to have this issue, although the longest distance I tested was between Razor Hill and Orgrimmar and a longer distance than this could be necessary for testing the higher Terrain Distance settings.)
2. Logout 300+ yards away from the indoors area that will be tested. (Second lowest Terrain Distance requires you to logout a bit further than the lowest setting.
3. Login and run to the indoors area and move the camera around. The point of view has to be inside the indoors area for the models to disappear.
[Video example](https://streamable.com/53sy7b)
[Example logout spot for Orc starting area](https://i.imgur.com/OheR4y8.jpg)

**Expected Behavior**
Models shouldn't be disappearing. I tested on a Light's Hope repack and the NPCs didn't disappear there.

**Comment by Gamemechanicwow** [comment]
Another user had a very similar issue where mobs turned invisible. https://github.com/the-hyjal-project/bugtracker/issues/13

The issue was being caused by his tesselation settings for his amd gpu. Lowering it fixed it.

Its a client issue.
