### ISSUE TITLE
mobs pets have sticky agro

### ISSUE THREAD

**Issue by Roflkopterr** [the-hyjal-project/bugtracker#224]
Mobs from all available open world areas so far (level 24) have sticky agro, once I send in my pet they will not come off no matter what ability or how much dmg is used on the them afterwards. First thing on the agro table and they will never come off of it.

**Comment by Nolin7777** [comment]
Use the template please. There are reasons because we wrote one...
I tested this but it worked for me.
Please provide some more information so I can find the issue, otherwise I have to close this.
