### ISSUE TITLE
Quest Washed Ashore Bug

### ISSUE THREAD

**Issue by paintxd1** [the-hyjal-project/bugtracker#229]
**Describe Your Issue**
Two of us tried to loot the sea creature in Darkshore for the quest Washed Ashore, from then on loot attempts receive "item is already in use" error message

**Steps To Reproduce**

1. Left zone and came back
2. Relogged
3. 

https://classicdb.ch/?quest=3524

**Expected Behavior**

Should be able to loot

**Comment by petage** [comment]
I can confirm this. I just tried to loot the creature and got an error message "That is already being used". I exited my client, deleted my WDB folder, launched the game again and retried looting the creature getting the same error message.
