### ISSUE TITLE
Debuff interaction (Faerie Fire and Puncture Armor)

### ISSUE THREAD

**Issue by fitqt** [the-hyjal-project/bugtracker#235]
**Describe Your Issue**

Currently, Faerie Fire removes Puncture Armor and vice versa.

**Steps To Reproduce**
1. Use listed weapons to apply aura Puncture Armor ([11791](https://classic.wowhead.com/spell=11791/puncture-armor) or [17315](https://classic.wowhead.com/spell=17315/puncture-armor)) to the target
2. Use Feral spec druid to try applying both Faerie Fire ([9907](https://classic.wowhead.com/spell=9907/faerie-fire)) and Faerie Fire (Feral) ([17392](https://classic.wowhead.com/spell=17392/faerie-fire-feral))
3. Notice them removing each other on proc/cast

Items: [Digmaster 5000](https://classic.wowhead.com/item=9465/digmaster-5000), [Vibroblade](https://classic.wowhead.com/item=9485/vibroblade), [Bashguuder](https://classic.wowhead.com/item=13204/bashguuder), [Rivenspike](https://classic.wowhead.com/item=13286/rivenspike)
Spells:  [Puncture Armor](https://classic.wowhead.com/spell=11791/puncture-armor), [Puncture Armor](https://classic.wowhead.com/spell=17315/puncture-armor), [Faerie Fire](https://classic.wowhead.com/spell=9907/faerie-fire), [Faerie Fire (Feral)](https://classic.wowhead.com/spell=17392/faerie-fire-feral)

**Expected Behavior**

Faerie Fire and Puncture Armor should stack prior to 1.8.0.

Patch [1.8.0](https://wow.gamepedia.com/Patch_1.8.0) states:

`The Puncture Armor ability found on the Rivenspike, Bashguuder, Digmaster 5000, and Vibroblade will no longer stack with Faerie Fire.`

Taking into account this [commit](https://github.com/vmangos/core/commit/e6b3ecd2c2475543d97a178488ece4d6a1244628) which was based on [Classic logs](https://nuiva.github.io/debuffprio/#17315) I'm not exactly sure what would be the interaction between those two spells regarding priority in debuffs slots in this case.

**Comment by Nolin7777** [comment]
Thanks for your ticket. Since we use the 1.12 state for spell mechanics I have to close this ticket.
