### ISSUE TITLE
Some mobs won't stop chasing you

### ISSUE THREAD

**Issue by Simp-N** [the-hyjal-project/bugtracker#238]
**Describe Your Issue**
Sometimes, [Starving Mountain Lion](https://classic.wowhead.com/npc=2384/starving-mountain-lion) and [Gray Bear](https://classic.wowhead.com/npc=2351/gray-bear) (and maybe [Vicious Gray Bear](https://classic.wowhead.com/npc=2354/vicious-gray-bear)) will chase you endlessly, even if you don't hit them. It's very similiar to #https://github.com/the-hyjal-project/bugtracker/issues/228 and I'm guessing it's the same issue. It seems to happen when you aggro two of them. Also, rooting them with Frost Nova seems to make them return to normal and stop chasing you.

While I can replicate it with Starving Mountain Lion and Gray Bear, I had trouble replicating it with Vicious Gray Bear.

**Steps To Reproduce**
1. Aggro two of these mobs at the same time.
2. Run and just keep running, survive

Demonstrations: 
[Starving Mountain Lion](https://streamable.com/eehe4k)
[Gray Bear](https://streamable.com/jgwwh2)
[Vicious Gray Bear](https://streamable.com/h1boq6). This recording starts mid-chase. However, you can look at the spawn points on Wowhead that these bear spawn a bit south of where I am. But this mob was actually aggroed a bit further into the area of which they spawn. Notice that in the Gray Bear video I do catch one Vicious during the chase and he then keeps chasing me for quite long.

**Expected Behavior**
If they're not hit, they should return to where you aggroed them after some time or distance, but I don't know exactly when.

**Comment by horaxi** [comment]
Not sure if this is related, but mage's chill from frost armor does extend the leash without attacking the mob. I am not sure if chill from frost armor is supposed to extend the the leash or if it is a bug, but what I have noticed at least in world chat is the people who are complaining the most about the huge leashes have been mages, assumingly from frost armor's chill extending the leash each time they get attacked.

**Comment by horaxi** [comment]
I tested the frost armor's chill again and it is definitely bugged. Any mob that is faster than the player will have an infinite leash, constantly renewing its leash after each attack on the mage's frost armor.

**Comment by Simp-N** [comment]
> 
> 
> I tested the frost armor's chill again and it is definitely bugged. Any mob that is faster than the player will have an infinite leash, constantly renewing its leash after each attack on the mage's frost armor.

Ya, I tried replicating this without Frost Armor/Ice Armor on, and couldn't. The previous issue with the Razormane stalker was with a druid. Perhaps Thorns was part of the issue there.

**Comment by Gamemechanicwow** [comment]
Changes to leash behavior has been pushed to PTR.

**Comment by hyjal-tester** [comment]
https://streamable.com/dc1nsq

I just created this clip, chill from frost armor is still extending the leash somehow.

**Comment by Simp-N** [comment]
Ya, it's still bugged I'm afraid.

[Video](https://streamable.com/y6sr2e)

I remove my Ice Armor towards the end, and then the mob finally runs back to his spawn.

**Comment by Simp-N** [comment]
I was gonna test another bug when this happened. It may be related to this issue. Basically the pigman hunter de-aggroes after a while, but his pet does not, and whenever the pet attacks the pigman re-aggroes.

https://streamable.com/d11egu
