### ISSUE TITLE
Follow pathing is not working

### ISSUE THREAD

**Issue by Johanahsberg** [the-hyjal-project/bugtracker#239]
When targeting another player and using the follow action the following player will not path correctly and instead run away from the targeted player.

**Comment by Johanahsberg** [comment]
Might be to server issues, but is on the PTR so shouldnt be.

**Comment by Gamemechanicwow** [comment]
If you go beyond 64 FPS /follow will not work. This is a bug/limitation in the client and unfortunately not something we can fix.

**Comment by Johanahsberg** [comment]
Ah okey, well good to know. Closing thread
