### ISSUE TITLE
32.8, 71.1 in redridge mountains, another clipping spot - Multiple pictures 

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#24]
**Describe Your Issue**
https://cdn.discordapp.com/attachments/780923795782369360/782566405907677214/unknown.png
https://cdn.discordapp.com/attachments/780923795782369360/782566526712020992/unknown.png
https://cdn.discordapp.com/attachments/780923795782369360/782566680790171658/unknown.png
https://cdn.discordapp.com/attachments/780923795782369360/782567265086341120/unknown.png
https://cdn.discordapp.com/attachments/780923795782369360/782567523350216714/unknown.png
https://cdn.discordapp.com/attachments/780923795782369360/782567779055960084/unknown.png

**Steps To Reproduce**

1.
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected Behavior**

**Comment by kodolol** [comment]
As far as I know these issues were because of their AMD gpu, tesselation to be exact.

**Comment by Gamemechanicwow** [comment]
> As far as I know these issues were because of their AMD gpu, tesselation to be exact.

Can confirm that was the issue.
