### ISSUE TITLE
Wonky line of sight issues

### ISSUE THREAD

**Issue by jamesaso** [the-hyjal-project/bugtracker#245]
In the houses in Durnholde Keep there are invisible walls/props/something that block line of sight for both NPCs and players.
(Sorry for bad description)

Video demonstrations:
https://streamable.com/anchag
https://streamable.com/zqwijp

**Comment by Simp-N** [comment]
Yeah it seems some buildings have severe LoS issues, but it's difficult to explain. I've had mobs run through walls and floors too. That kind of building at Morbant Fel for example.
