### ISSUE TITLE
[Rare] Commander Felstrom pops 2 times (Duskwood)

### ISSUE THREAD

**Issue by Hey0001** [the-hyjal-project/bugtracker#247]
Where ? Inside the Dawning Wood Catacombs (NW of Duskwood)

1 - Kill Commander Felstrom (Rare)
2 - He will pop a second time (no loot on the first one)

**Comment by Hey0001** [comment]
ID : https://classic.wowhead.com/npc=771/commander-felstrom

**Comment by jamesaso** [comment]
Works as intended then?

https://classic.wowhead.com/spell=3488/felstrom-resurrection
