### ISSUE TITLE
Elixir of Poison Resistance has the wrong effect

### ISSUE THREAD

**Issue by ripcurl91** [the-hyjal-project/bugtracker#250]
**Describe Your Issue**
Elixir of Poison Resistance grants immunity to poisons for 1 minute.

**Steps To Reproduce**

1. Use Elixir of Poison Resistance
2. 
3. 

Item: https://classic.wowhead.com/item=3386/elixir-of-poison-resistance

**Expected Behavior**
Elixir of Poison resistance should cure the imbiber of up to 4 poisons up to level 60.

**Comment by NickTyrer** [comment]
I think this is normal behavour until a later patch.
