### ISSUE TITLE
Quest - Kodo Roundup

### ISSUE THREAD

**Issue by Sundorian** [the-hyjal-project/bugtracker#259]
**Describe Your Issue**

In this quest you are given an item called the [Kodo Kombobulator](https://classicdb.ch/?item=13892)  With this item you are to go find Kodo around the area and use it to tame them and bring them back to [Smeed Scrabblescrew](https://classicdb.ch/?npc=11596)  He then says something like - Hey, look out with that kodo! You had better inspect that beast before I give you credit.  This is where the problem lies.  The player is unable to click on the kodo and can not complete the quest.
**Steps To Reproduce**

1.Accept quest from Smeed Scrabblescrew. He provides the Kodo Kombobulator.
2. Go find a Kodo to tame.  Tame a kodo and bring it back to Smeed Scrabblescrew
3. After  [Smeed Scrabblescrew](https://classicdb.ch/?npc=11596) says inspect the beast,try to click on the kodo but can't.

Item: [Kodo Kombobulator](https://classicdb.ch/?item=13892) 
Quest: https://classicdb.ch/?quest=5561
Spell:

**Expected Behaviour**

After taming a Kodo and bringing it back to Scrabblescrew, he should tell you to inspect the kodo.  You then click on the kodo and which completes the taming of 1 Kodo.  You must find, tame and bring back 5 Kodo and inspect all 5 for the quest to be completed.

**Comment by Gamemechanicwow** [comment]
I can't reproduce it. I completed the quest with both a horde and ally character without any problems.

**Comment by Hey0001** [comment]
I'm not sure if this quest will be fixed soon, but here are some issues with it right now :

- Sometimes, when you use the Kodo Kombobulator on a Kodo, the cast and the animation work but the Kodo is not Tamed. You then have to try to tame another Kodo
- Sometimes, you can't click on the Kodo tamed (when you are near the gobelin who gave you the quest). You then have to cancel the quest or wait 5 minutes to try to tame another Kodo
