### ISSUE TITLE
Spirit Healer at Raven Hill Cemetery is missing

### ISSUE THREAD

**Issue by alassdaire** [the-hyjal-project/bugtracker#264]
**Describe Your Issue**

Upon dying near Raven Hill Cemetery, I noticed that no spirit healer was present. 

**Steps To Reproduce**

1. Die near Raven Hill Cemetery in Duskwood.
2. Note that there is no Spirit Healer

NPC: https://classic.wowhead.com/npc=6491/spirit-healer

**Expected Behaviour**

There should be a Spirit Healer at Raven Hill Cemetery. 
See: https://classic.wowhead.com/npc=6491/spirit-healer

**Comment by Gamemechanicwow** [comment]
The spirit healer is not available in patch 1.2.

>  World of Warcraft Client Patch 1.8.0 (2005-10-11)
>  - A Graveyard has been added to Duskwood at Ravenhill Cemetery.

**Comment by alassdaire** [comment]
This doesn't make any sense. The graveyard is in game and functioning. If you want to be Blizzlike, remove the graveyard, and send people to the one in Darkshire. Otherwise, it is absolutely stupid to send people dead to a graveyard with no spirit healer, meaning that if they want to spirit res, they have to walk all the way to Darkshire dead. There's nothing Blizzlike about that!

**Comment by Gamemechanicwow** [comment]
My bad. I missunderstood the issue. You should indeed be transfered to a different graveyard.
