### ISSUE TITLE
Booty Bay–Ratchet boat missing 

### ISSUE THREAD

**Issue by alassdaire** [the-hyjal-project/bugtracker#265]
**Describe Your Issue**
I have now waited for the Booty Bay–Ratchet boat for ten minutes, and no boat has appeared.

**Steps To Reproduce**

1. Stand on the docks in Booty Bay.
2. Notice no boat ever arrives.

**Expected Behaviour**

A boat should be travelling back and forth between BB and Ratchet

**Comment by Gamemechanicwow** [comment]
The boat appears for me. I can't see any issues with the transport.

**Comment by alassdaire** [comment]
> The boat appears for me. I can't see any issues with the transport.

I logged in now and it seems fixed, but something is most likely messed up, as I did indeed go for ten minutes without seeing a boat earlier.

**Comment by GM-Dave-THP** [comment]
Tested in game - unable to reproduce

BB Docked time: 61 seconds 
Time to Ratchet: 2mins  
Ratchet docked time:  58 seconds
Time to BB: 1min 41 seconds
