### ISSUE TITLE
Lord Melenas spawn location

### ISSUE THREAD

**Issue by petage** [the-hyjal-project/bugtracker#266]
**Describe Your Issue**

Lord Melenas currently has only one spawn location.

**Steps To Reproduce**

``SELECT * FROM `creature` WHERE `id`='2038';``

https://classic.wowhead.com/npc=2038/lord-melenas

**Expected Behaviour**

Lord Melenas should have three spawn locations according to Classic WoW and a [comment](https://classic.wowhead.com/npc=2038/lord-melenas#comments:id=2896120) posted by fendarin on 2006-09-03. Here's video proof of each spawn location on Classic:
1. On the ledge overlooking the biggest cavern: https://youtu.be/jtjXUoZudSw?t=26087.
2. In the biggest cavern, just below the ledge: https://youtu.be/oF_Ds24qz4E?t=6617.
3. On the ledge overlooking the central cavern: https://youtu.be/4gNmGIFrEFE?t=13715.

**Comment by NickTyrer** [comment]
@Nolin7777 fixed here https://github.com/vmangos/core/pull/1036
