### ISSUE TITLE
Lady Sathrah spawn location

### ISSUE THREAD

**Issue by petage** [the-hyjal-project/bugtracker#267]
**Describe Your Issue**

Lady Sathrah currently has only one spawn location.

**Steps To Reproduce**

``SELECT * FROM `creature` WHERE `id`='7319';``

https://classic.wowhead.com/npc=7319/lady-sathrah

**Expected Behaviour**

Lady Sathrah should have three spawn locations according to Classic WoW and [comments](https://classic.wowhead.com/npc=7319/lady-sathrah#comments) on Classic Wowhead. Here's video proof of each spawn location on Classic:
1. West of Wellspring River, near where the rogue quest npc [Sethir the Ancient](https://classic.wowhead.com/npc=6909/sethir-the-ancient) is located: https://youtu.be/jtjXUoZudSw?t=30570.
2. West of Wellspring River, very close to the river: https://youtu.be/K1kp88nZ-RE?t=13012.
3. East of Wellspring River, easternmost corner of the area: https://youtu.be/Old_imBlQqE?t=11740.

**Comment by NickTyrer** [comment]
@Nolin7777 fixed here https://github.com/vmangos/core/pull/1036
