### ISSUE TITLE
Gaffer jacks quest unable to re-pick up

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#27]
**Describe Your Issue**
So I was able to accept the quest https://classic.wowhead.com/quest=1579/gaffer-jacks with a fishing skill of 10. I abandoned the quest and now the NPC doesn't offer it again. Two possible bugs here: 1) The quest shouldn't be offered until a higher fishing skill. Comments about the fishing skill required are conflicting, but the value 30 keeps popping up (check the comments in my link). 2) The quest should be repickable after abandoning it. No quests that you can't repick after abandoning them come to my mind, so why would this be a special case? I tried restarting my client and deleting WDB with no luck.

**Steps To Reproduce**

1.
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected Behavior**

**Comment by petage** [comment]
Adding a link to the [NPC](https://classic.wowhead.com/npc=3666/wizbang-cranktoggle) in question.

**Comment by ratkosrb** [comment]
Cannot reproduce bug. I can drop the quest and accept it back with no issue. And also it requires 30 skill not 10. It does not show up if you have only 10 skill.

**Comment by petage** [comment]
I was able to reproduce this bug with a fresh lvl 10. I trained my fishing from [Gubber Blump](https://classic.wowhead.com/npc=10216/gubber-blump) by accepting the quest [The Family and the Fishing Pole](https://classic.wowhead.com/quest=1141/the-family-and-the-fishing-pole) and selecting the dialogue option _Gubber, I don't know how to fish_. Although learning fishing from him probably doesn't make a difference I thought I'd mention it anyway.

**Steps To Reproduce**
1. Be level 10 and train fishing.
2. Fish until your skill in fishing is at least 5.
3. Apply a [Shiny Bauble](https://classic.wowhead.com/item=6529/shiny-bauble) to your Fishing Pole if you already didn't.
4. Talk to Wizbang Cranktoggle and notice how he offers you the quest Gaffer Jacks.

![WoWScrnShot_121220_223627](https://user-images.githubusercontent.com/47227158/101995011-7728ee00-3ccf-11eb-896f-9ed2607bdcf5.jpg)
![WoWScrnShot_121220_225141](https://user-images.githubusercontent.com/47227158/101995013-7a23de80-3ccf-11eb-992c-a1f8ef6cc6e7.jpg)
In the first screenshot I'm able to accept the quest with a fishing skill of 5 (+25 from the lure). In the second screenshot I'm about to complete the quest (and I did complete it successfully).

**Conclusion**
It looks like Shiny Bauble (and presumably other lures) which temporarily increases your skill in fishing makes you eligible to accept the quest which you wouldn't normally be able to. This could apply to other fishing skill increasing items, the gloves enchant and other fishing-related quests, but I haven't done any further testing. I'd be interested to see if this works in Classic WoW as well.

**Comment by Gamemechanicwow** [comment]
Temporary skill bonuses has no longer any effect quest skill requirements.
