### ISSUE TITLE
Forsaken Courier/Bodyguards not behaving correctly.

### ISSUE THREAD

**Issue by alassdaire** [the-hyjal-project/bugtracker#270]
**Describe Your Issue**
As part of the "Hints of a New Plague" quest, the Forsaken Courier and four Forsaken Bodyguards are meant to walk from Go'shek Farm in Arathi Highlands to Tarren Mill. At present, some of the NPCs are somehow deviating from their route and ending up fighting NPCs deep in Refuge Pointe (the Alliance base). They also don't seem to be walking together as a group, but apart, which seems to be part of the problem.

**Steps To Reproduce**

1. Go to the Arathi Highlands, and find the Forsaken Courier/Bodyguards.
2. Note that they are walking seperately, and that some of the npcs are aggroing onto Refuge Pointe guards and dying

NPC:
https://classic.wowhead.com/npc=2714/forsaken-courier
https://classic.wowhead.com/npc=2721/forsaken-bodyguard

Quest:
https://classic.wowhead.com/quest=658/hints-of-a-new-plague

**Expected Behaviour**

The Forsaken Courier and Bodyguards should be walking together from Go'shek Farm to Tarren Mill, unless they get killed by players or Lieutenant Valorcall (https://classic.wowhead.com/npc=2612/lieutenant-valorcall) and his patrolling horsemen. They should never end up in Refuge Pointe. I'll attach a picture for reference.
![bug-bodyguards](https://user-images.githubusercontent.com/77180009/104820324-0a3ed180-5802-11eb-8dc9-cc3e0f1e3833.jpg)

**Comment by Simp-N** [comment]
I don't know if this helps, but here's a recording I made at 52,35 in Hillsbrad Foothills when I noticed these flying NPCs, who were three of the courier guards.

https://streamable.com/aj2br7

**Comment by GM-Dave-THP** [comment]
Checked randomly on the guards today and pathing as normal, can we rule out that they were not pulled there by a player?

**Comment by alassdaire** [comment]
> Checked randomly on the guards today and pathing as normal, can we rule out that they were not pulled there by a player?

Yes, and I have now observed the behaviour multiple times, including the 'flying' behaviour shown in the video above. Clearly there is something wrong with these NPCs.

**Comment by Hey0001** [comment]
Kinolary from the escort quest "Hints of a new plague?" : https://classic.wowhead.com/quest=658/hints-of-a-new-plague
is targeting a Forsaken Bodyguard who spawned under the hill. Can't attack him.

![Forsaken Bodyguard spawned under the ground](https://user-images.githubusercontent.com/77048365/109086087-360b7c00-770b-11eb-8f7d-6989abb90cb7.png)
