### ISSUE TITLE
Gromgol inn not providing a "rested" area to log out in.

### ISSUE THREAD

**Issue by Roflkopterr** [the-hyjal-project/bugtracker#273]
**Describe Your Issue**
Grom gol Inn *inside the flight tower with the inn keeper* Does not apply a rested area. You have to log out after 20 sec and do not get rested xp.

**Steps To Reproduce**

1.
2. 
3. 

Item: https://classic.wowhead.com/item=
Quest: https://classic.wowhead.com/quest=
Spell: https://classic.wowhead.com/spell=

**Expected Behaviour**

**Comment by Simp-N** [comment]
I too did not get rested when in that inn. Tried walking around in there to see if I'd get rested anywhere, including heading up the top, but never got any icon, never got instant logout.

**Comment by Pirupuku** [comment]
Grom'gol didn't had an Inn in Patch 1.2 as far as I remember
