### ISSUE TITLE
Erelas Ambersky dialogue broken

### ISSUE THREAD

**Issue by swmpbb** [the-hyjal-project/bugtracker#276]
**Describe Your Issue**
NPC Erelas Ambersky's dialogue that appears after clicking "Tell me more about these hippogryphs." is missing (clicking the sentence prompt does nothing).

**Steps To Reproduce**
1. Talk to Erelas Ambersky in Rut'theran Village
2. Click "Tell me more about these hippogryphs."

NPC: https://classic.wowhead.com/npc=7916/erelas-ambersky

**Expected Behaviour**
After clicking the dialogue prompt a message should appear in the window talking about the hippogryphs.

**Comment by NickTyrer** [comment]
Fixed here https://github.com/vmangos/core/pull/1036

**Comment by NickTyrer** [comment]
@Nolin7777 this can be closed
