### ISSUE TITLE
Theramore docks graphic glitch

### ISSUE THREAD

**Issue by YellowRyder** [the-hyjal-project/bugtracker#278]
**Describe Your Issue**

Support beam for the Theramore dock is only visible from one side; graphic missing

![eeee](https://user-images.githubusercontent.com/77170734/104856667-fa96ba00-58e1-11eb-9744-63aa7b10e1f8.png)
![eee](https://user-images.githubusercontent.com/77170734/104856668-fbc7e700-58e1-11eb-8da2-edd30d183afd.png)

**Comment by Nolin7777** [comment]
Sorry I can't fix the client
