### ISSUE TITLE
 drop rate of Thresher Eye (id 5412) seems to be way too high. 

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#28]
**Describe Your Issue**
The drop rate of Thresher Eye (id 5412) seems to be way too high. 12 out of 13 Darkshore Threshers dropped the item. According to https://web.archive.org/web/20060629090500/http://wow.allakhazam.com/db/item.html?witem=5412 the drop rate should roughly be 22.5% for Darkshore Threshers and 3% for Elder Darkshore Threshers.

**Steps To Reproduce**

1.
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected Behavior**

**Comment by petage** [comment]
Adding the [Classic Wowhead page](https://classic.wowhead.com/item=5412/thresher-eye) and a [Thottbot archive](https://web.archive.org/web/20070316071913/http://www.thottbot.com/i5412) for some more reference, even though the archive is from early TBC.

**Comment by ratkosrb** [comment]
Fixed in https://github.com/vmangos/core/commit/c1db8e8f625ba5dbba3c03a11eafb4411e1557db
