### ISSUE TITLE
Biznicks 247x127 Accurascope

### ISSUE THREAD

**Issue by Pirupuku** [the-hyjal-project/bugtracker#280]
**Describe Your Issue**
Patch 1.10

"Biznicks 247x127 Accurascope now only affects ranged attacks, and Elemental Sharpening Stones no longer will affect ranged weaponry. The schematic for the Accurascope will now drop once again in the Molten Core."

**Steps To Reproduce**

1.
2. 
3. 

Item: https://classic.wowhead.com/item=18290/schematic-biznicks-247x128-accurascope

**Expected Behaviour**

Will it be like it should in Patch 1.2 -> increasing range AND melee hit
Or is it like seeing above as in Patch 1.10?

**Comment by Nolin7777** [comment]
This item ID doesn't exist in the database. You will see when you click the link, which you have posted.

**Comment by Pirupuku** [comment]
Edited the link!

**Comment by Nolin7777** [comment]
https://classic.wowhead.com/item=18283/biznicks-247x128-accurascope

**Comment by Nolin7777** [comment]
We will use [this spell](https://classic.wowhead.com/spell=22779), which says it only affects range attacks.
