### ISSUE TITLE
Hunter eagleeye not able to be chain casted

### ISSUE THREAD

**Issue by Roflkopterr** [the-hyjal-project/bugtracker#283]
**Describe Your Issue**
When you attempt to cast eagle again after the initial cast it just breaks your current channel/cast.

**Steps To Reproduce**

1. Nothing special just try to cast eagle more than once in succession and instead of chain casting like it should it cancels the first cast
2. 
3. 

Item: https://classic.wowhead.com/item=
Quest: https://classic.wowhead.com/quest=
Spell: https://classic.wowhead.com/spell=

**Expected Behaviour**
You should be able to cast successively without breaking your current cast/channel aka chain casting to gain larger view range from your location.

**Comment by Nolin7777** [comment]
No source no fix
