### ISSUE TITLE
Character disappears in ground

### ISSUE THREAD

**Issue by aehmya** [the-hyjal-project/bugtracker#284]
**Describe Your Issue**
Next to Kharanos are small mountains behind a fence, if you move there you disappear in the ground.

**Steps To Reproduce**
![grafik](https://user-images.githubusercontent.com/8287638/105096051-d3d5b080-5aa6-11eb-8b5b-96abf74bf131.png)

**Expected Behaviour**
You can walk normally there.

**Comment by aehmya** [comment]
This happens on many other positions too.

**Comment by aehmya** [comment]
![grafik](https://user-images.githubusercontent.com/8287638/105096504-75f59880-5aa7-11eb-8e8b-5097280adfcb.png)

**Comment by Gamemechanicwow** [comment]
![image](https://user-images.githubusercontent.com/2223066/105113606-887eca80-5ac5-11eb-95d0-15223acf6331.png)

There is no small mountain there.
As far as I know this issueis cause by the tesselation effect on AMD gpus. Try lowering the tesselation setting in your drivers settings.
