### ISSUE TITLE
Gouge Rotates Target

### ISSUE THREAD

**Issue by swmpbb** [the-hyjal-project/bugtracker#286]
**Describe Your Issue**
Using gouge on most NPCs causes them to instant rotate away from you, generally 180 degrees but sometimes 90 degrees.
However, despite now having their back to you, you cannot backstab them and have to run around and backstab them from
the front of their character model (face stab).

**Steps To Reproduce**
1. Gouge mob
2. Try to backstab its apparent "back" after it rotates

Spell: https://classic.wowhead.com/spell=1776/gouge

**Expected Behaviour**
After using gouge the target should remain facing the same direction they were before gouge succeeded.

**Comment by Gamemechanicwow** [comment]
This is blizzlike and is caused by how the client handles NPCs orientation.

https://github.com/vmangos/core/issues/872

**Comment by cliff7422** [comment]
Is there any chance this could be looked at again? Currently, it feels bad to use gouge and have the client lie about the mob's facing, especially while playing a class that needs to use some abilities from behind.
