### ISSUE TITLE
Mage quest Report to Jennea

### ISSUE THREAD

**Issue by petage** [the-hyjal-project/bugtracker#287]
**Describe Your Issue**

The mage quest Report to Jennea cannot be started from the NPC Zaldimar Wefhellt.

**Steps To Reproduce**

1. Be a mage and at least lvl 15.
2. Talk to Zaldimar Wefhellt in Goldshire, Elwynn Forest and notice how he doesn't offer you the quest Report to Jennea.

https://classic.wowhead.com/quest=1919/report-to-jennea
https://classic.wowhead.com/npc=328/zaldimar-wefhellt

**Expected Behaviour**

According to [Classic Wowhead](https://classic.wowhead.com/quest=1919/report-to-jennea), the quest should be available from both Zaldimar Wefhellt and Dink. Check the Quick Facts box on the right-hand side and notice the NPCs listed after the text _Start:_.

**Comment by NickTyrer** [comment]
```INSERT INTO `creature_questrelation` (`id`, `quest`, `patch_max`) VALUES
(328, 1919, 10);```
