### ISSUE TITLE
Stone drop rates from mining veins are too low

### ISSUE THREAD

**Issue by Simp-N** [the-hyjal-project/bugtracker#289]
**Describe Your Issue**
Some of the drop rates of mining stones from mining veins may be too low. When you can loot stones from veins, you may sometimes get more than one. The max count of this appears to be correct, but it's the chance to loot stones that may be off.

**Steps To Reproduce**
``SELECT gameobject_template.entry, gameobject_template.name, item_template.name, gameobject_loot_template.ChanceOrQuestChance, gameobject_loot_template.maxcount``
``FROM gameobject_template``
``INNER JOIN gameobject_loot_template ON gameobject_loot_template.entry = gameobject_template.data1``
``INNER JOIN item_template ON gameobject_loot_template.item = item_template.entry``
``WHERE item_template.name LIKE '% Stone' AND (gameobject_template.name LIKE '%Vein' OR gameobject_template.name LIKE '%Deposit')``
``ORDER BY item_template.name, gameobject_template.entry``

This should list the drop rate for each stone from their respective veins.

**Expected Behaviour**
Starting with **[Rough Stone](https://classic.wowhead.com/item=2835/rough-stone#mined-from-object)**. It has four veins. On Hyjal PTR the droprate of Rough Stone from all four veins is 35%. I will list the drop rate for each vein on Wowhead.
[Copper Vein, 1731](https://classic.wowhead.com/object=1731/copper-vein): 45%
[Copper Vein, 2055](https://classic.wowhead.com/object=2055/copper-vein): 67%
[Copper Vein, 3763](https://classic.wowhead.com/object=3763/copper-vein): 67%
[Copper Vein, 103713](https://classic.wowhead.com/object=103713/copper-vein): 45%

**[Coarse Stone](https://classic.wowhead.com/item=2836/coarse-stone#mined-from-object)**. Again, four veins. On Hyjal PTR drop rate is 35% for all four veins. On Wowhead the drop rates are these:
[Tin Vein, 1732](https://classic.wowhead.com/object=1732/tin-vein): 40%
[Tin Vein, 2054](https://classic.wowhead.com/object=2054/tin-vein): 65%
[Tin Vein, 3764](https://classic.wowhead.com/object=3764/tin-vein): 66%
[Tin Vein, 103711](https://classic.wowhead.com/object=103711/tin-vein): 41%

**[Heavy Stone](https://classic.wowhead.com/item=2838/heavy-stone#mined-from-object)**. On Hyjal PTR there are two veins that drop it. Iron Deposit, and Ooze Covered Iron Deposit, at 25% drop rate. On Wowhead:
[Iron Deposit, 1735](https://classic.wowhead.com/object=1735/iron-deposit): 40%
[Ooze Covered Iron Deposit, 73939](https://classic.wowhead.com/object=73939/ooze-covered-iron-deposit): Does not drop anything according to Wowhead.
User 3179 on Discord also linked to this [Allakhazam page](https://web.archive.org/web/20050329000612/http://wow.allakhazam.com/db/item.html?witem=2838) for Heavy Stone, which lists it as 40,12% drop rate from Iron Deposit.

**[Solid Stone](https://classic.wowhead.com/item=7912/solid-stone#mined-from-object)**. Four veins again. Hyjal PTR has 20% drop rate for all four. On Wowhead:
[Mithril Deposit, 2040](https://classic.wowhead.com/object=2040/mithril-deposit): 40%
[Ooze Covered Mithril Deposit, 123310](https://classic.wowhead.com/object=123310/ooze-covered-mithril-deposit): 38%
[Mithril Deposit, 150079](https://classic.wowhead.com/object=150079/mithril-deposit): 43%
[Mithril Deposit, 176645](https://classic.wowhead.com/object=176645/mithril-deposit): 40%

**[Dense Stone](https://classic.wowhead.com/item=12365/dense-stone#mined-from-object)**. Seven veins! 25% on all seven on Hyjal PTR. On Wowhead: 
[Small Thorium Vein, 324](https://classic.wowhead.com/object=324/small-thorium-vein): 40%
[Ooze Covered Thorium Vein, 123848](https://classic.wowhead.com/object=123848/ooze-covered-thorium-vein): 39%
[Small Thorium Vein, 150082](https://classic.wowhead.com/object=150082/small-thorium-vein): 39%
[Rich Thorium Vein, 175404](https://classic.wowhead.com/object=175404/rich-thorium-vein): 40%
[Small Thorium Vein, 176643](https://classic.wowhead.com/object=176643/small-thorium-vein): 40%
[Ooze Covered Rich Thorium Vein, 177388](https://classic.wowhead.com/object=177388/ooze-covered-rich-thorium-vein): 40%
[Hakkari Thorium Vein, 180215](https://classic.wowhead.com/object=180215/hakkari-thorium-vein): 39%

So in some of these cases, the drop rates on Hyjal PTR are around half that of the drop rate listed on Wowhead. One could think that Wowhead's droprate are higher because it handles the occurences of more than one Stone dropping from one attempt differently, but I don't think that's the case. If you look at [Briarthorn](https://classic.wowhead.com/object=3729/briarthorn) for example. It can drop more than one Briarthorn on each attempt, and you always get at least one, but the drop rate isn't listed as higher than 100%.

If Heavy Stone has a 25% drop rate and can give 1-3 stones for each mining attempt, which are the stats on Hyjal PTR, you'd on avarage get one stone every two attempts, or 50%. If following Wowhead's stats, 40% and 1-3 stones per attempt, you'd on avarage get four stones for every five attempts, or 80%. Quite a difference.

**Comment by Nolin7777** [comment]
Very juicy ticket! <3
