### ISSUE TITLE
You can open clams in your bag while dead

### ISSUE THREAD

**Issue by PabloMB95** [the-hyjal-project/bugtracker#290]
Literally the title

**Comment by GM-Dave-THP** [comment]
Confirmed, you can NOT open prior to release, but once a ghost this is possible.

**Comment by GM-Dave-THP** [comment]
![image](https://user-images.githubusercontent.com/19539976/105420773-dc5df080-5c38-11eb-9c61-83d3934c9086.png)

From Classic.
