### ISSUE TITLE
Touch of Zanzil not affecting stealth

### ISSUE THREAD

**Issue by swmpbb** [the-hyjal-project/bugtracker#291]
When afflicted with Touch of Zanzil stealth is supposed to be ineffective; while you can still use stealth, enemies are supposed to be able to see you as if you weren't stealthed, that is not working at the moment.

**Steps To Reproduce**

1. Open the chest in the tower for Klaven's Tower rogue quest
2. Become afflicted with Touch of Zanzil on opening chest
3. Walking by an enemy while you are stealthed should cause them to aggro as if you weren't stealthed

Quest: https://classic.wowhead.com/quest=2359/klavens-tower
Spell: https://classic.wowhead.com/spell=9991/touch-of-zanzil

**Expected Behaviour**
When affected by Touch of Zanzil casting stealth should not hide you from enemies.

**Comment by ratkosrb** [comment]
The spell is currently hacked to its wotlk version where it prevents stealth altogether.

**Comment by Neto-WoW** [comment]
This seems to work as intended.
