### ISSUE TITLE
[Quest] Crown of the Earth vial is destroyed if inventory is full

### ISSUE THREAD

**Issue by hyjal-tester** [the-hyjal-project/bugtracker#292]
**Describe Your Issue**
Filling the vial for the Crown of the Earth quest will not work if your inventory is full and will destroy the vial.

**Steps To Reproduce**
1. Run to moonwell.
2. Have full inventory.
3. Use the vial, and notice that the vial is destroyed and quest remains incomplete.

Item: https://classic.wowhead.com/item=18152/amethyst-phial https://classic.wowhead.com/item=18151/filled-amethyst-phial
Quest: https://classic.wowhead.com/quest=7383/crown-of-the-earth

**Expected Behaviour**
If inventory is full there should be a full inventory error given, so the vial does not get destroyed and the player can make room for the filled vial.

This is a duplicate of #200 but it appears to have 404d so I thought I would write it, because the OP of that issue seems to have a deleted account or something.

As a reminder there was discussion about this bug affecting all quests where there is a Use Item -> New item created interaction, so keep that in mind while working on this.

https://streamable.com/fqiqql

**Comment by ratkosrb** [comment]
Fixed in https://github.com/vmangos/core/commit/55e8e3944057bb6e672427e1eeaf2f146f989208

**Comment by GM-Dave-THP** [comment]
Now returns "Inventory is full" when attempting to use.
