### ISSUE TITLE
Wrong pathing from mobs while dropping from great heights

### ISSUE THREAD

**Issue by PabloMB95** [the-hyjal-project/bugtracker#294]
**Describe Your Issue**
This mob chases me while ignoring proper pathing and just flies to me:
https://gyazo.com/06ff970707e103575a33ae7f1fceb269

**Steps To Reproduce**
Go to a waterfall and drop down while a mob chases you.

The NPC tested is https://classicdb.ch/?npc=2179 but I suspect that it's not a mob issue but a pathing problem with heights.

**Expected Behaviour**
Mob should path correctly around the terrain to reach me.

**Comment by ratkosrb** [comment]
It happened because you jumped in water. Mobs swim directly to the target when it's in water.

**Comment by ratkosrb** [comment]
This case should be solved after https://github.com/vmangos/core/commit/74c5f1e1387f520e96cd3a4bb3409eec295d4e4f

**Comment by PabloMB95** [comment]
Still bugged.
Proof 1: https://gyazo.com/b5dffb0f319e0cd2c88db7bc5bb49ea6
Proof 2: https://gyazo.com/3697545ef3642248a49a1aec68d9addd

**Comment by ratkosrb** [comment]
Another attempt https://github.com/vmangos/core/commit/9dba4ccf31b076f48163d792c5b0b4f623acf79c
