### ISSUE TITLE
Moonkins Skinnable

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#3]
**Describe Your Issue**
Moonkins were not skinnables on classic, I don't know how much vanilla like is that, but there are skinnables on Hyjal (and other pservers), I think this should be revised, since is not a big deal, the leather from high level moonkins (hinterlands) is a big help on the War Effort

**Steps To Reproduce**

None

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected Behavior**

**Comment by ratkosrb** [comment]
Fixed in https://github.com/vmangos/core/commit/c1db8e8f625ba5dbba3c03a11eafb4411e1557db
