### ISSUE TITLE
escort quest NPC "Pao'ka Swiftmountain" also bugging out

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#30]
**Describe Your Issue**
BUG: escort quest NPC "Pao'ka Swiftmountain" also bugging out like Gilthares when aggroing mobs

**Steps To Reproduce**

1.
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected Behavior**

**Comment by Gamemechanicwow** [comment]
https://github.com/vmangos/core/pull/894

**Comment by Nolin7777** [comment]
Will be fixed with the new fork
