### ISSUE TITLE
Hunter AP

### ISSUE THREAD

**Issue by gwsm1992** [the-hyjal-project/bugtracker#301]
Hunters are not getting the AP amount they should be getting according to WoW Classic.

In one of the newer development notes for classic:
Many helpful auras and buffs that improve Attack Power now properly apply to Ranged Attack Power.
Developers’ notes: This was an issue that was the result of a technical limitation in original World of Warcraft that was fixed in later updates to the game. During internal testing we discovered that this issue also affected the Paladin and Shaman 6-piece Tier 3 set bonuses, and in fixing that, we decided to also fix it in many other situations where buffs and auras should affect Ranged Attack Power.

It seems for the most part, Fengus Ferocity, Rallying Cry of the Dragonslayer and Juju Might all affect ranged AP now and the T3 bonus of Paladins and Shaman also boost a hunters ranged AP, not just melee AP. 

**Steps To Reproduce**
1. Apply Rallying Cry of the Dragonslayer to a Hunter
2. There is no ranged AP bonus
3. Same with Juju Might and Fengus Ferocity

Spell: https://classic.wowhead.com/spell=22817
https://classic.wowhead.com/spell=16329
https://classic.wowhead.com/spell=22888

**Expected Behaviour**
Instead of the buffs only increasing melee attack power, they should increase ranged attack power, or at least they do in Classic.

**Comment by ratkosrb** [comment]
This is a change from Classic, and this is not how it worked in Vanilla. These buffs should not buff ranged attack power.
https://www.wowhead.com/news=318385.2/hunter-buffs-auras-and-buffs-will-properly-apply-to-ranged-attack-power-in-wow-c
