### ISSUE TITLE
Improved Weapon Totems Shaman Talent not working

### ISSUE THREAD

**Issue by gwsm1992** [the-hyjal-project/bugtracker#302]
**Describe Your Issue**
Along with ranged attack power working now for many buffs in Classic, the Improved Weapon Totems talent for Shamans was also fixed and now boosted not only the attack power of just the shaman but also everyone else affected by the totem.

**Steps To Reproduce**
1. Have someone else be in your group.
2. Spec Shaman talents into Improved Weapon Totems talent
3. Drop Windfury Totem
4. View Shaman attack power and view other group members attack power
5. Shaman's attack power will be higher than other group members

Spell: https://classic.wowhead.com/spell=29193

**Expected Behaviour**
On Classic, it boosts everyone's attack power in the group, not just the shaman. This is listed as a bug here:
https://us.forums.blizzard.com/en/wow/t/improved-weapon-totems-does-not-give-bonus-attack-power-to-other-people-in-the-group/595293/36

**Comment by T1ti** [comment]
This is a blizzlike bug in 1.12, Blizzard fixed it in the TBC pre patch (2.0)
This is a design decision, if you want to fix a blizzlike bug or not.

**Comment by ratkosrb** [comment]
Working as intended for vanilla.
