### ISSUE TITLE
Hurricane damage stacks.

### ISSUE THREAD

**Issue by 123iqpl123** [the-hyjal-project/bugtracker#306]
**Describe Your Issue**
Multiple Hurricanes from druids stack and they all deal damage.

**Steps To Reproduce**
1. Get multiple druids in a group, pull mobs and each druid hurricanes.
2. Mobs get affected by the hurricane debuff multiple times and each druid deals damage with hurricane.

https://classic.wowhead.com/spell=17402/hurricane

**Expected Behaviour**
Damage and debuffs should not stack, if 2 druids cast hurricane on the same pack of mobs only the first one should deal damage and they shouldn't recieve 2 debuffs.

**Comment by Gamemechanicwow** [comment]
Do you got any proof that damage doesn't stack? I think it looks like a classic bug.

![image](https://user-images.githubusercontent.com/2223066/106549827-0dc89d00-6512-11eb-8f75-696328d2eaa8.png)
https://eu.forums.blizzard.com/en/wow/t/classic-bug-druid-aoe-spell-hurricane-dont-stack/96138

But nevertheless debuffs shouldn't stack.

**Comment by PabloMB95** [comment]
Looks like it's a bug from classic. Damage should stack but debuffs shouldn't.
