### ISSUE TITLE
Lupos not saved on relog

### ISSUE THREAD

**Issue by jokerxxzz** [the-hyjal-project/bugtracker#308]
**Describe Your Issue**

As hunter I tamed Lupos, twice feed him, relogged, Lupos disappear.
Call Pet spell didnt call him.
I rechecked with normal wolf and he stayed with me.

**Steps To Reproduce**

1. Tame Lupos
2. Relog
3. Lupos is absent

NPC: https://classic.wowhead.com/npc=521/lupos

**Comment by elderwow** [comment]
Had similar issue with tamed Broken Tooth today, fed few times, by the time I got from his spawnpoint to Kargath it dissapeared

**Comment by GM-Dave-THP** [comment]
Unable to replicate at the moment, tested with Lupos fed to full happiness relog multiple times and he stayed

**Comment by jokerxxzz** [comment]
I tamed second Lupos, fed to high happiness, relogged and got medium happiness.
May be relog decrease Lupos happiness by some amout?
