### ISSUE TITLE
Strength of Earth Rank 5 totem not working

### ISSUE THREAD

**Issue by Phoee** [the-hyjal-project/bugtracker#309]
Pretty much as says in the title - rank 1 - 4 work just fine but rank 5 doesn't exist. You can spam the spell and no totem appears; in fact it removes any pre-existing earth totem

**Comment by Gamemechanicwow** [comment]
Strenght of Earth Totem Rank 5 was added in patch 1.9, so the totem does not exist yet :>
Its a ptr bug that you where allowed to learn the spell.
