### ISSUE TITLE
Baron rivendare and Death pact

### ISSUE THREAD

**Issue by Depressionree** [the-hyjal-project/bugtracker#311]
**Describe Your Issue**

Rivendare heals from death pact even with no skeletons alive

**Steps To Reproduce**

1.kill the skeletons he spawns and wait for him to use death pact

NPC: https://classic.wowhead.com/npc=10440
not sure which death pact he uses
Spell: https://classic.wowhead.com/spell=17698
Spell: https://classic.wowhead.com/spell=17472
Spell: https://classic.wowhead.com/spell=17471

**Expected Behaviour**

he should not heal when all the skeletons are dead

**Comment by ratkosrb** [comment]
Fixed in https://github.com/vmangos/core/commit/da8346555e92621d65640033709339cdefc67a31
