### ISSUE TITLE
Flame Wrath spellpower scaling inaccuracy

### ISSUE THREAD

**Issue by YellowRyder** [the-hyjal-project/bugtracker#313]
**Describe Your Issue**

Flame Wrath should apply a flame shield buff that increases fire resistance and does 10 fire damage to attacks. It is supposed to scaled with 100% spellpower; currently, it is not applying any spellpower whatsoever.

**Steps To Reproduce**

1. Equip Flame Wrath
2. Hit mobs til proc
3. Check spellpower coefficient.

https://classic.wowhead.com/item=11809/flame-wrath

**Expected Behaviour**

It should scale with 100% spellpower coefficient, as seen on live.

**Comment by ratkosrb** [comment]
Fixed in https://github.com/vmangos/core/commit/c82d2f41dc6863744d67ca3eecb7ceb6d636d9f6
