### ISSUE TITLE
Mages can't activate "Blizzard AoE Indicator" while running.

### ISSUE THREAD

**Issue by radiix** [the-hyjal-project/bugtracker#315]
**Describe Your Issue**

As title reads, mages aren't able to use the ability "Blizzard" while moving. It says "cant use that while moving".
You have to stand still to see the AoE Indicator (green ring) appear.

**Steps To Reproduce**

1. Create Mage, learn ability "Blizzard -> Move and use spell Blizzard.

**Expected Behaviour** [Taken from Classic]
https://gyazo.com/b9b5a3bf80cc150796bbaf90cc47c18b

https://user-images.githubusercontent.com/7096803/106772529-6433f980-6640-11eb-91f7-598c7c6e9f8e.mp4

**Comment by PabloMB95** [comment]
It happens with all classes with AOE channeled spells like hunter volley, druid hurricane and warlock rain of fire.
Might just be a vanilla client problem (classic client is Legion client).

**Comment by Gamemechanicwow** [comment]
This is working as intended for vanilla. You can still move after you activated the ability and are targetting.
