### ISSUE TITLE
cluck!

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#32]
**Describe Your Issue**
gamebraking bug- i did the quest in westfall named cluck to get the chicken the food and i didnt got the chicken as a reward

**Steps To Reproduce**

1.
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected Behavior**

**Comment by kodolol** [comment]
This was just a misunderstanding, he didn't know he had to right click the egg 🐣
