### ISSUE TITLE
Buffs keep ticking down while pet is dismissed/player is logged off

### ISSUE THREAD

**Issue by lequintal69** [the-hyjal-project/bugtracker#332]
Disclaimer: I didnt try this on Hyjal. I'm making this report so that question is brought up to the team's attention

**The issue**
**_Buffs continue ticking down when pets are dismissed OR when you log off_**
(on the other hand, debuff do pause and stop ticking)

**Steps to reproduce:**
buff hunter pet with whatever buff. Dismiss or log off for the buff's duration. Notice the buff is gone

**How it should work (possibly)**
**_Buffs should linger on pets when pet is dismissed/player is logged off_**
Could not find specific evidence regarding BUFFS lingering on pets though I could find many on DEBUFFS  
https://www.youtube.com/watch?v=yva7MbQy11g  (warlock getting debuff to stay on his pet in 1.12)
https://www.youtube.com/watch?v=ckrcaDuizs4   (sheep on pet lingering while pet is dismissed)
Now I dont know if/why it would work differently for buffs. But I could not find HARD evidence either. 
The only mention of pet buffs I could find on patch notes was that one:
_"Pet buffs will now apply and remove properly"_ (patch 1.12)

Anyone can help on this?

**Comment by GM-Dave-THP** [comment]
Not tested on Hyjal
No evidence supplied to back of the issue. Afraid this will have to be closed.

Please re-open once confirmed.
