### ISSUE TITLE
Sap does not flag you for PvP

### ISSUE THREAD

**Issue by Simp-N** [the-hyjal-project/bugtracker#336]
**Describe Your Issue**
As a rogue, sapping someone does not flag you for pvp. This means that you can sap somebody, and they or their friends can't do anything to stop you from keep doing it.

**Steps To Reproduce**
1. Make a rogue and go to an area where you're not automatically flagged for PvP (such as Hyjal)
2. Look around for someone who has PvP enabled
3. Sap them, and you should see that you're still not flagged for pvp, they can't fight back against you. They will remain "yellow" for you and you will remain "blue" for them.

I noticed that if you sap, but it misses, you *will* be flagged for pvp, but if you're also specced into Sap you will not be flagged for pvp if the sap misses but you remain in stealth.

Sap:
[Rank 1](https://classic.wowhead.com/spell=6770/sap)
[Rank 2](https://classic.wowhead.com/spell=2070/sap)
[Rank 3](https://classic.wowhead.com/spell=11297/sap)

**Expected Behaviour**
You should get flagged for pvp if you sap a player of the other faction.

In general, any action taken towards a player of the other faction should flag you for pvp, and if Sap was an exception it would've been noted by people. I've spent some time looking around for any mention that Sap doesn't flag you for pvp but couldn't find anything. I've also tested this in Classic, and you will get flagged for pvp if you sap. Furthermore the inconsistent behaviour of hitting and missing sap doesn't make sense.

![Sorted_WoWScrnShot_210205_003953](https://user-images.githubusercontent.com/75734743/107117256-66cd6380-6879-11eb-9872-9baf88080d44.png)
![Sorted_WoWScrnShot_210205_180249](https://user-images.githubusercontent.com/75734743/107117277-8c5a6d00-6879-11eb-8e4b-75a2c3422093.png)
![Sorted_WoWScrnShot_210205_180426](https://user-images.githubusercontent.com/75734743/107117282-941a1180-6879-11eb-807b-94407cf57e07.png)

**Comment by Neto-WoW** [comment]
SAP triggering combat was added around Cataclysm, and they kept it for Classic. Since vMangos aims to be true to Vanilla, it should remain keeping you out of combat.

Evidence:
Comments here from players - > https://us.forums.blizzard.com/en/wow/t/concerns-regarding-rogue/297678/5
and -> https://us.forums.blizzard.com/en/wow/t/rogue-sap-bring-me-into-combat/294420/5
