### ISSUE TITLE
Following via Macro toggles Autorun when not facing target, gets glitchy 

### ISSUE THREAD

**Issue by ivanbobanst** [the-hyjal-project/bugtracker#338]
**Describe Your Issue**

Create a /follow Name macro
Face away from your target, hit the macro,
in a more laggy area, the character will try to turn towards the Target,
but will instead autorun away

/w Threall in-game I can show it

edit: V-Sync was off all the time

**Comment by Gamemechanicwow** [comment]
This is a client issue. Due to internal timings - going above 64 fps breaks follow. 

Sorry, but there is nothing we can do to fix it.
