### ISSUE TITLE
noticed this movement pattern with this specific mob

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#34]
**Describe Your Issue**
https://cdn.discordapp.com/attachments/780923795782369360/783292046278131742/pathing_Trim.mp4

**Steps To Reproduce**

1.
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected Behavior**

**Comment by GM-Dave-THP** [comment]
Creature (Entry: 475 Guid: 80596).

**Comment by Nolin7777** [comment]
I don't like to download videos, please upload it to a streamable platform

**Comment by ratkosrb** [comment]
I don't see an issue here.

**Comment by GM-Dave-THP** [comment]
I can see what they mean, the mob runs south then across to the player, this happens with a lot of mobs in vanilla typical error in pathing with pservers. Closing as this is not mob pacific.
