### ISSUE TITLE
Quest: The Balnir Farmstead not working

### ISSUE THREAD

**Issue by Amant23** [the-hyjal-project/bugtracker#341]
**Describe Your Issue**
Quest: The Balnir Farmstead (UC Mage Quest) - Cannot loot Balnir Snapdragon flowers at the Balnir Farmstead in Tirisfal Glades. 

**Steps To Reproduce**
1. Click on snapdragons but nothing happens. No cast bar. Click it a few times repeatedly and it just makes a sound. There are a few clumped together. None of them worked.

Item: https://classic.wowhead.com/item=7227/balnir-snapdragons
Quest: https://classic.wowhead.com/quest=1882/the-balnir-farmstead
Object: https://classic.wowhead.com/object=102985/balnir-snapdragons

**Expected Behaviour**
Click on snapdragons and loot them for quest item.

**Comment by Gamemechanicwow** [comment]
This is most likely a caching issue. Can you try clearing your wdb folder and try again?

**Comment by Gamemechanicwow** [comment]
I don't know if you still have trouble with the quest, but i have had it confirmed that clearing the wdb folder solves issues with this quest. So i am going to close to this issue.
