### ISSUE TITLE
Quest: Protecting the Shipment (Infinite Dark Iron Raider spawn)

### ISSUE THREAD

**Issue by dsquidvicious** [the-hyjal-project/bugtracker#343]
https://classicdb.ch/?quest=309

Issue: Dark Iron Raiders are not despawning after quest failure or after the quest is started again.

How it should work: The Dark Iron Raiders will despawn after quest is failed or after quest is restarted. In the current state an infinite number of Dark Iron Raiders could accumulate if no one kills them but continues to start the quest again and again

**Comment by Gamemechanicwow** [comment]
Fixed - but isn't live on the server yet.

Dark Iron Raiders will now despawn after 25 secs out of combat.
