### ISSUE TITLE
talents tree for druid

### ISSUE THREAD

**Issue by tk4w** [the-hyjal-project/bugtracker#344]
**Describe Your Issue**
cannot spent talents except balance tree

**Steps To Reproduce**

1. i pick "https://classic.wowhead.com/spell=16689/natures-grasp" talent first and could not spent to other trees
2. i unlearn my talents for 1 gold and still could not spent them to other trees
3. 

NPC: https://classic.wowhead.com/npc=
Item: https://classic.wowhead.com/item=
Quest: https://classic.wowhead.com/quest=
Spell: https://classic.wowhead.com/spell=
Object: https://classic.wowhead.com/object=

**Expected Behaviour**

**Comment by GM-Dave-THP** [comment]
Is this still an issue for you? Have you tried deleting your WDB folder?

**Comment by Godmatik** [comment]
This is likely caused by Zygor add-on, just disable it, should fix the issue @tk4w

**Comment by Gamemechanicwow** [comment]
This is a client issue. Most likely an addon as stated above.
