### ISSUE TITLE
Mage spell BLINK does NOT remove stun

### ISSUE THREAD

**Issue by kinpin-bug** [the-hyjal-project/bugtracker#346]
**Describe Your Issue**

Mage spell BLINK does NOT remove stun, when used!
**Steps To Reproduce**

1.tested on two murlocks who used COUGE and stun me. BLINK does NOT remove stun
2. tested on two murlocks who used COUGE and stun me. BLINK does NOT remove stun
3. 

NPC: https://classic.wowhead.com/npc=
Item: https://classic.wowhead.com/item=
Quest: https://classic.wowhead.com/quest=
Spell: https://classic.wowhead.com/spell=1953/blink
Object: https://classic.wowhead.com/object=

**Expected Behaviour**

MAGE spell BLINK should remove stun when used!

**Comment by Gamemechanicwow** [comment]
Gouge is not a stun, but an incapacitate.
