### ISSUE TITLE
Flight Master in Camp Taurajo, Barren

### ISSUE THREAD

**Issue by Nostaglicdude** [the-hyjal-project/bugtracker#347]
**Describe Your Issue**
Currently, the game is on 1.2 patch. There's a flight master in Camp Taurajo which actually did not exist until 1.6 patch.

**Steps To Reproduce**
Flight Paths
Added a Wind Rider Master to Camp Taurajo in The Barrens.
New Horde Flight Paths --
Camp Taurajo in The Barrens <-> Crossroads in The Barrens
Camp Taurajo in The Barrens <-> Thunder Bluff in Mulgore
Camp Taurajo in The Barrens <-> Freewind Post in Thousand Needles

https://wowwiki-archive.fandom.com/wiki/Patch_1.6.0#World_Environment

**Expected Behaviour**
Should not be a flight master in Camp Taurajo until patch 1.6.

**Comment by Daribon** [comment]
will investigate
