### ISSUE TITLE
Blue ring [Seal of Wrynn] is giving the wrong stats (different than tooltip & database)

### ISSUE THREAD

**Issue by JoaoGabrielGama** [the-hyjal-project/bugtracker#350]
**Describe Your Issue**
The item from the Defias questline inside Stormwind, the blue ring [Seal of Wrynn] that should give +3 str +3 agi +4 stam +4 int +3 spr is giving +2 stam + 6 spr. Even though the tool tip shows the correct stats.

**Steps To Reproduce**
1. Do questline finishing at [An Audience with the King] https://classicdb.ch/?quest=396
2. Get the bugged [Seal of Wrynn]

Item: https://classicdb.ch/?item=2933
Quest: https://classicdb.ch/?quest=396

**Expected Behaviour**
[Seal of Wrynn] should have the stats as shown on the its tooltip (+3 str +3 agi +4 stam +4 int +3 spr)

**Comment by Gamemechanicwow** [comment]
Seal of wrynn changes through patches.
Until patch 1.9 its a green item: https://classicdb.ch/?item=2933-0

Your client is currently showing it as a blue item because your client has the item cached. You can delete the contents of your "wdb" folder to show the correct stats.
