### ISSUE TITLE
please fix STEALTH

### ISSUE THREAD

**Issue by codon3** [the-hyjal-project/bugtracker#353]
**Describe Your Issue**
Any level under is detecting me out of stealth from over +5 yards away.... very unreal very terrible very sadge.
SHOULD only detect out when i am directly in front of the target... not on the side which it IS.....please fix this pleaase please.
yes i know MOD, this should NOT be happening without MOD. been playing since 2003 beta.  all my comparison is from real vanilla..   so again,  getting broken out of stealth from levels lower than my self....not how its intended.  only time this SHOULD happen if the target is red or orange or ??..... MOD then helps with detection on these higher mobs. 

**Steps To Reproduce**

1.just chnage how stealth is detected  right now its SUPER broken, im not the only one that is aggreeing here.
2. 
3. 

NPC: https://classic.wowhead.com/npc=
Item: https://classic.wowhead.com/item=
Quest: https://classic.wowhead.com/quest=
Spell: https://classic.wowhead.com/spell=
Object: https://classic.wowhead.com/object=

**Comment by Gamemechanicwow** [comment]
What level is your character - and the mobs that detect you?
What rank of stealth where you using? Different ranks of stealth adds a different baseline modifier. And for each level gained your stealth gets a bit worse against mobs at an equal level.

**Comment by codon3** [comment]
I'm telling you. I'm 12 they are 8-10.  Detecting me from the side where
they can't even see .... It's broken man

**Comment by DaniLaMeux** [comment]
> What level is your character - and the mobs that detect you?
> What rank of stealth where you using? Different ranks of stealth adds a different baseline modifier. And for each level gained your stealth gets a bit worse against mobs at an equal level.

Tested on both Night Elf and Horde rogues, levels below were 1-2 below the player character. Walking anywhere within a 3-5 yard radius will trigger the npc to attack you even if you are in stealth. 

If you are on the side of the npc, they will sometimes turn directly to you and then aggro you if you move even to back away and as of right now, stealthing is not doable at all due to the fact that stealth is being broken before you can even reach the mob.

**Comment by codon3** [comment]
would you be able to hotfix this ? or when can you change it to proper
functioning.

thanks

**Comment by GM-Dave-THP** [comment]
Devs are looking into this.

**Comment by Gamemechanicwow** [comment]
I have made a chart showcasing various stealthdetection ranges with Stealth rank 1 to 4.
Y-axis shows in yards - how far stealth can be detected.
X-axis shows versus opponents within -5 to +5 leveldifference.

![image](https://user-images.githubusercontent.com/2223066/108216458-cc033d80-7132-11eb-8618-8338cd5e08d3.png)

From looking through some old sources - i think the range is accurate.
This one is dated back to feb 2005: http://www.worldofwarcraft-alliance.com/apprentissage/voleur-le-talent-maitre-des-illusions/
By hovering over the links you can see detection range with or without Master of deception. Both players are equal level.

Shadowpanther made similar test on classic:
http://shadowpanther.net/stealthtest.htm

If we take a look, at his first image and try to recreate it on our core - it looks something like this:
Shadowpanther
![image](https://user-images.githubusercontent.com/2223066/108217123-898e3080-7133-11eb-8df2-f420dd6d9676.png)
Hyjal
![image](https://user-images.githubusercontent.com/2223066/108217213-9f9bf100-7133-11eb-9f5b-27500b71d99b.png)
I would say that its pretty close.

Regarding detection from behind and in front. We are using a 180 degree view, which are blizzlike. I can't reproduce creatures detecting me when I am behind the mob. 

I can't find anything wrong with stealth. I would be happy to review any issues - and would appriciate screenshots, videos or sources proving that the current implementation is wrong.

**Comment by codon3** [comment]
That's great. But we are talking about mob aggro. Not player vs player.

It's definitely not correct its very delicate detection. And mob lower then
me are detecting me out of stealth like crazy.

**Comment by codon3** [comment]
Even when you're on the side of a mob or almost behind. It's also
detecting.  And they are 2 levels lower...

**Comment by codon3** [comment]
seems per danielles findings, even the NE  benefit is not working. so something is off.  we cant just let is ride out and wait till we are all 60.   we rely on pick pocket for our livelihood n game.

**Comment by codon3** [comment]
currently, i think when we are 1+ a level or more on a mob. we are not getting the added stealth bonus benefit. its acting as its always at "base line"    talking to druids and rogues in game they also feel its off. 

each level above a mob we are should be +10(3 in classic) stealth level.  currently its 0 or lower than normal.

**Comment by Nostaglicdude** [comment]
I can confirm that. I do not understand how mobs at the same level can see me as if I am not stealthed. I know from playing since 2005.
