### ISSUE TITLE
QUEST - Screecher Spirits AND Testing the Vessel

### ISSUE THREAD

**Issue by Sundorian** [the-hyjal-project/bugtracker#357]
**Describe Your Issue**

When I click on the Yeh'kinya's Bramble for the quest Screecher Spirits all I get in return is "invialid target"
**Steps To Reproduce**

1. Get Quest Screecher Spirits   ID 3520
2. Kill a Rogue Vale Screecher in Feralas
3. Try to use the bramble on the corpse of the victim  Braqnble is ID 10699

NPC: https://classic.wowhead.com/npc=
Item: https://classic.wowhead.com/item=
Quest: https://classic.wowhead.com/quest=
Spell: https://classic.wowhead.com/spell=
Object: https://classic.wowhead.com/object=

**Expected Behaviour**

**Comment by Sundorian** [comment]
ALSO same issue with the quest Testing the vessel from Feralas  ID 3213

**Comment by Sundorian** [comment]
This has now been confirmed by another player as well , Oru.

**Comment by Phoee** [comment]
When can we expect a fix for this, getting really annoying with the item quests. Badlands Reagent Run II also bugged for Alchemists, can't use the vial on the dragons

**Comment by Gamemechanicwow** [comment]
Pushed a fix that solves issues with using items on dead mobs. Its not live on the server yet.
