### ISSUE TITLE
The Essence of Aku'Mai

### ISSUE THREAD

**Issue by Zantu** [the-hyjal-project/bugtracker#358]
**Describe Your Issue**
It is not posseble to pick up crystals. 

**Steps To Reproduce**

1.
2. 
3. 

NPC: https://classic.wowhead.com/npc=12736/jeneu-sancrea
Item: https://classic.wowhead.com/item=16784/sapphire-of-akumai
Quest: https://classic.wowhead.com/quest=6563/the-essence-of-akumai
Object: https://classic.wowhead.com/item=16784/sapphire-of-akumai

**Expected Behaviour**
You should be able to know down the crystals of the walls in the cave, so it opens a loot window, to pick up crystals. 
There are between 1-3 crystals in each.

**Comment by Zantu** [comment]
Everyone else can pick up items. 
I ahve tryed to disable all addons. relog, retake quest. no change.

**Comment by Gamemechanicwow** [comment]
Sounds like a caching issue. Try deleting the contents in your wdb folder.

**Comment by Zantu** [comment]
I have tryed this now. Unfortently this did not help.
Please help here :)

**Comment by Zantu** [comment]
Seems like I have the same issue, even tho i try to log in on a different computer. So I think something deeper is wrong

**Comment by Gamemechanicwow** [comment]
I think we talked in game the other day. Do you still have experience the problems?

I know not being able to loot barrels and crates is often a caching issue, where closing wow and deleting the contents of wdb folder fixes it. I assume the crystals are the same bug.

**Comment by Zantu** [comment]
It's all working perfect now. I love it <3 

Find me in game one of the days. I have a question about pathing :)
