### ISSUE TITLE
Deeprun Rat Roundup - Quest

### ISSUE THREAD

**Issue by Catlynjenner** [the-hyjal-project/bugtracker#359]
**Describe Your Issue**

Level 1 rats which are neutral color should turn friendly (green nameplate) and follow you. Just completed it by clicking on the flute 5 times near a neutral rat. 
**Steps To Reproduce**

1. Pretty self explanatory - click on quest item and watch as it doesn't turn the rat friendly nor does it follow you. Does however allow you to complete the quest and counts towards completion when clicking the flute near a rat
2. 
3. 

NPC: https://classic.wowhead.com/npc= https://classic.wowhead.com/npc=12997/monty ; https://classic.wowhead.com/npc=13016/deeprun-rat
Item: https://classic.wowhead.com/item= https://classic.wowhead.com/item=17117/rat-catchers-flute
Quest: https://classic.wowhead.com/quest= https://classic.wowhead.com/quest=6661/deeprun-rat-roundup
Spell: https://classic.wowhead.com/spell=
Object: https://classic.wowhead.com/object=

**Expected Behavior**

Player should roam around the IF portion of the tram and find rats with neutral nameplates and use the flute to lure them.  Using the quest item flute will then turn the rat to a friendly nameplate and will follow the player around until the quest is completed or once leaving the tram instance.

**Comment by Neto-WoW** [comment]
Need more confirmation on this. I just tested and its working fine. Please reopen ticket with video if you find this issue continuing to happen.

1. Accept Quest
2. Select Rat
3. Use quest Flute
4. Rat is enthralled, aura applied. Turns green and follows.

![image](https://user-images.githubusercontent.com/79717052/111913341-12a2cb00-8a44-11eb-8b58-ca2f9c30131a.png)
