### ISSUE TITLE
Illyanie spawned incorrectly

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#364]
**Describe Your Issue**
Illyanie spawned incorrectly

**Steps To Reproduce**

Spawned incorrectly

https://classic.wowhead.com/npc=4188

**Expected Behaviour**

![image](https://user-images.githubusercontent.com/19539976/108407260-6b036480-721b-11eb-9e62-8f6302b13bb3.png)

This SS from wowhead shows her in front of the cart, her current orientation (facing a wall) does not seem right.

**Comment by NickTyrer** [comment]
This is correct, verified on classic.

**Comment by ratkosrb** [comment]
The area she is spawned in underwent some changes in 1.11, but her position and orientation weren't updated until 2.0, leaving her looking awkward in the final vanilla patches.

**Comment by ratkosrb** [comment]
Here is what the area she is spawned in looked like before 1.11
![WoWScrnShot_021921_140718](https://user-images.githubusercontent.com/35845488/108502725-eae10b80-72bb-11eb-8b96-edc3e2fdda42.jpg)
