### ISSUE TITLE
Rogvar Horde alchemy trainer doesn't train you past 225

### ISSUE THREAD

**Issue by Phoee** [the-hyjal-project/bugtracker#366]
**Describe Your Issue**
Rogvar is supposed to train you to Artisan Alchemy (225-300). He does not currently. 

**Steps To Reproduce**
1. Skill Alchemy to 225
2. Go see Rogvar
3. Check options on his list; no Artisan Alchemy

NPC: https://classic.wowhead.com/npc=1386/rogvar
Item: https://classic.wowhead.com/item=
Quest: https://classic.wowhead.com/quest=
Spell: https://classic.wowhead.com/spell=11611/alchemy#comments
Object: https://classic.wowhead.com/object=

**Expected Behaviour**
Rogvar should train horde alchemists with the required skill to open up to 300

**Comment by Phoee** [comment]
![Rovgar bug](https://user-images.githubusercontent.com/78449431/108574943-92882900-7310-11eb-8e89-1d2582d3c8d5.JPG)

**Comment by Phoee** [comment]
that's with 225 skill talking to him. any fix on this??? is somewhat ridiculous bug

**Comment by Gamemechanicwow** [comment]
What is your level?

**Comment by Phoee** [comment]
42

**Comment by Phoee** [comment]
resolved cos i am retard
