### ISSUE TITLE
Regular Blessings of Kings not generating threat

### ISSUE THREAD

**Issue by YellowRyder** [the-hyjal-project/bugtracker#367]
**Describe Your Issue**

Regular blessings of kings should generate 60 threat per cast, modified by Righteous Fury (total 114 with talents). Currently it generates zero threat. All other regular blessings seem to generate appropriate amounts per my testing today
**Steps To Reproduce**

1. Have someone in your party aggro a mob
2. Spam regular blessings of kings on them
3. Zero threat

https://classicdb.ch/?spell=20217

**Expected Behaviour**

It should generate 60 threat per cast, modified by Righteous Fury. Same reason why greater blessing of kings generates

**Comment by Gamemechanicwow** [comment]
Added threat for bok.
