### ISSUE TITLE
Screecher Spirits

### ISSUE THREAD

**Issue by DaniLaMeux** [the-hyjal-project/bugtracker#368]
**Describe Your Issue**
Unable to use Yeh'kinya's Bramble to collect the Screecher Spirits in Feralas

**Steps To Reproduce**

1. Kill Vale Screecher
2.  Use Bramble
3.  Invalid Target

NPC: https://classic.wowhead.com/npc=
Item: https://classic.wowhead.com/item=10699/yehkinyas-bramble
Quest: https://classic.wowhead.com/quest=3520/screecher-spirits
Spell: https://classic.wowhead.com/spell=
Object: https://classic.wowhead.com/object=

**Expected Behaviour**

Kill Screechers, collect spirits

**Comment by Gamemechanicwow** [comment]
Pushed a fix that solves issues with using items on dead mobs. Its not live on the server yet.
