### ISSUE TITLE
Vendor sells Tome of Fire Blast VII

### ISSUE THREAD

**Issue by Simp-N** [the-hyjal-project/bugtracker#370]
**Describe Your Issue**
The Horde Vendor [Kireena](https://classic.wowhead.com/npc=9636/kireena), at 51,53 in Desolace, appears to sell [Tome of Fire Blast VII](https://classic.wowhead.com/item=8878/tome-of-fire-blast-vii). This doesn't make sense.

**Steps To Reproduce**´
1. Please be horde character and go to 51,53 in Desolace and talk with Kireena.
2. Look on second tab of merchandise.
3. Tome of Fire Blast VII

**Expected Behaviour**
If you look at the Wowhead Classic link for Kireena you can see that she does not sell this tome. She mostly sells trade goods. I'm not even sure if this particular tome does anything. [Fire Blast rank 7](https://classic.wowhead.com/spell=10199/fire-blast) is normally taught by trainers, and while the tome's name is VII, the rank in the description is 3.

![Sorted_WoWScrnShot_210220_140644](https://user-images.githubusercontent.com/75734743/108596757-56dc7600-7387-11eb-9b5c-ec1f508c3ab0.png)

**Comment by NickTyrer** [comment]
Fixed here https://github.com/vmangos/core/pull/1036
