### ISSUE TITLE
Baron Longshore only has one spawn point

### ISSUE THREAD

**Issue by Simp-N** [the-hyjal-project/bugtracker#373]
**Describe Your Issue**
[Baron Longshore](https://classic.wowhead.com/npc=3467/baron-longshore), who is the objective of quest [WANTED: Baron Longshore](https://classic.wowhead.com/quest=895/wanted-baron-longshore) in Barrens, only has one spawn point on Hyjal. He should have two additional spawn points, at two other Freebooter camps.

**Steps To Reproduce**
``SELECT * FROM creature_template``
``INNER JOIN creature ON creature.id = creature_template.entry``
``WHERE creature_template.name = 'Baron Longshore'``

**Expected Behaviour**
He should also spawn at the two freebooter camps located south of his current spawn. These two camps are also where you pick up the objectives for quest [Stolen Booty](https://classic.wowhead.com/quest=888/stolen-booty). Please look at the bottom for screenshots of these two camps.

If you look on the map for [WANTED: Baron Longshore](https://classic.wowhead.com/quest=895/wanted-baron-longshore), you will see three points, which I believe are his spawn points. The map on the page for the actual NPC is a bit more cluttered. You can also see [this clip](https://youtu.be/v0BPUXwqpeg?t=3640) from Joana's vanilla leveling guide (go to about 1:00:40) that the Baron indeed should spawn at other locations than the one on Hyjal. The one in the clip is the southern-most spawn.

I tried getting in-game coordinates for likely spawn for these two places, and they're about 
63,579440116882 49,102431535721
62,624561767752 49,740219116211
which if I can translate into mangos coords correctly is 
position_x: -1704.9830306321505, position_y: -3819.800837140051
position_x: -1748.0735540390056, position_y: -3723.0397674363203

![Fixed_WoWScrnShot_210222_005309](https://user-images.githubusercontent.com/75734743/108643333-74eec700-74aa-11eb-9a8c-e2b635b3086a.jpg)

![Fixed_WoWScrnShot_210222_005352](https://user-images.githubusercontent.com/75734743/108643339-78824e00-74aa-11eb-8dc5-1ea493447a10.jpg)

**Comment by NickTyrer** [comment]
Fixed here https://github.com/vmangos/core/pull/1094
