### ISSUE TITLE
NPCs who should flee at low HP, do not

### ISSUE THREAD

**Issue by Simp-N** [the-hyjal-project/bugtracker#374]
**Describe Your Issue**
I was fighting some Venture Co. NPCs at the Samophlange and I noticed that they did not flee at low hp. They should. I noticed this issue with [Venture Co. Drudger](https://classic.wowhead.com/npc=3284/venture-co-drudger), [Venture Co. Peon](https://classic.wowhead.com/npc=3285/venture-co-peon), [Theramore Marine](https://classic.wowhead.com/npc=3385/theramore-marine) so far.

**Steps To Reproduce**
You can go to their location and start killing them to check if they flee. About 53,11 for Venture Co., and 62,53 for Marines.
However, if I understand vmangos correctly, I believe the following should show you if they flee or not:
``SELECT * FROM creature_template``
``INNER JOIN creature_ai_events ON creature_ai_events.creature_id = creature_template.entry``
``WHERE creature_template.name IN ('Venture Co. Peon', 'Venture Co. Drudger', 'Theramore Marine')``
There should be creature_ai_events with event_type = 2 for each creature.

**Expected Behaviour**
They should flee at low hp. I think it's common for 15% for a lot of NPCs but I wouldn't know the exact value for these ones. To see that they did flee back in vanilla you can watch [this clip from Joana's vanilla guide](https://www.youtube.com/watch?v=NrSdjsrhX0s). Go to 1:03:14 to see him fight Venture Co., and to 3:58:30 for Marines.

There may be more NPCs who should be fleeing at low hp, but are not. I will try and look out for them and report it.

**Comment by NickTyrer** [comment]
fixed here https://github.com/vmangos/core/pull/1142
