### ISSUE TITLE
Serpentbloom subject

### ISSUE THREAD

**Issue by Simp-N** [the-hyjal-project/bugtracker#376]
**Describe Your Issue**
The [quest Serpentbloom](https://classic.wowhead.com/quest=962/serpentbloom), requires you to loot [Serpentbloom items](https://classic.wowhead.com/item=5339/serpentbloom) from the [objects](https://classic.wowhead.com/object=13874/serpentbloom) with same name.

I have three issues regarding this:
First of all, the objects are very, *very* difficult to loot. There's like this one magic pixel where you finally get the golden cogwheel and can loot it. I've had some luck if I put my camera on the floor. It's a bit like the objects are sunken into the ground. Several people in my group had this issue while doing WC.

Secondly, you do not always get the quest item when looting the flowers. In the vmangos database it appears to be a 80% drop chance. This should be 100%. 

Thirdly, when you loot a flower a [Serpentbloom Snake](https://classic.wowhead.com/npc=3680/serpentbloom-snake) should spawn. This works as intended on Hyjal, however if you kill the snake you can loot it, which is wrong. See screenshot at bottom.

**Steps To Reproduce**
1. Grab the quest from Apothecary Zamah in Thunder Bluff, then head to Wailing Caverns.
2. Find a flower and wave your cursor over it and you should notice it's almost like you don't have the quest because no cogwheel appear.
3. Once you're finally able to loot it, kill the snake that appears and it should glimmer and you should be able to loot it.
4. For the second issue, this should show you it only has an 80% drop chance:
``SELECT item_template.name, gameobject_template.name, gameobject_loot_template.ChanceOrQuestChance FROM item_template``
``INNER JOIN gameobject_loot_template ON gameobject_loot_template.item = item_template.entry``
``INNER JOIN gameobject_template ON gameobject_loot_template.entry = gameobject_template.data1``
``WHERE item_template.name = 'Serpentbloom'``

**Expected Behaviour**
First issue: they should be a lot more easy to loot. Just having the cursor over the model in the game should be enough.

Second issue: the drop rate should be 100%, as in you always get the quest item when looting a flower. [This Allakhazam link](https://web.archive.org/web/20050527200327/http://wow.allakhazam.com/db/item.html?witem=5339) (may 2005) shows the drop rate at 98%.

Third issue: they should not be lootable. At least they aren't in Classic. They're critters like Sheep, Barrens Gazelles, and such.
![Sorted_WoWScrnShot_210215_215620](https://user-images.githubusercontent.com/75734743/108647976-4c6ec900-74ba-11eb-9d88-f320eb7c4b26.png)

**Comment by monoeko** [comment]
me and all 4 other people in our party experienced the same issue with there being a very, very small clickable area. as far as i can tell it is like this for everyone. came here to report the same issue.

**Comment by NickTyrer** [comment]
fixed here https://github.com/vmangos/core/pull/1097
