### ISSUE TITLE
Gnomeregan event for Grubbis boss

### ISSUE THREAD

**Issue by Brodda** [the-hyjal-project/bugtracker#378]
**Describe Your Issue**
Talking to the npc Blastmaster Emi Shortfuse doesn't start the cave event for Grubbis.

https://classic.wowhead.com/npc=7998/blastmaster-emi-shortfuse
https://classic.wowhead.com/npc=7361/grubbis

**Expected Behaviour**
Emi should walk to the caves and mobs should spawn in them.

**Comment by Neto-WoW** [comment]
Hi there. I was unable to reproduce this bug. Emi starts the quest as intended. Can you please provide more evidence (video) of it not working and reopen ticket?

![image](https://user-images.githubusercontent.com/79717052/111913701-b2148d80-8a45-11eb-9dc3-f9770e94a431.png)
