### ISSUE TITLE
Arcanist Doan does not cast his "Righteous Fire" spell

### ISSUE THREAD

**Issue by Simp-N** [the-hyjal-project/bugtracker#379]
**Describe Your Issue**
I did SM lib twice today and Arcanist Doan, the final boss, never cast his dangerous Fire Nova spell. Doan is supposed to bubble, becoming immune, and during that time cast his powerful fire spell. According to [Wowpedia page on Doan](https://wow.gamepedia.com/Arcanist_Doan?oldid=326929) (november 2006), this happens when he reaches 50% HP. Now on Hyjal, he does bubble, become immune and yells "Burn in Righteous Fire!", but he simply never casts the fire spell.

Also, I don't think he cast Polymorph, Silence or Arcane Explosion either during the fight, but that may have been me not paying attention, or the priest having very good reactions. If you can, please check if he casts these during the fight. According to the wowpedia page he should Polymorph the tank.

**Steps To Reproduce**
1. Go to the last boss in SM Lib.
2. Fight him, eventually he should bubble.
3. Observe that he doesn't cast the fire spell.

**Expected Behaviour**
He should cast his spell during his bubble. I am unsure how strong it hits, but [a comment on his Wowhead page](https://classic.wowhead.com/npc=6487/arcanist-doan#comments:id=2905085), from 2005, says that it hits for 900 damage. This spell can be avoided by running away from him, or hiding behind a wall. [This](https://www.wowhead.com/spell=9435/detonation) might be the spell that Doan uses.

[Here](https://youtu.be/aq9zwZpEIsk?t=140) is a recording from november 2006 of the Doan fight. Awful music, turn of sound before you watch it.

**Comment by ratkosrb** [comment]
He always casts the fire aoe after the bubble in my tests.

**Comment by Neto-WoW** [comment]
Tested and working as intended. If you can reopen and supply video evidence, that would be great. Maybe we're doing something differently.
