### ISSUE TITLE
Willix the Importer

### ISSUE THREAD

**Issue by Brodda** [the-hyjal-project/bugtracker#382]
**Describe Your Issue**
Willix despawns at the end of the escort without completing the escort quest.

https://classic.wowhead.com/quest=1144/willix-the-importer
https://classic.wowhead.com/npc=4508/willix-the-importer

**Expected Behaviour**
Quest should become completed at the end of the escort next to Razorfen Kraul portal.

**Comment by Neto-WoW** [comment]
Unable to reproduce.

![image](https://user-images.githubusercontent.com/79717052/111914150-33b8eb00-8a47-11eb-9696-d0b7cbd5c579.png)

Please provide a video if possible upon experiencing this again.
