### ISSUE TITLE
[Question] Do Rares are meant to sometimes drop no loot ?

### ISSUE THREAD

**Issue by Hey0001** [the-hyjal-project/bugtracker#387]
Hi, I just wanted to know if it's ok that sometimes Rares mob don't loot anything please ?

It happens to me and few people on the server.

Thank you!

**Comment by PabloMB95** [comment]
I don't think a bugtracker is the best place to ask those questions. Close this report and ask in discord, Im sure they will happily answer that question.

**Comment by GM-Dave-THP** [comment]
If you suspect a bug with loot please provide the mob name, ID & loot it should drop and we will look into it further.
