### ISSUE TITLE
Burning Exiles can drop quest item that they shouldn't

### ISSUE THREAD

**Issue by Simp-N** [the-hyjal-project/bugtracker#389]
**Describe Your Issue**
[Burning Exiles](https://classic.wowhead.com/npc=2760/burning-exile), the firemen in Arathi Highlands, can drop the quest item [Burning Key](https://classic.wowhead.com/item=4483/burning-key), which they shouldn't do. The key is part of the quest [Stones of Binding](https://classic.wowhead.com/quest=651/stones-of-binding), and is looted from a stone that the firemen are guarding.

**Steps To Reproduce**
``SELECT creature_template.name, item_template.name, creature_loot_template.ChanceOrQuestChance FROM creature_template``
``INNER JOIN creature_loot_template ON creature_loot_template.entry = creature_template.loot_id``
``INNER JOIN item_template ON item_template.entry = creature_loot_template.item``
``WHERE creature_template.name LIKE ('%Exile%') AND item_template.name LIKE ('%Key%')``

This should show you that the Burning Exiles have a 0,06% chance to drop the key, and also that you don't even have to have the quest in order for the key to drop. This should also show you that the other exiles, [Cresting](https://classic.wowhead.com/npc=2761/cresting-exile) and [Thundering](https://classic.wowhead.com/npc=2762/thundering-exile), has no issue with "their" keys.

**Expected Behaviour**
The Burning Exiles should have the Burning Key removed from their loot table. 

The key should only be lootable from the stone that they are guarding, and that portion works fine.

**Comment by NickTyrer** [comment]
Fixed here https://github.com/vmangos/core/pull/1036
