### ISSUE TITLE
gizelton caravan in desolace also not working properly

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#39]
**Describe Your Issue**
gizelton caravan in desolace also not working properly. bugs out in the middle of mannoroc covern and not moving any further
"Bodyguard for Hire" and "Gizelton Caravan" are the specific quest names

**Steps To Reproduce**

1.
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected Behavior**

**Comment by Gamemechanicwow** [comment]
https://github.com/vmangos/core/commit/71f44965b1f5d531a90c81b9ae29d8291d5d8bab

**Comment by Nolin7777** [comment]
Fixed on new fork
