### ISSUE TITLE
Login probs

### ISSUE THREAD

**Issue by ramiobomb1998** [the-hyjal-project/bugtracker#393]
**Describe Your Issue**
Hello!

I signed up today into the server and changed the code in realmlist.wtf and tried to login and it says my info is incorrect. I tried both WoW versions (1.12 and 1.12.1). While it seems like other servers do read my login info, I even tried a password change on the website, and download the realmlist.wtf from the website.

**Steps To Reproduce**

1. Change to "set realmlist logon.hyjal.org" and save.
2. Enter wow and enter the info I signed with into the website.
3. Play.

**Expected Behaviour**
1. Change to "set realmlist logon.hyjal.org" and save.
2. Enter wow and enter the info I signed with into the website.
3. Play.

Thank you and kind regards!

**Comment by GM-Dave-THP** [comment]
Did you verify your email account?

**Comment by ramiobomb1998** [comment]
I did not receive one.

**Comment by ramiobomb1998** [comment]
I did not receive the mail on the tabs I usually use, but now I found it. Thanks!
