### ISSUE TITLE
Gnomish-net-o-matic-projector

### ISSUE THREAD

**Issue by DaniLaMeux** [the-hyjal-project/bugtracker#398]
**Describe Your Issue**
Since last restart, Gnomish-net-o-matic-projector upon logging in nets you in place. When taking it off and logging out and back in again, same thing happens. Could be character related or item related. But no additional reports of this happening.

**Steps To Reproduce**

1. Equip Gnomish-net-o-matic-projector
2.  Log out
3. Log in
4. You will be netted

https://classic.wowhead.com/item=10720/gnomish-net-o-matic-projector

**Expected Behaviour**
Not net you on login

**Comment by Neto-WoW** [comment]
Could not reproduce. Likely an issue with your character. Please ask a GM to check your in game auras via ticket.

**Comment by Dengesiz07** [comment]
This is also happening to me at every logon. Started  happening after using net-o-matic and I was also caught by it.
