### ISSUE TITLE
in shadowmeld it only takes you out of stealth the moment your shot hits - when you get in combat

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#4]
**Describe Your Issue**
in shadowmeld it only takes you out of stealth the moment your shot hits - when you get in combat
afaik in classic its supposed to take you out ofs tealth instantly

**Steps To Reproduce**

1.
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected Behavior**
https://wowwiki.fandom.com/wiki/Patch_1.10.0
"Stealth and Invisibility effects will now be canceled at the beginning of an action (spellcast, ability use etc...), rather than at the completion of the action."
it wouldnt bother me if you kept that in though

**Comment by Nolin7777** [comment]
Mechanic changes are tied to client progression.
This is implemented and works correctly if compiling pre-1.10 core.
