### ISSUE TITLE
bubble fissures not refilling breath in desolace

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#40]
**Describe Your Issue**
bubble fissures not refilling breath in desolace

**Steps To Reproduce**

1.
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected Behavior**

**Comment by Nolin7777** [comment]
Location?

**Comment by GM-Dave-THP** [comment]
#84 has further details
