### ISSUE TITLE
Innkeepers set hearthstone spell is blocked by LOS

### ISSUE THREAD

**Issue by High-Speed-Dirt** [the-hyjal-project/bugtracker#402]
**Describe Your Issue**

I spoke with the innkeeper at Nijels Point to set my hearth stone to Nijels point.  After a round of questing I used my hearthstone and much to my surprise I was returned to Ironforge.  I checked my bag and alas my hearthstone still said Ironforge.  I flew back to Nijels point and asked the innkeeper to set my hearth stone to Nijels Point again and I saw the innkeeper make the animation but that is when I noticed the usual blue sparkles and "wooshing noise" did not happen.  I jumped up on the counter and got right beside the innkeeper and asked again and this time the process worked.   I think there may be a LOS issue with gnomes when we are standing behind the counter of the Inn.  I was able to replicate this same issue with the innkeeper in Booty Bay.

**Steps To Reproduce**

1. Goto Nijels point and ask the innkeeper to make this your home while standing behind the counter.
2. Fail miserably.
3. Jump up on counter and get right beside the innkeeper.  Repeat step one with success.

NPC: https://classicdb.ch/?npc=11103

**Expected Behaviour**

When you speak with an innkeeper and ask her to make a inn your home, she should do that, regardless of how tall you are, as long as you are within conversation range.

**Comment by ratkosrb** [comment]
I am not able to LoS her. The vase and the globe are both too far to be able to talk to her.
