### ISSUE TITLE
Black Widow Band doesn't show correct information 

### ISSUE THREAD

**Issue by Lakanman** [the-hyjal-project/bugtracker#405]
**Describe Your Issue**
The ring Black Widow Band which drop from the rare spawn spider Leech Widow in the cave Thelgen Rock in Wetlands doesn't show the correct info. It only says +7 Intellect. The correct status is +7 Intellect, -5 Stamina.  It still works so you get -5 stamina because you get -5 stamina when you put it on.

NPC: https://classic.wowhead.com/npc=1112/leech-widow
Item: https://classic.wowhead.com/item=6199/black-widow-band

**Expected Behaviour**

![WoWScrnShot_030221_125751](https://user-images.githubusercontent.com/79947354/109731141-0355fd80-7bbb-11eb-8277-3c0fa749a561.jpg)
![WoWScrnShot_030221_125754](https://user-images.githubusercontent.com/79947354/109731154-094bde80-7bbb-11eb-92bb-fabedb1ce6a1.jpg)
![WoWScrnShot_030221_125801](https://user-images.githubusercontent.com/79947354/109731170-0e109280-7bbb-11eb-941c-bed723763f58.jpg)

**Comment by GM-Dave-THP** [comment]
Hi,

Please can you delete your WDB folder in the wow directory and check this item again.

Thanks

**Comment by Lakanman** [comment]
Now it is correct

![image](https://user-images.githubusercontent.com/79947354/109902682-13450e80-7c9b-11eb-9b22-38e1665d6230.png)

**Comment by Neto-WoW** [comment]
Resolved.
