### ISSUE TITLE
Goblin Rocket Helmet not working

### ISSUE THREAD

**Issue by YellowRyder** [the-hyjal-project/bugtracker#408]
**Describe Your Issue**

Goblin rocket helmet doesn't cause you to charge. The stun and self-stun still happen, but your character doesn't move at all.

**Steps To Reproduce**

1. Use goblin rocket helmet

https://classicdb.ch/?item=10588

**Expected Behaviour**

Rocket helmet should cause your character to charge

**Comment by YellowRyder** [comment]
This might also affect Horned Viking Helmet. Cannot test myself.

https://classicdb.ch/?item=9394

**Comment by ratkosrb** [comment]
The issue happens when the content patch is set to 1.2, but the client is newer.
Fixed here: https://github.com/vmangos/core/commit/91be6536091da81310ba545edc4ee2966d6789a6
