### ISSUE TITLE
AH sales in Mailbox not showing picture

### ISSUE THREAD

**Issue by Woozythebear** [the-hyjal-project/bugtracker#411]
**Describe Your Issue**
When you sell something on the AH and go to get it from the mailbox it does not show a picture as shown here https://imgur.com/ny2HYU1

**Steps To Reproduce**

1. List item on AH
2. Sell item on AH
3. Open mailbox to collect your money

NPC: https://classic.wowhead.com/npc=
Item: https://classic.wowhead.com/item=
Quest: https://classic.wowhead.com/quest=
Spell: https://classic.wowhead.com/spell=
Object: https://classic.wowhead.com/object=

**Expected Behaviour**

**Comment by Gamemechanicwow** [comment]
Fixed after next restart.
