### ISSUE TITLE
PET BUG 

### ISSUE THREAD

**Issue by rasbal123** [the-hyjal-project/bugtracker#412]
Hello, whenever a pet gets feared / intimidated , it runs away but stays stuck in the position. 

The pet does not return to the mob until it is dead, you have to click with hand for the pet to run back to you, otherwise it will be stuck in a position and not attack or anything. Pretty useless. 

I have tried using different pets and all does the same.

The pet should run back to the target automatically after the fear / intimidation effect has worn off. 

Please fix it.

**Comment by ratkosrb** [comment]
https://github.com/vmangos/core/commit/246c051a2b1f85e0b1076079e0d5e97cf926e611
