### ISSUE TITLE
All Along the Watchtowers bugged

### ISSUE THREAD

**Issue by AveDominiInferni** [the-hyjal-project/bugtracker#414]
**Describe Your Issue**
Can't mark the Tower Three in the quest "All Along the Watchtowers". I tried abandoning it and trying again but it didn't fix it.

**Steps To Reproduce**
1. Take the quest "All Along the Watchtowers"
2.  Try to mark the "Tower Three"

NPC: https://classic.wowhead.com/npc=10904/andorhal-tower-three
Item: https://classic.wowhead.com/item=12815/beacon-torch
Quest: https://classic.wowhead.com/quest=5097/all-along-the-watchtowers

**Expected Behaviour**
Using the beacon torch in the Tower Three should complete the objective.

**Comment by Neto-WoW** [comment]
Wasn't able to reproduce unfortunately. I also tried all towers, and all are working as intended.

![image](https://user-images.githubusercontent.com/79717052/111009795-9680f700-8362-11eb-8f86-d3dbc4ff4af0.png)

**Comment by AveDominiInferni** [comment]
I used the torch inside the tower, didn't know it was possible to use it outside. Maybe that's why I couldn't do it.
