### ISSUE TITLE
Mage 30 Quest Chain Missing Requirements

### ISSUE THREAD

**Issue by Simp-N** [the-hyjal-project/bugtracker#415]
**Describe Your Issue**
At level 30 mages get a quest that sends them to Dustwallow Marsh to begin a chain to get a wand. However, some of the quests in the chain seem to be missing previous quests as requirements, making you able to skip one part.

The quests involved in this chain are:
[Journey to the Marsh](https://classic.wowhead.com/quest=1947/journey-to-the-marsh)
[Hidden Secrets](https://classic.wowhead.com/quest=1949/hidden-secrets)
[Get the Scoop](https://classic.wowhead.com/quest=1950/get-the-scoop)
[Rituals of Power](https://classic.wowhead.com/quest=1951/rituals-of-power)
[Items of Power](https://classic.wowhead.com/quest=1948/items-of-power)
[Mage's Wand](https://classic.wowhead.com/quest=1952/mages-wand)

**Steps To Reproduce**
``SELECT entry, PrevQuestID, NextQuestInChain, title FROM quest_template``
``WHERE entry IN (1948, 1951, 1950, 1949, 1947, 1952)``

Looking at the results, you should see that _Items of Power_ has no quest requirement. Also, the final quest, _Mage's Wand_, only seem to have _Rituals of Power_ as requirement. _Items of Power_ seem to have fallen out of the chain.

**Expected Behaviour**
If you look on Wowhead Classic, each quest should require the previous one in the list above. Meaning:
Journey to the Marsh -> Hidden Secrets -> Get the Scoop -> Rituals of Power **-> Items of Power ->** Mage's Wand
*edit*
I looked on my screenshots from Classic, and I found that I did have both Rituals of Power and Items of Power at the same time, so the chain from Wowhead Classic is probably incorrect.
*/edit*

However, I read some comments on [Thottbot ](https://web.archive.org/web/20070417130641/http://www.thottbot.com/q1952) that suggest that you get both _Items of Power_ and _Hidden Secrets_ after the initial breadcrumb quest. And if following that, the chain should be something like this:

Journey to the Marsh -> Hidden Secrets -> Get the Scoop -> Rituals of Power -> Mage's Wand
Journey to the Marsh **-> Items of Power --------------------------------------->** Mage's Wand

> To get the wand there are 2(yes, TWO) parts: Visiting Magus Tirth and getting his book from the Scarlet Monastery AND getting jade and charged bramble (from Witherbark Trolls in Arathi Highlands).  After you turn in BOTH quests, Tabetha will have a new quest

> u get 2 quests from Tabetha after u hand in the quest u got from a mage trainer. 

> get the mage quest from mage trainer in org.
> 
> find tabetha. 46,57 dustwallaoroo (i fergit the name, fly to camp taj then book it southeast)
> 
> get new quests.
> 
> go to shimmering flats, talk to dude by the race track (read yer quests!). find the chicken, he's by the race tower. go back to tabetha.
> 
> go to arathi highlands. go to the far east side by the lake, kill the trolls and git yer stix! (read the letter she gives you)
> 
> go to circle of outer binding (bring a friend if yer low 30 like me) use the sticks in the center rock, open the rod, get the thingy inside of it.
> 
> buy a Jade. borrow a jade. steal a jade. just git yer hands on a jade.
> 
> go to SM (trisfal glades, northeast of undercity.)
> get a crew together and rox the library. in the long hall before the boss there is a book you can open on the wall. do it. git yer book fer tabetha.
> 
> go to tabetha. git yer wand.
> you have a choice. frost, arcane, fire... 

> I got the quest, A Journey to the Marsh, from the Mage trainer in Stormwind at level 30. The quest is to basically talk to Tabetha in Dustwallow Marsh.  She is only a short distance due north from the "E" in Stonemaul Ruins on the map.  Once there, she gives you two quests, Hidden Secrets and Items of Power.

**Comment by NickTyrer** [comment]
Fixed here https://github.com/vmangos/core/pull/1094
