### ISSUE TITLE
Vorsha the Lasher Brazier Bug

### ISSUE THREAD

**Issue by Simp-N** [the-hyjal-project/bugtracker#416]
**Describe Your Issue**
In the quest [Vorsha the Lasher](https://classic.wowhead.com/quest=6641/vorsha-the-lasher) you have to escort an orc, and then click a brazier to start an event where you have to fight off mobs. However, when I did this on Hyjal the brazier seemed bugged. I couldn't click it to start the event. There was a golden cogwheel as if I could, but the event did not start when I tried. Also, the brazier appeared to change between lit and unlit all the time, even if I'm not clicking it. Eventually I gave up. [Here's a video of it.](https://streamable.com/fq17p2)

I tried to do the quest later, this time in a group, and now the brazier appeared to work.

**Steps To Reproduce**
1. Please reach level 20, and go to 12,34 in Ashenvale and accept the quest from [Muglash](https://classic.wowhead.com/npc=12717/muglash).
2. Escort him to his brazier.
3. When he tells you to put out the brazier, try using it. I am not sure what really caused this brazier to bug out.

I think [this](https://classicdb.ch/?object=178247) is the brazier object.

**Expected Behaviour**
The brazier should be clickable after Muglash's prompt, and using it should start the event.

**Comment by ratkosrb** [comment]
It seems the Brazier was already extinguished when u got there, but I'm not sure how that can happen.

**Comment by RainElysium** [comment]
> It seems the Brazier was already extinguished when u got there, but I'm not sure how that can happen.

It's not resetting after a player uses it. I've reproduced and bug fix incoming!

**Comment by Neto-WoW** [comment]
Issue was that there was nothing resetting the brazier after use so the state stayed as use. I tried fixing this in the db however it wouldn't reset the gob. Quest start is handled in the db, and ensuring the gob resets is handled in the core now.

**Comment by ratkosrb** [comment]
The object is reset when the quest is accepted.
![Untitled](https://user-images.githubusercontent.com/35845488/111486799-75dce680-8740-11eb-90ec-d5d072f9032a.jpg)

**Comment by Neto-WoW** [comment]
> The object is reset when the quest is accepted.
> ![Untitled](https://user-images.githubusercontent.com/35845488/111486799-75dce680-8740-11eb-90ec-d5d072f9032a.jpg)

Yes that enables the brazier however it never resets back upon quest start after the first completion. I tried adding in the opposite to quest_end_scripts to either respawn or change GO state back to original, however the db is having none of it. GOB states are always finicky, I find.

**Comment by Simp-N** [comment]
I saw somebody on Hyjal Phoenix today who tried to do this quest and it seems to have bugged in the same way it did for me when I reported this problem, so it may not be fixed. The brazier flashed like in the video and they could not click to start the event. @Neto-WoW
