### ISSUE TITLE
Mana Surge Corpse Linger

### ISSUE THREAD

**Issue by Simp-N** [the-hyjal-project/bugtracker#417]
**Describe Your Issue**
In the mage [quest Mana Surge](https://classic.wowhead.com/quest=1957/mana-surges), you have to befeat twelve enemy [NPC Mana Surge](https://classic.wowhead.com/npc=6550/mana-surge). These enemies begin spawning as you start the quest. When they die, they should despawn immediately. However, on Hyjal their corpses linger. This is a very minor issue by itself but on Hyjal they are also lootable, dropping some silver, which is worth fixing.

**Steps To Reproduce**
1. Be a level 35 Mage and compelte the chain for Mana Surge.
2. Start Mana Surge and wait for one to spawn outside the house.
3. Kill it, and you should see it can be looted, glimmering, and that the corpse lingers.

**Expected Behaviour**
The corpse should despawn immediately upon dying. An alternative fix is to make it so it doesn't drop anything.

[Here's a video](https://www.youtube.com/watch?v=KBL7BCrqe2w) from February 2007 (TBC admitedly), showing that they despawn immediately. You can also look on Mana Surge's page on [Wowhead Classic](https://classic.wowhead.com/npc=6550/mana-surge) and [Allakhazam (May 2006)](https://web.archive.org/web/20060526223357/http://wow.allakhazam.com/db/mob.html?wmob=6550) and see that there is no loot listed.

**Comment by ratkosrb** [comment]
https://github.com/vmangos/core/commit/32fc31e66b3ea86b97dffbeb887f049c679afa80
