### ISSUE TITLE
Blasta Lasta Buffs Stack

### ISSUE THREAD

**Issue by Simp-N** [the-hyjal-project/bugtracker#418]
**Describe Your Issue**
In Blasta Lasta there are five quests that reward you with buffs that increase each stat for an hour, and a consumable which gives the same effects. These five quests are:
[A Boar's Vitality](https://classic.wowhead.com/quest=2583/a-boars-vitality)
[Snickerfang Jowls](https://classic.wowhead.com/quest=2581/snickerfang-jowls)
[The Basilisk's Bite](https://classic.wowhead.com/quest=2601/the-basilisks-bite)
[The Decisive Striker](https://classic.wowhead.com/quest=2585/the-decisive-striker)
[Vulture's Vigor](https://classic.wowhead.com/quest=2603/vultures-vigor)

Please also note that there are repeatable versions of these quests, but I dont think you get the buff from the quest turn in of them: 
[Spirit of the Boar](https://classic.wowhead.com/quest=2584/spirit-of-the-boar)
[Rage of Ages](https://classic.wowhead.com/quest=2582/rage-of-ages)
[Infallible Mind](https://classic.wowhead.com/quest=2602/infallible-mind)
[Salt of the Scorpok](https://classic.wowhead.com/quest=2586/salt-of-the-scorpok)
[Spiritual Domination](https://classic.wowhead.com/quest=2604/spiritual-domination)

On Hyjal you can stack all five of these buffs if you turn in all five quests at the same time. This shouldn't be possible. The buffs should replace each other, meaning that if you turn in all five, you only get one buff, whichever one you turned in last.

The five buffs are: 
[Spirit of Boar](https://classic.wowhead.com/spell=10668/spirit-of-boar)
[Rage of Ages](https://classic.wowhead.com/spell=10667/rage-of-ages)
[Infallible Mind](https://classic.wowhead.com/spell=10692/infallible-mind)
[Strike of the Scorpok](https://classic.wowhead.com/spell=10669/strike-of-the-scorpok)
[Spiritual Domination](https://classic.wowhead.com/spell=10693/spiritual-domination)

**Steps To Reproduce**
1. Be at least level 45.
2. Gather the items for the quests. For all five quest you need: 14 [Vulture Gizzard](https://classic.wowhead.com/item=8396/vulture-gizzard), 11 [Basilisk Brain](https://classic.wowhead.com/item=8394/basilisk-brain), 6 [Blasted Boar Lung](https://classic.wowhead.com/item=8392/blasted-boar-lung), 6 [Scorpok Pincer](https://classic.wowhead.com/item=8393/scorpok-pincer), 5 [Snickerfang Jowls](https://classic.wowhead.com/item=8391/snickerfang-jowl).
3. Turn in all five quests, and you should end up with all five buffs.

**Expected Behaviour**
Whenever you turn in any of these quests, the new buff should replace any old one you had of these buffs. Here's [Joana's Vanilla Guide](https://youtu.be/Up_ThglOopY?t=6005). At 1:40:05 you can see him turn in all five quests, and you can see that the buffs dont stack. In the written portion of his guide he explicitly mentions that you should turn in The Decisive Striker last so that you end up with the agility buff.

Furthermore I will list some comments from Wowhead Classic pages for these quests where people mention that the buffs do not stack.

[January 2006](https://classic.wowhead.com/quest=2604/spiritual-domination#comments:id=2785065)
> - none of the blasted lands buffs stack with each other

[August 2006](https://classic.wowhead.com/quest=2584/spirit-of-the-boar#comments:id=2742435)
> BUT! If you do two quests that this guy offers, and turn them in at the same time, the last buff will replace the previous. In other words, you can't have Sta +25 and Str +25 at the same time.

[March 2006](https://classic.wowhead.com/quest=2586/salt-of-the-scorpok#comments:id=2781165)
> Take note that you can only get one of these nice buffs at a time.  Dunno about if you put the buffs on yourself when you use the items.  But when you turn the quest in, and he buffs you, you get one buff.  So if you decide to turn in a whole bunch of quests at once for the items and xp... choose your favorite buff for last.  =)

[December 2006](https://classic.wowhead.com/quest=2585/the-decisive-striker#comments:id=2758762)
> The buffs do not stack.  If you have a stamina buff from a previous quest, do not turn in for agility.  The earlier buff will be replaced by the new one.

**Comment by ratkosrb** [comment]
https://github.com/vmangos/core/commit/2f230a807138a3ce24ee9fad3526646fe9b1f020
