### ISSUE TITLE
rezzing at a spirit healer that is far away from your body brings you back to life at the healer closest to your body

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#42]
**Describe Your Issue**
rezzing at a spirit healer that is far away from your body brings you back to life at the healer closest to your body
though that might be intentional
**Steps To Reproduce**

1.
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected Behavior**

**Comment by kodolol** [comment]
Can confirm this happens but needs testing in classic.
