### ISSUE TITLE
Hazzali Parasite can be looted

### ISSUE THREAD

**Issue by Simp-N** [the-hyjal-project/bugtracker#420]
**Describe Your Issue**
[Hazzali Parasite](https://classic.wowhead.com/npc=7769/hazzali-parasite) spawns whenever any of the Hazzali Silithid in southern Tanaris is killed. These parasites die in one hit. On Hyjal they can be looted, and drop some silver.

**Steps To Reproduce**
1. Go to around 56,70 in Tanaris.
2. Kill any of the silithid. Kill the parasites that spawn when they die.
3. Observe that the parasites can be looted, glittering, and that they drop some silver.

**Expected Behaviour**
The Parasites should not drop anything. If you look on their [Wowhead Classic page](https://classic.wowhead.com/npc=7769/hazzali-parasite#comments) you will see that no loot or silver is listed as dropping. There are also comments about how they don't drop anythng.

Furthermore, you can also watch [Joana's Vanilla Guide](https://youtu.be/KO1iKRoKDyI?t=7440), at 2:04:00 where he begins fighting these silithid. At 2:07:05, 2:11:20, 2:11:44 and 2:14:04 you can see they are not glittering.

**Comment by NickTyrer** [comment]
Fixed here https://github.com/vmangos/core/pull/1097
