### ISSUE TITLE
Mobs who flee at low HP, but shouldn't

### ISSUE THREAD

**Issue by Simp-N** [the-hyjal-project/bugtracker#421]
**Describe Your Issue**
There are two mobs who flee at low HP on Hyjal, but they shouldn't.

The mobs I have noticed this with are:
[Bloodscalp Berserker](https://classic.wowhead.com/npc=597/bloodscalp-berserker)
[Marsh Flesheater](https://classic.wowhead.com/npc=751/marsh-flesheater)

These mobs also enrage when at low HP, which makes them fleeing quite ironic I think. It also makes them enraging pointless since they'll flee shortly after that.

**Steps To Reproduce**
1. Go fight these mobs. Bloodscalp around 20,13 STV. Flesheater around 90,72 Swamp of Sorrow.
2. Get them below 20% HP or so.
3. Observe as they flee.

**Expected Behaviour**
They simply should not flee. Referring to Joana's Vanilla Guide, like I always do, I will link to some clips where he fights these mobs and you will see they do not flee.
[Bloodscalp Berserker](https://youtu.be/t9-p76s-G5k?t=5875):
1:37:55
1:38:45
1:39:30
1:43:30
[Marsh Flesheater](https://youtu.be/s14G2JdLh6Y?t=7193):
1:59:53
2:00:33
2:03:18
2:03:50
and so on.

It is possible that more mobs flee on Hyjal, while they actually shouldn't but these are the ones I've noticed so far. I will report more if I find them.

**Comment by NickTyrer** [comment]
fixed here https://github.com/vmangos/core/pull/1097
