### ISSUE TITLE
Hunter pet follows far behind instead of running alongside you

### ISSUE THREAD

**Issue by michaeltgarrard** [the-hyjal-project/bugtracker#422]
Not only does this cause problems with pulling aggro when trying to path between mobs, but it also ruins the immersive feeling that comes from being a hunter that has a pet that runs just about alongside (or very closely behind) with you out in the world. You don't even see your pet when running, unless you zoom out a ton.

(wanted to post this for devs to see before re-launch. it is a pretty big factor as to whether i will play or not, as hunter is the only class i want to play, and this just kills it for me.)

edit: here are some references (URLs to vanilla-era videos showing pet pathing in relation to the hunter):

https://youtu.be/6c1e-F_FHjg?t=247 (from 4:07 - 4:11) - Here is an example of the hunter and his pet following very closely. The head of the cat is basically just at the left side of the feet of the hunter as they run together. On pserver the cat would not be nearly that close. It would be trailing behind with a pretty reasonable gap between them.

https://youtu.be/RNfh6jUIPqA?t=482 (from 8:02 - 8:05) - Here's another example. If you recreated that situation on the pserver, and strafed to the right like that, the pet would likely barely even move if at all. In this video, the pet follows very closely and ends up being pretty much glued to the hunter's left side. There is a lower tolerance for the pet's trailing distance from the hunter, whereas the pserver it looks/feels more like a loose rubber band where the pet ends up following with a pretty big gap between them.

**Comment by ratkosrb** [comment]
I did some quick changes to the follow movement code, is this more like what it should look like?
https://streamable.com/sgs26p

**Comment by michaeltgarrard** [comment]
> 
> 
> I did some quick changes to the follow movement code, is this more like what it should look like?
> https://streamable.com/sgs26p

Yes! That looks amazing. I know it may seem trivial to some, but to me this is huge, and makes a world of difference. This makes me so excited to start playing a hunter come the 27th. Thank you for the quick work, you are awesome!
