### ISSUE TITLE
Breath bar . There is no breath bar when you are underwater and you dont lose hp even if you stay  for a long time

### ISSUE THREAD

**Issue by serioussalvi** [the-hyjal-project/bugtracker#424]
**Describe Your Issue**

**Steps To Reproduce**

1.
2. 
3. 

NPC: https://classic.wowhead.com/npc=
Item: https://classic.wowhead.com/item=
Quest: https://classic.wowhead.com/quest=
Spell: https://classic.wowhead.com/spell=
Object: https://classic.wowhead.com/object=

**Expected Behaviour**

**Comment by Gamemechanicwow** [comment]
Fixed. Not yet live on ptr.
