### ISSUE TITLE
Wandering Skeleton - No Dalson Outhouse Key

### ISSUE THREAD

**Issue by Halahlstrom** [the-hyjal-project/bugtracker#430]
**Describe Your Issue**
The wandering skeleton wont drop the key to the outhouse

**Steps To Reproduce**
1.  Kill wandering skeleton numerous times
2.  Witness no key dropping
3.  

NPC: https://classic.wowhead.com/npc=10816/wandering-skeleton
Item: https://classic.wowhead.com/item=12738/dalson-outhouse-key
Quest: https://classic.wowhead.com/quest=5059/locked-away
Spell: https://classic.wowhead.com/spell=
Object: https://classic.wowhead.com/object=

**Expected Behaviour**
Wandering skeleton should drop the key that allows players to interact with the outhouse to complete the quest.

**Comment by NickTyrer** [comment]
Have you completed the required pre quest https://classic.wowhead.com/quest=5058/mrs-dalsons-diary?

**Comment by NickTyrer** [comment]
Tested and working
