### ISSUE TITLE
PW: Shield animation disappears in shadowform

### ISSUE THREAD

**Issue by staticallyvoid** [the-hyjal-project/bugtracker#433]
**Describe Your Issue**
The animation on the priest ability Power Word: Shield disappears when the players enters shadowform. When going back to normal form, the animation re-appears.

**Steps To Reproduce**

1. Cast PW: S while not in shadowform and observe the bubble/halo animation effect
2. Enter shadowform and this animation disappears
3. Go back to normal form while the PW: S buff is still active and observe the animation re-appear again

NPC: https://classic.wowhead.com/npc=
Item: https://classic.wowhead.com/item=
Quest: https://classic.wowhead.com/quest=
Spell: https://classic.wowhead.com/spell=15473/shadowform
Spell: https://classic.wowhead.com/spell=spell=10901/power-word-shield
Object: https://classic.wowhead.com/object=

**Expected Behaviour**

The animation should be visible regardless of whether priest is in shadow or normal form

**Comment by GrenderG** [comment]
https://user-images.githubusercontent.com/8654362/113319034-584b7780-9311-11eb-9bc3-7818b8b4a118.mp4

Seems to be present, it's just hard to see unless you target yourself to light your character.

Vanilla video for reference: https://www.youtube.com/watch?v=w7pP4ouSkqQ
You can check at 0:24 and you'll notice that the shield is barely visible either.
