### ISSUE TITLE
Mo'grosh Ogres debuff dubious behaviour

### ISSUE THREAD

**Issue by Pirupuku** [the-hyjal-project/bugtracker#434]
**Describe Your Issue**

After fighting some ogres (Mo'grosh *) in Loch Modan (upper right corner the elite ones) I got a debuff. I sadly didn't pay to much attention but my body got engulfed in flames (normal behaviour) BUT also all other mobs, npcs etc got engulfed in flames AND after the debuff ran out they are still like that! Even after 5+ min it is like that! Similar to the ZG drunken debuff I know from other pservers. The buff runs out but the blurry vision won't run off until you die or relog. But that's another issue I don't even know if it's like that on Hyjal/Tyr's Hand as we couldn't test ZG.

**Steps To Reproduce**

1. Fight some Mo'grosh ogres (brutes, enforcer) don't know exactly which mob gives that debuff
2. Get the debuff
3. See how all the NPCs turn red, engulfed in flames

NPC: https://classicdb.ch/?search=mo%27grosh#npcs (just putted the whole NPCs here as I don't know which exactly had it)

**Expected Behaviour**

Only I myself should engulf in flames and turn red and after the debuff runs out I should be back to normal.

(Got a screenshot if that's helping)

**Comment by Gamemechanicwow** [comment]
Should be fixed tomorrow :>
