### ISSUE TITLE
The trigger area for completing the objective in the quest The Master's Glaive (id 944) doesn't seem right.

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#44]
**Describe Your Issue**
The trigger area for completing the objective in the quest The Master's Glaive (id 944) doesn't seem right. I think it should complete as you step in the water and approach the island in the center of the area. I had to go to the southern end, behind the massive monument, to make it trigger.

**Steps To Reproduce**

1.
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected Behavior**

**Comment by petage** [comment]
Adding the [Classic Wowhead page](https://classic.wowhead.com/quest=944/the-masters-glaive) of the quest and [this video](https://youtu.be/oF_Ds24qz4E?t=25065) from Classic WoW showing where the quest should get completed. The video link is timestamped.

**Comment by ratkosrb** [comment]
Fixed in https://github.com/vmangos/core/commit/c1db8e8f625ba5dbba3c03a11eafb4411e1557db
