### ISSUE TITLE
Grom'gol Inn, no rest status

### ISSUE THREAD

**Issue by CCmagro** [the-hyjal-project/bugtracker#442]
**Describe Your Issue**
Cant have rest status in that Inn.

**Steps To Reproduce**

1. Step inside
2. No "sleeping" icon on the character frame

**Expected Behaviour**

Its supposed to be an Inn, it has an Innkeeper!

**Comment by GrenderG** [comment]
The inn was not added until Patch 1.7. However I have noticed that the Innkeeper shouldn't be there until that patch, it was an old Gun Merchant spawned in Durotar that was repurposed to be the Innkeeper of Grom'gol.

**Comment by GrenderG** [comment]
https://github.com/vmangos/core/pull/1146/f
