### ISSUE TITLE
Warlock Pet

### ISSUE THREAD

**Issue by Pirupuku** [the-hyjal-project/bugtracker#445]
**Describe Your Issue**

When you have an active Pet, and summon a new one, the active one should not disappear directly as it does right now.

**Steps To Reproduce**

1. Summon any Pet
2. Summon another one while you have an active Pet
3. Active Pet disappears when you start the cast

**Expected Behaviour**

The active Pet should disappear when you finish the cast as far as I know and not when you start the cast as it currently does.

**Comment by ratkosrb** [comment]
Pretty sure we researched this and found out the pet should despawn as soon as you start casting in Vanilla. In TBC they changed it so the current pet gets stunned while you are summoning a new one.

**Comment by Pirupuku** [comment]
Ok, than every other pserver did it the TBC way

**Comment by Daribon** [comment]
Current behavior is the correct one for vanilla. They changed it in TBC.
