### ISSUE TITLE
Holy shield does no damage

### ISSUE THREAD

**Issue by Jumpingthroughhoops** [the-hyjal-project/bugtracker#446]
**Describe Your Issue**
< When blocking with holy shield active, it will expend a charge but do 0 damage >

**Steps To Reproduce**

1. Be paladin
2. Spec protection w/ Holy Shield
3. Activate Holy Shield
4. Block

Spell: https://classic.wowhead.com/spell=20928/holy-shield

**Expected Behaviour**

 after blocking with holy shield active and expending a charge, should do 130 holy damage for each blocked attack + spell power coefficient.  Also should increase threat by 20% on those damage outputs.

**Comment by Nolin7777** [comment]
fixed here -> https://github.com/vmangos/core/commit/95aece62a82979b82f8bb784b6ae792d13804f16
