### ISSUE TITLE
Blessing of Sanctuary deal no holy damage

### ISSUE THREAD

**Issue by Jumpingthroughhoops** [the-hyjal-project/bugtracker#447]
**Describe Your Issue**
< When blocking, Blessing of Sanctuary deal 0 reflective damage>

**Steps To Reproduce**

1. Be paladin
2. Spec protection w/ Blessing of Sanctuary
3. Block

Spell: https://classic.wowhead.com/spell=20914/blessing-of-sanctuary

**Expected Behaviour**

**Comment by Nolin7777** [comment]
fixed here -> https://github.com/vmangos/core/commit/95aece62a82979b82f8bb784b6ae792d13804f16
