### ISSUE TITLE
Onu (id 3616) doesn't offer the quest

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#45]
**Describe Your Issue**
Onu (id 3616) doesn't offer the quest https://classic.wowhead.com/quest=961/onu-is-meditating when you're on the quest https://classic.wowhead.com/quest=949/the-twilight-camp like he should. I abandoned the quest The Twilight Camp, deleted my Phial of Scrying and now I'm unable to get the quest again.

**Steps To Reproduce**

1.
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected Behavior**

**Comment by petage** [comment]
Adding a link to the [NPC](https://classic.wowhead.com/npc=3616/onu) in question.

**Comment by ratkosrb** [comment]
Fixed in https://github.com/vmangos/core/commit/c1db8e8f625ba5dbba3c03a11eafb4411e1557db
