### ISSUE TITLE
quest Orans Gratitude not offered by Oran Snakewrithe

### ISSUE THREAD

**Issue by Halahlstrom** [the-hyjal-project/bugtracker#455]
**Describe Your Issue**
I did the escort of Rinji in Hinterlands, visited the island for the completion of the quest. This then sends you to Oran in Undercity for a follow-up quest, which according to wow databases should lead to a quest called "oran's gratitude". This quest is not offered when the required quest completion is done.
Deleted WDB and checked again, but the quest was not available to the player.

**Steps To Reproduce**
1. Completed the required quests in hinterlands and undercity
2.  Witness the quest "Oran's gratitude" not being available to the player.
3. 

NPC: https://classic.wowhead.com/npc=
Item: https://classic.wowhead.com/item=
Quest: https://classic.wowhead.com/quest=8273/orans-gratitude
Spell: https://classic.wowhead.com/spell=
Object: https://classic.wowhead.com/object=

**Expected Behaviour**
Quest should be available to pick up by a player once the required quest delivery is completed  ( https://classic.wowhead.com/quest=2782/rinjis-secret )

**Comment by NickTyrer** [comment]
According to the DB this quest was only added in a later patch.
