### ISSUE TITLE
 The mob just keeps evading in place and if you kill it, Therylune is still bugged. 

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#46]
**Describe Your Issue**
So this initially happened as I was in stealth and Therylune aggroed a mob. The mob just keeps evading in place and if you kill it, Therylune is still bugged. Also I noticed she doesn't seem to generate threat. She never pulled aggro off of me even if I just hit the mob once and stood there while she kept autoattacking it.

https://ptb.discord.com/channels/770005571910500484/780923795782369360/783556406741696515

**Steps To Reproduce**

1.
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected Behavior**

**Comment by petage** [comment]
Adding a link to the [NPC](https://classic.wowhead.com/npc=3584/therylune) and the [quest](https://classic.wowhead.com/quest=945/therylunes-escape) in question.

**Comment by petage** [comment]
Also [here](https://cdn.discordapp.com/attachments/780923795782369360/783556406627401788/2020-12-02_06-38-50.mkv) is a direct link to the video which was referenced in the original post.

**Comment by ratkosrb** [comment]
Fixed in https://github.com/vmangos/core/commit/0a24e43fe353853d860b5349c3677a6d9d9867db
