### ISSUE TITLE
Molten Core attunement

### ISSUE THREAD

**Issue by Brodda** [the-hyjal-project/bugtracker#468]
**Describe Your Issue**
Core Fragment is missing inside BRD.

https://classic.wowhead.com/object=179553/core-fragment

**Comment by GM-Dave-THP** [comment]
![image](https://user-images.githubusercontent.com/19539976/115899334-87f42800-a456-11eb-88fa-05d25e3cee0f.png)

**Comment by GM-Dave-THP** [comment]
Update:

The core fragment was moved in patch 1.4 to its position outside of the instance in BRD
