### ISSUE TITLE
Rogue/druid stealth

### ISSUE THREAD

**Issue by Ejbinator** [the-hyjal-project/bugtracker#477]
Stealth works different from a few days. When i approach mobs from behind, they always turn on me, even when they are many levels below mine. 

This happens also when they are distracted. They turn a bit or directly on you.

Its same with rogue as with druid.

**Comment by WobLight** [comment]
Hello,
please state your level, stealth rank and mob level to help investigating.

**Comment by Ejbinator** [comment]
There are 2 cases i can report.
1. Druid level 35, no stealth talents. Interacting with mobs in level range from 28 to 40. Mostly in desolace. Satyrs, centaurs, scorpions etc. Doesnt matter what kind of enemy you face.
2. Same with rogue level 30, no stealth talents. Mobs in wetlands in range 22 to 29. Raptors, dragonmaw orcs, etc.

**Comment by WobLight** [comment]
Fix pending
