### ISSUE TITLE
Runecloth turn in not available for Darkspear Trolls

### ISSUE THREAD

**Issue by ripcurl91** [the-hyjal-project/bugtracker#478]
After turning in Wool, Silk and Mageweave there should be an option given for Runecloth. However, after turning in Mageweave the NPC won't offer any repeatable quest anymore.

**Comment by chaudgod** [comment]
I went UC > TB and had all the turnins, went to org started troll turnin and had the same issue - went and turned in the org rep and came back and it was available.

**Comment by ripcurl91** [comment]
I can't even turn in anything for Org rep
