### ISSUE TITLE
Quest "Proof of Demise" in Tirisfal Glades Does not require first quest of "At War With The Scarlet Crusade"

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#48]
**Describe Your Issue**
Bug: Quest "Proof of Demise" in Tirisfal Glades Does not require first quest of "At War With The Scarlet Crusade" to be completed before pick up. Proof:
https://classic.wowhead.com/quest=374/proof-of-demise#comments:id=2933524

https://cdn.discordapp.com/attachments/780923795782369360/783653779811074069/proof_of_demise.jpg
https://cdn.discordapp.com/attachments/780923795782369360/783653810170101760/proof_of_proof_of_demise.jpg

**Steps To Reproduce**

1.
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected Behavior**

**Comment by ratkosrb** [comment]
Fixed in https://github.com/vmangos/core/commit/c1db8e8f625ba5dbba3c03a11eafb4411e1557db
