### ISSUE TITLE
Zul Farrak bug

### ISSUE THREAD

**Issue by Packo93** [the-hyjal-project/bugtracker#480]
**Describe Your Issue**

The Zul Farrak dungeon needs to be repaired, the first two bosses are not working properly, the second NPCs on the graveyard, they are not synchronizd, can't as mage AOE farming, as it works on real classic, generally the whole dungeon needs to be repaired please.
**Steps To Reproduce**

1. So need synchronize NPCs, to do not leave agroo, and do not spawn alot when is boss attacked..
2. 
3. 

NPC: https://classic.wowhead.com/npc=
Item: https://classic.wowhead.com/item=
Quest: https://classic.wowhead.com/quest=
Spell: https://classic.wowhead.com/spell=
Object: https://classic.wowhead.com/object=

**Expected Behaviour**

**Comment by GM-Dave-THP** [comment]
Need more information other than "the first two bosses are not working properly"
