### ISSUE TITLE
Level 40 Riding Skill bug

### ISSUE THREAD

**Issue by Shoryutofu** [the-hyjal-project/bugtracker#485]
**Describe Your Issue**
No level 40 riding skill learned after buying the ability from the Orc Riding Trainer in Orgrimmar.

**Steps To Reproduce**

1. I purchased the the Wolf riding skill for 18g in Orgrimmar from the Riding Trainer
2. I bought one of the level 40 mount ( Dire Wolf) for 72g
3. I am unable to use the level 40 mount because I do not have the riding skill.
4. I can not buy/learn the skill again from the trainer because it is not longer available for me to buy( already known)
![No riding skill](https://user-images.githubusercontent.com/83883756/117551323-2a391180-affa-11eb-8e7e-be1f46e832c5.jpg)

NPC: https://classic.wowhead.com/npc=
Item: https://classic.wowhead.com/item=
Quest: https://classic.wowhead.com/quest=
Spell: https://classic.wowhead.com/spell=
Object: https://classic.wowhead.com/object=

**Expected Behaviour**

**Comment by GM-Dave-THP** [comment]
Hi,

Can you please delete your WDB folder and check this again.

**Comment by Shoryutofu** [comment]
Hi,Thank you for the response!I have already tried deleting the WDB cache folder, but did not have any affect.However I can try it again once I am home.Sent from my Galaxy
-------- Original message --------From: Dave ***@***.***> Date: 5/9/21  10:53 AM  (GMT-08:00) To: the-hyjal-project/bugtracker ***@***.***> Cc: Shoryutofu ***@***.***>, State change ***@***.***> Subject: Re: [the-hyjal-project/bugtracker] Level 40 Riding Skill bug (#485) 
Hi,
Can you please delete your WDB folder and check this again.

**Comment by Shoryutofu** [comment]
Hi,This time make sure to close the Game completely, Deleteed the WDB, and then start the game.I can mount now! =)Thanks!!Sent from my Galaxy
-------- Original message --------From: Dave ***@***.***> Date: 5/9/21  10:53 AM  (GMT-08:00) To: the-hyjal-project/bugtracker ***@***.***> Cc: Shoryutofu ***@***.***>, State change ***@***.***> Subject: Re: [the-hyjal-project/bugtracker] Level 40 Riding Skill bug (#485) 
Hi,
Can you please delete your WDB folder and check this again.
