### ISSUE TITLE
Quest "Tears of the moon" in Teldrassil

### ISSUE THREAD

**Issue by Barwaat** [the-hyjal-project/bugtracker#486]
Hello,

The ques NPC Lady Sathrah for the quest "Tears of the Moon" is not spawning, and mobs around her aren't spawning either. We've waited for 5min + and there's no sign of anything spawning in the area.

We can't complete the quest (I did do it 2 weeks ago and the NPC was there).

Thanks

NPC: https://classic.wowhead.com/npc=7319
Quest: https://classic.wowhead.com/quest=2518

**Expected Behaviour**
The NPC should spawn at 48.1:25.1 and should have a respawn time of 2 minutes like sourrounding mobs (which aren't here either).

**Comment by GM-Dave-THP** [comment]
I have checked and this NPC is spawned correctly, This NPC has more then one spawn location as seen on wowhead.

**Comment by GM-Dave-THP** [comment]
![image](https://user-images.githubusercontent.com/19539976/117581899-4373b800-b0f7-11eb-9ee0-c4d34cea2cbf.png)
