### ISSUE TITLE
"Pearl Diving" Quest

### ISSUE THREAD

**Issue by rockenos** [the-hyjal-project/bugtracker#489]
**Describe Your Issue**
No more than two of the Giant Clam objects that contain Blue Pearls are spawned at a time, making this quest take hours. 

**Steps To Reproduce**

1. Swim around the Vile Reef off the coast of Grom Gol for an hour and look for Giant Clams.
2. I found only 2 spawned in 15+ minutes with no competition from other players.
3. 

Item: https://classic.wowhead.com/item=4611
Quest: https://classic.wowhead.com/quest=705
Object: https://classic.wowhead.com/object=2744

**Expected Behaviour**

Should be sufficient Giant Clams spawned at any given time to allow at least one player to complete the quest. There are tons of nodes where they can spawn, so I'm not sure why they aren't populated. Perhaps the respawn time is too long, or improperly randomized.

**Comment by ratkosrb** [comment]
Fixed here - https://github.com/vmangos/core/commit/3f848afc257371849c018ea27fad9b5e3f34bd21
