### ISSUE TITLE
Coming to a new group of mobs and click-targetting one for the first time makes you target another.

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#49]
**Describe Your Issue**
https://cdn.discordapp.com/attachments/780923795782369360/783679161599918141/Classic_Mob_targeting_bug1.gif

**Steps To Reproduce**

How to recreate: Make sure you have atleast 2 mobs of the same grp in distance. relog to make sure you haven't targetted them before and click once on a target
I tested this on several Rotting dead and the target always went to the same mob

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected Behavior**

**Comment by kodolol** [comment]
Might just be an addon/client issue. Needs testing again w/o any addons.

**Comment by Gamemechanicwow** [comment]
he did another test iirc; it was caused by a nameplate addon.
