### ISSUE TITLE
Doomguard & Inferal mob duration

### ISSUE THREAD

**Issue by Firestoat** [the-hyjal-project/bugtracker#493]
The Bug - On most Mang0s core servers (including Hyjal's) a summoned Infernal or Doomguard will have a spawn duration of between 30 minutes to 1 hour after entering the game world, depending on the version of server used. This allows players to grief a location like say, Crossroads in the barrens with a spell and mob behavior that was never possible on old retail.

Classic - In the 2004-2007 era of the game, Doomguards and Infernals only had a spawned duration of 5 seconds upon the clearing of their current Hate / Aggro list. All Infernals and Doomguards had the Warlock player which summoned them automatically placed at the bottom of their hate list upon casting spawn-in, with potential hostile (to the mob's tracking) targets added to the list based on normal detection range and target activity (healing, demo shouts, etc).

To Reproduce - Log on a Warlock of appropriate level with the appropriate Infernal or Doomguard summoning spell and watch to see if the summoned mob will remain in an idle stance and location after its hate table is clear.

Video Evidence - this is an ancient Youtube video showing the despawn of the Doomguard about 3-5 seconds after the mob's hate list has been cleared, which was a normal result. The music is terrible, so skip forward to the 3:40 time mark. -
https://www.youtube.com/watch?v=SagtQmamJ9A

(Spell) Ritual of Doom - https://classic.wowhead.com/spell=18540/ritual-of-doom
(Mob) Doomguard - https://classic.wowhead.com/npc=11859/doomguard

(Spell) Inferno - https://classic.wowhead.com/spell=1122/inferno
(Mob) Infernal - https://classic.wowhead.com/npc=89/infernal

**Comment by ratkosrb** [comment]
Fixed here - https://github.com/vmangos/core/commit/a5567ba373de4378b8864317d075fa52c552de3d
