### ISSUE TITLE
Pirate Hats Ahoy and Southsea Shakedown

### ISSUE THREAD

**Issue by rhukar** [the-hyjal-project/bugtracker#495]
**Two quests in Tanaris don't appear to be in the game?**
There's an NPC in Tanaris - Haughty Modiste that seems to be missing in the game. She's supposed to be in Steamwheedle Port. Separately, in the same area, Security Chief Bilgewhizzle is supposed to also have the quest Southsea Shakedown available for pickup but it doesn't appear to be so. 

**Steps To Reproduce**
1. Coordinates ~ 67,22 is where Haughty Modiste is supposed to exist as an NPC with the quest Pirate Hats Ahoy! quest available
2. 
3. 

NPC: https://classic.wowhead.com/npc=15165/haughty-modiste
Quest: https://classic.wowhead.com/quest=8365/pirate-hats-ahoy
Quest 2: https://classic.wowhead.com/quest=8366/southsea-shakedown

**Expected Behaviour**

There should be these an NPC - Haughty Modiste that exists in Steamwheedle Port that has a quest (Pirate Hats Ahoy!) you can start and there is an existing NPC in Steamwheedle Port - Security Chief Bilgewhizzle - that doesn't have the quest (Southsea Shakedown) available.

**Comment by ratkosrb** [comment]
NPC Haughty Modiste was added in patch 1.8. Quest Southsea Shakedown was also added in patch 1.8.

**Comment by rhukar** [comment]
Ah, I see those patch notes and Wowhead has differing information. Apologie sand thank you ratkosrb!
