### ISSUE TITLE
Wolf stuck on statue in ashenvale

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#5]
**Describe Your Issue**
Wolf stuck on statue in ashenvale, 31.2, 50.6 - https://cdn.discordapp.com/attachments/780923795782369360/781724914737610762/unknown.png

**Steps To Reproduce**

1.
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected Behavior**

**Comment by GM-Dave-THP** [comment]
Moving this mob 10 yards of his X or Y position will fix this - Tested and confirmed.

**Comment by Nolin7777** [comment]
> Moving this mob 10 yards of his X or Y position will fix this - Tested and confirmed.

We need an SQL migration for every single change in the DB, in case it's damaged somehow and need a new fork.

**Comment by ratkosrb** [comment]
Fixed in https://github.com/vmangos/core/commit/c1db8e8f625ba5dbba3c03a11eafb4411e1557db
