### ISSUE TITLE
gnomish / goblin rocket boots, nifty's stopwatch, skull of impending doom, swift boots - Cooldown

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#52]
**Describe Your Issue**
so, this is a pretty big issue: items such as gnomish / goblin rocket boots, nifty's stopwatch, skull of impending doom, swift boots, etc. - basically all run speed increasing items and even more gadgets I can't think of yet - SHARE the same cooldown. this means, when you use one, you'll get locked from using any other of said items for 5 minutes.

I'm not sure if this is an early patch thing or just a bug - but it completely impairs pvp in every aspect and should be in the state of 1.12, same as the talents. when warsong drops, especially, you want all of these items working properly otherwise people will go crazy.

**Steps To Reproduce**

1.
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected Behavior**

**Comment by Nolin7777** [comment]
Not a bug, thats part of progression.
