### ISSUE TITLE
LoS issues

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#53]
**Describe Your Issue**
Hi, i wanted to ask whether you guys have encountered LoS issues?
More specifically, in caster mobs
I was doing the caster mobs in undead starting area, and i figured to mess around with LoS around the trees, and they could shoot fireballs straight thru

**Steps To Reproduce**

1.
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected Behavior**

**Comment by Nolin7777** [comment]
Intended.
