### ISSUE TITLE
Rank 1 overpower (lvl 12) does not state it requires battle stance

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#54]
**Describe Your Issue**
Rank 1 overpower (lvl 12) does not state it requires battle stance.  I am able to use it in fury stance.   Rank 2, which I have not trained, says it requires battle stance.  I checked on classic and rank 1 does require battle stance.   Allakhazam does not state which stance the skill requires as far as I can find, so I cannot confirm.

**Steps To Reproduce**

1.
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected Behavior**

**Comment by ratkosrb** [comment]
![WoWScrnShot_121120_153240](https://user-images.githubusercontent.com/35845488/101909449-2d081580-3bc6-11eb-9d80-d8b026980de6.jpg)

Unable to reproduce.

**Comment by ratkosrb** [comment]
The stance requirements for spells like most spell data comes from the client btw.

**Comment by High-Speed-Dirt** [comment]
My apologies, this is an issue with the addon "Theory Craft" which I did not think to disable.  This issue can be closed.
