### ISSUE TITLE
The quest https://classic.wowhead.com/quest=5713/one-shot-one-kill - Issues

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#55]
**Describe Your Issue**
The quest https://classic.wowhead.com/quest=5713/one-shot-one-kill has multiple issues. Currently Sentinel Aynasha doesn't attack any of the mobs that spawn, and they walk instead of running. She is missing some voice lines and has a debuff (https://classic.wowhead.com/spell=18373/aynashas-root) which should be hidden. Also, if you let the final mob (https://classic.wowhead.com/npc=11714/marosh-the-devious) despawn, you won't be able to complete the quest and Aynasha will stay in a bugged state (like the quest was still in progress) presumably until the next server restart. I'm not quite sure about the expected behaviour on the mobs attacking Aynasha, but I'm assuming they should attack her, in which case Marosh the Devious despawning won't be a thing/issue. A video from Classic WoW with the quest shown in action: https://youtu.be/oF_Ds24qz4E?t=25693 (the link is timestamped). Interestingly enough in the video Aynasha attacks the mobs through all three waves. Quote from a comment on 2006-01-16: "Last wave Sentinal Aynasha will run out of arrows and won't help you.". Did Blizzard fuck up the scripting too? She should run away at the end as you complete the quest like shown in the video.

**Steps To Reproduce**

1.
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected Behavior**

**Comment by petage** [comment]
Adding a link to the [NPC](https://classic.wowhead.com/npc=11711/sentinel-aynasha) in question.

**Comment by ratkosrb** [comment]
https://github.com/vmangos/core/commit/5b98daa7a597f4797dd7239483e9555cc0792909
