### ISSUE TITLE
The quest https://classic.wowhead.com/quest=731/the-absent-minded-prospector has a few issues.

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#56]
**Describe Your Issue**
The quest https://classic.wowhead.com/quest=731/the-absent-minded-prospector has a few issues. Firstly, Prospector Remtravel doesn't aggro any mobs on his escort route. He should aggro the golems and troggs. Secondly, the range at which the quest fails because you got too far away from him seems too long. I was able to cheese the quest by dying in a central spot and just waiting until Remtravel finished his escort route. Lastly, I'm not totally sure if this is blizzlike, but the mobs which spawn during the escort automatically aggro onto you even if you are in stealth and far away. Here's a reference video of the quest from Classic WoW: https://youtu.be/oF_Ds24qz4E?t=26105 (the link is timestamped).

**Steps To Reproduce**

1.
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected Behavior**

**Comment by petage** [comment]
Adding a link to the [NPC](https://classic.wowhead.com/npc=2917/prospector-remtravel) in question.

**Comment by Nolin7777** [comment]
Note: Wrong faction?
