### ISSUE TITLE
the storwmwind guard that patrols in westbrook garrison walks over tables, walls and weapon racks

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#58]
**Describe Your Issue**
the storwmwind guard that patrols in westbrook garrison walks over tables, walls and weapon racks

https://cdn.discordapp.com/attachments/780923795782369360/784132754597347369/unknown.png
https://cdn.discordapp.com/attachments/780923795782369360/784133010873122856/unknown.png

another female guard walking on the side upstairs

**Steps To Reproduce**

1.
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected Behavior**

**Comment by ratkosrb** [comment]
Bugged mmaps inside the building.
