### ISSUE TITLE
the cannon for the quest "Death From Below" is not working

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#59]
**Describe Your Issue**
BUG: the cannon for the quest "Death From Below" is not working (it should kill the naga waves when right-clicked)

**Steps To Reproduce**

1.
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected Behavior**

**Comment by ratkosrb** [comment]
Fixed in https://github.com/vmangos/core/commit/0a24e43fe353853d860b5349c3677a6d9d9867db
