### ISSUE TITLE
imp doesnt make any sound when it commences an attack

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#6]
**Describe Your Issue**
imp doesnt make any sound when it commences an attack

**Steps To Reproduce**

1.
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected Behavior**
Needs to be verified.

**Comment by Nolin7777** [comment]
Fixed on next fork
