### ISSUE TITLE
Ursal the Mauler event where the enslaved druids fly off doesn't happen.

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#60]
**Describe Your Issue**
Ursal the Mauler event where the enslaved druids fly off doesn't happen.
**Steps To Reproduce**

1.
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected Behavior**

**Comment by Nolin7777** [comment]
Sources? Links? IDs?

**Comment by petage** [comment]
I'm not the one who reported this issue, but I found some information. When [Ursal the Mauler](https://classic.wowhead.com/npc=2039/ursal-the-mauler) dies, the four [Enslaved Druid of the Talon](https://classic.wowhead.com/npc=2852/enslaved-druid-of-the-talon) resided next to the camp shapeshift into [Freed Druid of the Talon](https://classic.wowhead.com/npc=2853/freed-druid-of-the-talon) and say some RP text before flying away. See [this](https://youtu.be/vSyTQxPJ-rg) video of the event in Classic WoW. At 1:02 in the video Ursal the Mauler dies and the event begins.

**Comment by ratkosrb** [comment]
Fixed in https://github.com/vmangos/core/commit/f7e05b063cb778c471152387f561410aed4de97c
