### ISSUE TITLE
2 mobs walking on top of an object

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#62]
**Describe Your Issue**
https://cdn.discordapp.com/attachments/780923795782369360/784893876820639744/unknown.png

its south east of goldshire
just off the road

**Steps To Reproduce**

1.
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected Behavior**

**Comment by GM-Dave-THP** [comment]
the two mobs are guid: 80706 and 80708

**Comment by Nolin7777** [comment]
IdleMovementGenerator
