### ISSUE TITLE
32.50 tirisfal glades there's a scarlet warrior that spawns underground

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#63]
**Describe Your Issue**
32.50 tirisfal glades there's a scarlet warrior that spawns underground

**Steps To Reproduce**

1.
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected Behavior**

**Comment by Nolin7777** [comment]
What does that mean?

**Comment by GM-Dave-THP** [comment]
Discord report: 

NPC ID: 1535 spawned underground @ coordinates 32 50

**Comment by ratkosrb** [comment]
Tell us the guid.

**Comment by Gamemechanicwow** [comment]
guid: 38336

**Comment by ratkosrb** [comment]
Fixed in https://github.com/vmangos/core/commit/f37b4439082ab182d739e23d7ba7eb574f430bd5
