### ISSUE TITLE
I went to go pick a mageroyal and after i picked it i got the items but the flower was still sitting there 

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#64]
**Describe Your Issue**
Bug report: I went to go pick a mageroyal and after i picked it i got the items but the flower was still sitting there then i went to pick it again and it disappeared 

**Steps To Reproduce**

1.
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected Behavior**

**Comment by GM-Dave-THP** [comment]
Should of been lag - please report if this is seen again

**Comment by Nolin7777** [comment]
Maybe a double spawn? Reopen if necessary..
