### ISSUE TITLE
Mobs with healing abilities seem to more or less spam their heal with very little time

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#65]
Mobs with healing abilities seem to more or less spam their heal with very little time inbetween making them extremely hard to kill.

Steps To Reproduce

Attack a Scarlet Friar or Rot Hide Mystic for example.

Mobs: https://classic.wowhead.com/npc=1538/scarlet-friar#abilities

https://classic.wowhead.com/npc=1773/rot-hide-mystic#abilities

**Comment by ratkosrb** [comment]
Scarlet Friar's heal cooldown matches Trinity so I have not changed it. Cooldown on Rot Hide Mystic's heal changed here https://github.com/vmangos/core/commit/c1db8e8f625ba5dbba3c03a11eafb4411e1557db
