### ISSUE TITLE
 kobold in jasperlode mine casts fireball on me it has a chill effect

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#68]
**Describe Your Issue**
when the kobold in jasperlode mine casts fireball on me it has a chill effect with it.  i thought this was a bug. then i checked his abilities on wowhead and it appears that he actually causes chilled effect too.
https://classic.wowhead.com/npc=476/kobold-geomancer#abilities

https://cdn.discordapp.com/attachments/780923795782369360/785626710053355530/unknown.png

**Steps To Reproduce**

1.
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected Behavior**

**Comment by ahly1213** [comment]
i dont think this is a bug. i checked the mob's data on wowhead and the chill ability is present. https://classic.wowhead.com/npc=476/kobold-geomancer#abilities

you can remove this from the tracker. i am the one who wrongly reported this.
