### ISSUE TITLE
The rare mob Lady Vespia doesn't have the quest item Ring of Zoram on her drop table.

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#69]
The rare mob Lady Vespia doesn't have the quest item Ring of Zoram on her drop table.

Steps To Reproduce

``SELECT * FROM `creature_loot_template` WHERE `item`='5445';``

https://classic.wowhead.com/npc=10559/lady-vespia#drops
https://classic.wowhead.com/item=5445/ring-of-zoram#dropped-by

Expected Behavior

Lady Vespia should have Ring of Zoram on her drop table, presumably with a 100% drop rate.

**Comment by ratkosrb** [comment]
Fixed in https://github.com/vmangos/core/commit/c1db8e8f625ba5dbba3c03a11eafb4411e1557db
