### ISSUE TITLE
The wolves on the northshire valley get out of combat after I attack them with my rogue

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#70]
Describe Your Issue

The wolves on the northshire valley get out of combat after I attack them with my rogue level 1, tried atleast with 2 wolves, both sinester strike(skill) or auto attacks

Steps To Reproduce

1. Target a Young Wolf
2. Attack him
3. After 1s or even less the mob leaves combat without attacking me, like if I had gm or something 

NPC: https://classic.wowhead.com/npc=299/young-wolf

Expected Behavior

Like a normal mob, attacking me if I attack him

**Comment by kodolol** [comment]
This was just a client issue and was fixed after a /reload.
![image](https://user-images.githubusercontent.com/37703096/101631514-21351b80-3a2d-11eb-8ef9-19c30ff0f696.png)

**Comment by GM-Dave-THP** [comment]
Client side issue. Closed.
