### ISSUE TITLE
Yarrog Baneshadow doesnt spawn

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#72]
**Describe Your Issue**
42.5, 53,6. Yarrog Baneshadow doesnt spawn

https://cdn.discordapp.com/attachments/780923795782369360/785830720600801320/unknown.png

**Steps To Reproduce**

1.
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected Behavior**

**Comment by kodolol** [comment]
They were underneath the spawn point, everything is all right I believe ^^

**Comment by GM-Dave-THP** [comment]
Ah yes, you were correct I did confirm that one.
