### ISSUE TITLE
The drop rate of Pridewing Venom Sac is too high and Pridewing Soarer should not drop it.

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#73]
Describe Your Issue

The drop rate of Pridewing Venom Sac is too high and Pridewing Soarer should not drop it.

Steps To Reproduce

``SELECT * FROM `creature_loot_template` WHERE `item`='5808'; ``
``SELECT * FROM `creature_loot_template` WHERE `entry`='6141';``

https://classic.wowhead.com/item=5808/pridewing-venom-sac#dropped-by
https://classic.wowhead.com/npc=6141/pridewing-soarer#comments

Expected Behavior

Pridewing Venom Sac's drop rate should be significantly lower than it currently is. See Classic Wowhead's (link above), Allakhazam's (https://web.archive.org/web/20060307141316/http://wow.allakhazam.com/db/item.html?witem=5808) and Thottbot's (archive from early TBC, there was no earlier one: https://web.archive.org/web/20070317021045/http://www.thottbot.com/i5808) drop rates for reference. Pridewing Soarer should not have Pridewing Venom Sac on its loot table, as it's a creature which cannot be targeted or killed (see the comments in the Classic Wowhead link).

**Comment by ratkosrb** [comment]
Fixed here https://github.com/vmangos/core/commit/c1db8e8f625ba5dbba3c03a11eafb4411e1557db
