### ISSUE TITLE
Turning in an item and choosing a reward and my bag is full i cant complete the quest and recieve the reward unless i free a slot. 

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#74]
**Describe Your Issue**
ive noticed that when completing a quest that requires turning in an item and choosing a reward and my bag is full i cant complete the quest and recieve the reward unless i free a slot. On classic i am able to recieve the reward while my bag is full because i am giving away an item and recieving another in its place so they jare ust switching slots in my bag.
**Steps To Reproduce**

1.
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected Behavior**

**Comment by Gammelman** [comment]
Was thinking this was false but looking at Joanas 1-60 it seems like it is a bug, https://youtu.be/9UafaB6V958?t=1058

**Comment by kodolol** [comment]
> Was thinking this was false but looking at Joanas 1-60 it seems like it is a bug, https://youtu.be/9UafaB6V958?t=1058

Taking a part of the video from that: seems like the way it's working now is intended.

![ezgif-5-ef211d3a5b51](https://user-images.githubusercontent.com/37703096/101630618-cd760280-3a2b-11eb-9989-9062a3ff4fa9.gif)

First he tries turning the quest in, notices his bags are full (and the quest doesnt get turned in), then he moves his arrows to the quiver so he has a free spot in his bags.

**Comment by Nolin7777** [comment]
I don't see an issue here
