### ISSUE TITLE
Quest "Supplies for the Crossroads" is available without having to do unlock Q "Disrupt the attacks"

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#75]
Quest "Supplies for the Crossroads" is available without having to do unlock Q "Disrupt the attacks"

Quest: https://classic.wowhead.com/quest=5041/supplies-for-the-crossroads

https://classic.wowhead.com/quest=871/disrupt-the-attacks

**Comment by ratkosrb** [comment]
Fixed here https://github.com/vmangos/core/commit/c1db8e8f625ba5dbba3c03a11eafb4411e1557db
