### ISSUE TITLE
Kolkar Wrangler in The Barrens have fire resistance, making them take close to no fire damage.

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#76]
Kolkar Wrangler in The Barrens have fire resistance, making them take close to no fire damage.

NPC: https://classic.wowhead.com/npc=3272/kolkar-wrangler

Expected Behavior

No other Kolkar resist fire damage like the wranglers. I cannot find a detailed database with resistances but I'm sure their not supposed to have fire resistance.

**Comment by Nolin7777** [comment]
No source, no fix.
