### ISSUE TITLE
Wizzlecrank's Shredder respawn bug

### ISSUE THREAD

**Issue by Gammelman** [the-hyjal-project/bugtracker#78]
**Describe Your Issue**

Wizzlecrank's Shredder that gives quests "Ignition" and "The Escape" respawns at the location which it have despawned. When starting the escort Q from the wrong location the shredder will run to the pathing start location, most likely dying in the process.

**Steps To Reproduce**

1. If Shredder is in correct location, start the escort Q and have it die in another location.
2. Wait for respawn.
3. Start escort quest anew and see the shredder running to pathing start location.

NPC: https://classic.wowhead.com/npc=3439/wizzlecranks-shredder
Quest: https://classic.wowhead.com/quest=863/the-escape

**Expected Behavior**

Shredder is supposed to respawn at the same location every time.

**Comment by ratkosrb** [comment]
Should be fixed by https://github.com/vmangos/core/commit/0a24e43fe353853d860b5349c3677a6d9d9867db
