### ISSUE TITLE
Checked cube while in flight

### ISSUE THREAD

**Issue by PennieLen** [the-hyjal-project/bugtracker#79]
**Describe Your Issue**
Every time I use the flight path I become a checked cube in flight 

**Steps To Reproduce**

1. As a human male warrior flight to Lakeshire from SW always turns me in to a checkered cube 
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected Behavior**

to not be a checkered cube while flying

**Comment by kodolol** [comment]
Wonder if it's just your client? I'll test this too whenever the server's back up.

**Comment by Gammelman** [comment]
As it doesn't happen for everyone I suspect it's client side. Try reinstalling

**Comment by kodolol** [comment]
Just checked: It's fine for me on my end. I'm pretty sure it's your install.

**Comment by GM-Dave-THP** [comment]
Client side bug for not finding a texture
