### ISSUE TITLE
Theramore Preserver's Renew is too powerful

### ISSUE THREAD

**Issue by Gammelman** [the-hyjal-project/bugtracker#80]
**Describe Your Issue**

[Theramore Preserver's](https://classic.wowhead.com/npc=3386/theramore-preserver) Do a Renew with cast time which ticks for around 20% of their total HP. This together with [This general healer mob issue](https://github.com/the-hyjal-project/bugtracker/issues/65#issue-758810446) makes them extremely hard to kill without a interruption.
**Steps To Reproduce**

1. Try to kill a Theramore Preserver as a lvl 19 mage for example

NPC: https://classic.wowhead.com/npc=3386/theramore-preserver

**Expected Behavior**

In general healers healing abilities should be less powerful, and the Theramore Preserver's Renew should be an instant cast , as seen [here](https://youtu.be/qKIZSBsK46s?t=496).

**Comment by Nolin7777** [comment]
Will be fixed in the new fork
