### ISSUE TITLE
Magic Dust

### ISSUE THREAD

**Issue by ripcurl91** [the-hyjal-project/bugtracker#81]
**Describe Your Issue**
The drop rate for "Magic Dust" in Westfall is too high.

**Steps To Reproduce**

1. Go to Westfall
2. Kill Dust Devils and monitor drop rate
3. 

Item: https://classic.wowhead.com/item=2091/magic-dust
NPC:  https://classic.wowhead.com/npc=832/dust-devil

**Expected Behavior**
Droprate should be around 15% according to wowhead and the item should be an instant cast.

**Comment by ratkosrb** [comment]
Fixed here https://github.com/vmangos/core/commit/c1db8e8f625ba5dbba3c03a11eafb4411e1557db
