### ISSUE TITLE
Blasting Powder (Engineering)

### ISSUE THREAD

**Issue by ripcurl91** [the-hyjal-project/bugtracker#82]
**Describe Your Issue**
Cast time of Blasting Powder is 5 seconds.

**Steps To Reproduce**

1. Get Engineering
2.  Create either Rough, Coarse, Heavy, Solid or Dense Blasting Powder

Item: https://classic.wowhead.com/item=4357/rough-blasting-powder, https://classic.wowhead.com/item=4364/coarse-blasting-powder, https://classic.wowhead.com/item=4377/heavy-blasting-powder, https://classic.wowhead.com/item=10505/solid-blasting-powder, https://classic.wowhead.com/item=15992/dense-blasting-powder

**Expected Behavior**
Blasting Powder cast time on Classic is 3 seconds.

**Comment by ratkosrb** [comment]
Spell cast times come from the client dbc.
