### ISSUE TITLE
Bubble fissures in Desolace

### ISSUE THREAD

**Issue by ripcurl91** [the-hyjal-project/bugtracker#84]
**Describe Your Issue**
Bubble fissures in Desolace do not refill breath

**Steps To Reproduce**

1. Go to the Desolace coast
2. Dive to any of the bubble fissures and watch how breath is not refilling
3. 

**Expected Behavior**
Bubble fissures should refill your breath

**Comment by GM-Dave-THP** [comment]
Linked to #40

**Comment by Gamemechanicwow** [comment]
Fixed
