### ISSUE TITLE
Gnomish Death Ray cooldown

### ISSUE THREAD

**Issue by ripcurl91** [the-hyjal-project/bugtracker#87]
**Describe Your Issue**
Gnomish Death Ray cooldown is 10 minutes.

**Steps To Reproduce**

1. Use Gnomish Death Ray.

Item: https://classic.wowhead.com/item=10645/gnomish-death-ray

**Expected Behavior**
Gnomish Death Ray should have a cooldown of 5 minutes.

**Comment by kodolol** [comment]
Gnomish Death Ray cooldown was decreased down to 5 minutes in [https://wow.gamepedia.com/Patch_1.4.0](patch 1.4). The PTR is currently on patch 1.2.
![image](https://user-images.githubusercontent.com/37703096/101657941-24d89a80-3a4d-11eb-9e33-31fe62b4c030.png)
