### ISSUE TITLE
Noggenfogger Elixir

### ISSUE THREAD

**Issue by ripcurl91** [the-hyjal-project/bugtracker#90]
**Describe Your Issue**
Noggenfogger Elixir has a 2 minute cooldown.

**Steps To Reproduce**

1. Use Noggenfogger Elixir.

Item: https://classic.wowhead.com/item=8529/noggenfogger-elixir

**Expected Behavior**
Noggenfogger Elixir shouldn't have a cooldown. It is vital for Warsong PvP and leaving this item in the nerfed state makes Battlegrounds dull and uninteresting.

**Comment by Nolin7777** [comment]
Changed in 1.11
