### ISSUE TITLE
Lil Timmy's White Kitten attackable

### ISSUE THREAD

**Issue by Simp-N** [the-hyjal-project/bugtracker#92]
**Describe Your Issue**
The White Kitten that follows Lil Timmy in Stormwind around can be attacked and looted.
[Here](https://www.youtube.com/watch?v=wtXma8OpXSw) is a video from classic where the player mouses over the kitten, and there's no sword-icon to indicate that it can be attacked. Go to around 0:14 for example.
[Here](https://www.youtube.com/watch?v=7LaRj-LRsPw) is another example from 2009. The video is very choppy but at around 0:57 you can see the player mousing over the kitten and there's no sword-icon here either.

**Steps To Reproduce**
1. Find Lil Timmy. I believe he's supposed to be "rare" in the sense that he isn't always up and wandering Stormwind. He patrolls around Cathedral square.
2. Kill the kitten.

Lil Timmy: https://classic.wowhead.com/npc=8666/lil-timmy
White Kitten: https://classic.wowhead.com/npc=7386/white-kitten

**Expected Behavior**
The player should not be able to attack the kitten, as if it was friendly.

**Comment by Nolin7777** [comment]
Note: NPC Flags

**Comment by ratkosrb** [comment]
Fixed in https://github.com/vmangos/core/commit/c1db8e8f625ba5dbba3c03a11eafb4411e1557db
