### ISSUE TITLE
The drop rate of Highborne Relic is too high

### ISSUE THREAD

**Issue by petage** [the-hyjal-project/bugtracker#94]
**Describe Your Issue**

The drop rate of the quest item Highborne Relic is currently set to 80% for all the 3 mobs it drops off of.

**Steps To Reproduce**

``SELECT * FROM `creature_loot_template` WHERE `item`='5360';``

https://classic.wowhead.com/item=5360/highborne-relic

**Expected Behavior**

The drop rate should be significantly lower as [Classic Wowhead](https://classic.wowhead.com/item=5360/highborne-relic#dropped-by) and [Thottbot](https://web.archive.org/web/20070315144843/http://www.thottbot.com/i5360) suggest.

**Comment by ratkosrb** [comment]
Fixed in https://github.com/vmangos/core/commit/c1db8e8f625ba5dbba3c03a11eafb4411e1557db
