### ISSUE TITLE
The drop rate of Fine Crab Chunks is too high

### ISSUE THREAD

**Issue by petage** [the-hyjal-project/bugtracker#95]
**Describe Your Issue**

The drop rate of the quest item Fine Crab Chunks is currently set to 80% for both of the mobs it drops off of.

**Steps To Reproduce**

``SELECT * FROM `creature_loot_template` WHERE `item`='12237';``

https://classic.wowhead.com/item=12237/fine-crab-chunks

**Expected Behavior**

The drop rate should be significantly lower as [Classic Wowhead](https://classic.wowhead.com/item=12237/fine-crab-chunks#dropped-by), [Allakhazam](https://web.archive.org/web/20080113171835/http://wow.allakhazam.com/item.html?witem=12237) and [Thottbot](https://web.archive.org/web/20070408180626/http://www.thottbot.com/i12237) suggest.

**Comment by ratkosrb** [comment]
Fixed in https://github.com/vmangos/core/commit/c1db8e8f625ba5dbba3c03a11eafb4411e1557db
