### ISSUE TITLE
The drop rate of Worn Parchment is too high

### ISSUE THREAD

**Issue by petage** [the-hyjal-project/bugtracker#96]
**Describe Your Issue**

The drop rate of the quest item Worn Parchment is currently set to 80% for the mob it drops off of.

**Steps To Reproduce**

``SELECT * FROM `creature_loot_template` WHERE `item`='5348';``

https://classic.wowhead.com/item=5348/worn-parchment

**Expected Behavior**

The drop rate should be significantly lower as [Classic Wowhead](https://classic.wowhead.com/item=5348/worn-parchment#dropped-by), [Allakhazam](https://web.archive.org/web/20050902121230/http://wow.allakhazam.com/item.html?witem=5348) and [Thottbot](https://web.archive.org/web/20070428051256/http://thottbot.com/i5348) suggest.

**Comment by ratkosrb** [comment]
Fixed in https://github.com/vmangos/core/commit/c1db8e8f625ba5dbba3c03a11eafb4411e1557db
