### ISSUE TITLE
The drop rate of Middle of Gelkak's Key is too high

### ISSUE THREAD

**Issue by petage** [the-hyjal-project/bugtracker#98]
**Describe Your Issue**

The drop rate of the quest item Middle of Gelkak's Key is currently set to 100% for all the 9 mobs it drops off of.

**Steps To Reproduce**

``SELECT * FROM `creature_loot_template` WHERE `item`='7499';``

https://classic.wowhead.com/item=7499/middle-of-gelkaks-key

**Expected Behavior**

The drop rate should be significantly lower as [Classic Wowhead](https://classic.wowhead.com/item=7499/middle-of-gelkaks-key#dropped-by) and [Thottbot](https://web.archive.org/web/20070514034651/http://thottbot.com/i7499) suggest.

**Comment by ratkosrb** [comment]
Fixed in https://github.com/vmangos/core/commit/c1db8e8f625ba5dbba3c03a11eafb4411e1557db
